### ISSUE TITLE
Error trying to parse settings: Unexpected trailing characters in Packages/User/mavensmate.sublime-settings:1:15

### ISSUE THREAD

**Issue by tomgersic** [joeferraro/MavensMate-SublimeText#192]
I've installed the latest Sublime Text 3 and MavensMate, but when I try to set up my workspace directory according to the settings in the Readme.md, I get this error:

Error trying to parse settings: Unexpected trailing characters in Packages/User/mavensmate.sublime-settings:1:15

("mm_workspace": "/Users/your_username/Projects")

**Comment by FelipeMiranda** [comment]
Works for me for the first line but when I add something like this it breaks

`{"auto_complete_selector": "source - comment, meta.tag - punctuation.definition.tag.begin"},
{auto_complete_triggers":
    [
        {
            "characters": "ng-controller=\"*",
            "selector": "punctuation.definition.string"
        }
    ]
}`
