### ISSUE TITLE
MavensMate Diff > Compare To... Error

### ISSUE THREAD

**Issue by doublesharp** [joeferraro/MavensMate-SublimeText#194]
OSX 10.8.4
ST3
MavensMate 0.35.1
Plugin 3.0.4

When I try to do a diff to the server I get the following in the ST3 console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
  File "/Users/justinsilver/Library/Application Support/Sublime Text 3/Packages/MavensMate/mavensmate.py", line 501, in is_enabled
    if util.is_config.mm_dir(d):
AttributeError: 'module' object has no attribute 'is_config'
```

**Comment by vickypanwar** [comment]
there is notactive MavensMate diff> compare to... ,how would i compare to.. active , please help,

thanks in Advanced.

**Comment by ralphcallaway** [comment]
@vickypanwar that doesn't sound like the same issue, please create another issue ... you'll need to provide a lot more diagnostic info (versions and logs), just take a look at some recent issues to get an idea of what is helpful
