### ISSUE TITLE
Plugin_host freezing Sublime Text 3, makes it impossible to use.

### ISSUE THREAD

**Issue by davidDeinDeal** [joeferraro/MavensMate-SublimeText#195]
Hello, 

For some reason plugin_host is freezing my sublime. I have the latest version and I am running OS X 10.7.5. Process plugin_host takes 100% of my cpu, completely freezes Sublime, I have to reboot it and it takes about two seconds to happen the same again. Right now I am not able to use it. 

![1](https://f.cloud.github.com/assets/2751125/992258/46839cc2-097a-11e3-9237-24191f09a2f3.jpg)
![2](https://f.cloud.github.com/assets/2751125/992259/4697e786-097a-11e3-839e-dfd2f7ea040e.jpg)

**Comment by liveforeverx** [comment]
Hi! I have the same issue on my Mac Os X.
Mac OS X version: 10.10.2 (14C1514)
Sublime Version: Build 3083

Since today, it happens 3 times, it freezes use all CPUs, I'll kill the plugin host and restart sublime.
I don't have MavensMate installed.
