### ISSUE TITLE
Saving Apex class returns "Success" but the apex class is not really updated in Salesforce

### ISSUE THREAD

**Issue by luiseluciani** [joeferraro/MavensMate-SublimeText#201]
I have been running into this issue for the past 2 days. I reinstalled both ST and the MavensMate plugin. I am running with the default settings. mm_compile_on_save is set to true.

When I save any apex class or trigger I get the below message popup on the panel. The panel doesn't disappear, even though mm_hide_panel_on_success is set to true. When I go to check that same class I saved through the Salesforce UI, my changes are not there. I am saving into a Sandbox environment.

Message on panel:
Compiling: testingClass.cls
Timestamp: Sat, 24 Aug 2013 16:19:21
Result: Success

**Comment by apexforcedev** [comment]
Looks like the problem is back, currently having the same issue described above and have tried the following:

turned off tooling, turned it back on
Cleaned the project

Still not writing files up to salesforce, just saving local, currently on Yosemite on a Mac. Problem seems to have just started today.

**Comment by apexforcedev** [comment]
Looks like I fixed it myself -- mm_compile_on_save was set to false (not sure how that got set to false), setting it to true fixed the problem.

**Comment by eswinehart** [comment]
I also ran into this problem today. Setting mm_compile_with_tooling_api to false is my workaround.

**Comment by PavelCZE** [comment]
Just run into this issue today. Changing mm_compile_with_tooling_api to false works for now.

**Comment by joem5815** [comment]
Just ran into this as well. Setting mm_compile_with_tooling_api worked as a workaround.

**Comment by doublesharp** [comment]
I'm having this issue as well, mm_compile_with_tooling_api=false works but makes it much slower overall.

**Comment by jkrepps** [comment]
Starting having this issues today, set mm_compile_with_tooling_api=false seems to work for now

**Comment by pescjjj** [comment]
This started happening for me this morning. Setting mm_compile_with_tooling_api=false seems to work.

**Comment by haripopuri** [comment]
It started happening on my new windows 7 PC. I disabled mm_compile_with_tooling_api to false and got the below error:

Result: [OPERATION FAILED]: An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.

I am not sure how to enable logging. Can you please help?
