### ISSUE TITLE
Keychain issue

### ISSUE THREAD

**Issue by orikkers** [joeferraro/MavensMate-SublimeText#228]
Result: [OPERATION FAILED]:Unable to retrieve password from the keychain store.

I know why I am getting this error (new laptop old project folder)

How can I force it to relogin?

**Comment by srajagopalan1712** [comment]
deleting config file and recreating the project does not solve this for me. I have added myc omment in another mm issue in this project I just found. Any help please.

**Comment by srajagopalan1712** [comment]
manually adding the password to keychain workaround works for me.

**Comment by haripopuri** [comment]
Hey,
How to open keychain app and key in password?
Thanks

**Comment by ruwanthalk** [comment]
I  was working on all day then I stopped for a while but the Sublime Text and the MavensMate  app was still on. Then I went back to the IDE and started to work. Really frustrating I can't save my work now. Yesterday also it was auto updated and given an error that "Apex.tmLanguage" was missing I fixed that after googling.
I even stopped the auto update in order to save the current version to develop without interruption. But all when wrong now.

**Comment by m0gul** [comment]
I'd love to just, you know... go back to version that WORKED

**Comment by OlegForce** [comment]
Click on the spotlight search and type "Keychain Access"  :) 

<img width="971" alt="screenshot 2015-10-09 16 04 51" src="https://cloud.githubusercontent.com/assets/2013992/10405602/91de0d4c-6e9f-11e5-8ee3-617af8f756a8.png">

**Comment by m0gul** [comment]
Sorry, spotlight search?

**Comment by OlegForce** [comment]
Oh :) you must be from the "other" camp. Keychain is on Mac :)



Sent from a rotary phone.




On Fri, Oct 9, 2015 at 2:35 PM -0700, "m0gul" <notifications@github.com> wrote:












Sorry, spotlight search?

**Comment by chrs85** [comment]
May i know what the fix for windows? There are not solution for Windows yet so far... can anyone help on this?

**Comment by OlegForce** [comment]
@chrs85 

per note from earlier - 

"delete the config directory, right click the project name in the Sublime Text sidebar, and MavensMate > Create MavensMate project"

**Comment by haripopuri** [comment]
Looks like you don't need MM app. Sublime is working without starting MM
app.


On Mon, Oct 12, 2015 at 8:03 AM, olegforce <notifications@github.com> wrote:

> @chrs85 <https://github.com/chrs85>
>
> per note from earlier -
>
> "delete the config directory, right click the project name in the Sublime
> Text sidebar, and MavensMate > Create MavensMate project"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate-SublimeText/issues/228#issuecomment-147426213>
> .
>



-- 
Thanks
హరి

**Comment by joeferraro** [comment]
correct @haripopuri v4/v6 do NOT require mm-app

**Comment by hunsakerjeff** [comment]
So what is the solution here for Windows users?  I cannot EDIT the project, no screen comes up.  I have 8 projects on this new PC that I moved from my old PC.  ONe of them is connected to GITHUB,

Thanks.

**Comment by ernestopuente** [comment]
Hi, my solution for this was create a new Project with a different name, and copy the file "config/.settings" from the new project to the old, and replace the "project_name" with the old project name.

After that, delete the new project :)

I hope that helps others.

**Comment by devvratarya** [comment]
For windows users, close the Mavensmate app, and start a new project using Mavensmate sublime plugin. That will fix the issue.

As mentioned by @haripopuri , Sublime works without starting MM
