### ISSUE TITLE
MavensMate not responding while creating new Project

### ISSUE THREAD

**Issue by markopb** [joeferraro/MavensMate-SublimeText#25]
Hi, 

Sorry to say that I still didn't start using the app. Even if I am now able to start the New Project creation wizard, I cannot complete it. After populating name, username and password and click on Create Project, complete form goes gray and loading indicator appears but it never ends, just hanging for minutes. 

The same behavior is when just click on tab Metadata. Loading indicator appears and never get chance to choose metadata or switch to some other tab again. The behavior is the same no mater if I enter some data on Details or Version Control  tab.

Hope this can help resolving the issue.

Thank you in advance

**Comment by Chitee** [comment]
Hi joeferraro,

Please tell me how can I update Mavensmate. I'm very new to this and I'm facing the same issue of indefinite loading & creation of Metadata when I try to create a new trigger. When I click on the option in Mavensmate for update, I get directed to the GitHub page. This GitHub page contains many versions of Mavesmate (most of them are Beta versions). I currently have version 10 which isn't Beta. So, I don't know how should I update mavensmate.
You said in one of the above posts to update Mavensmate and then run gem install mavensmate. Please tell me how to update mavensmate and also how to run gem install mavensmate...Please help. I'm a new salesforce greenhorn!!
