### ISSUE TITLE
Execute Apex not working

### ISSUE THREAD

**Issue by harshal-gajare** [joeferraro/MavensMate-SublimeText#259]
Execute Apex has stopped working for me after the latest update. No error/success message displays after executing the script. Debug log is not showing up either. Also there the cursor and code don't match while typing cursor is 2 spaces ahead of actual code being typed. Any help is really appreciated.

ST3 Build 3047 
MavensMate for Sublime Text v3.1.5
MavensMate app 0.35.7
Mac OSX

![screen shot 2013-11-05 at 9 48 41 pm](https://f.cloud.github.com/assets/5017173/1479789/aab54ec4-468e-11e3-8780-1c88dbd34ed3.png)

execute_apex
MM Log

[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_project", line 897, in execute_apex
KeyError: 'levels'
Traceback (most recent call last):
File lib.mm_project", line 897, in execute_apex
KeyError: 'levels'
[ENVIRONMENT]: MacOS 10.9, MavensMate 0.35.7

**Comment by dscloudlending** [comment]
@jhtest Hey how did you refresh the project? I am new to Mavensmate. I am trying to execute Apex code blocks but the options in Mavensmate > Apex Scripting always appear greyed out to me.
