### ISSUE TITLE
Objects in unmanaged installed packages do not show in object list

### ISSUE THREAD

**Issue by dschach** [joeferraro/MavensMate-SublimeText#286]
I installed an unmanaged package into a Developer Edition org and would like to customize it. I understand that managed objects may not appear in the object list (though I would like a way to add fields to those objects via the plugin) but an unmanaged installed package should not show up differently in the component list.

Please check if an object was installed via an unmanaged package and show it in the object (and other components) list. I can edit them just like any other object via the UI and would like to do so in Sublime Text 3 as well.

**Comment by shanerk** [comment]
Hi guys, MM is showing my unmanaged code in the metadata preview, and I can check them off.  But it is only downloading my Custom Objects, no Apex, Aura etc.  Any ideas?
