### ISSUE TITLE
Error loading syntax file "Packages/MavensMate/Apex.tmLanguage" after 3.3.0 upgrade

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate-SublimeText#292]
After upgrading the plugin to 3.3.0, sublime text is unable to parse the .tmLanguage file. 

Console Output

> error: Error loading syntax file "Packages/MavensMate/Apex.tmLanguage": Unable to open Packages/MavensMate/Apex.tmLanguage

**Comment by papapitufo** [comment]
This worked for me:
Preferences -> Package Control -> Upgrade/Overwrite all Packages
