### ISSUE TITLE
"Unable to retrieve password from the keychain store"

### ISSUE THREAD

**Issue by vraskin** [joeferraro/MavensMate-SublimeText#294]
I am getting this message when trying to refresh my project. I tried to Edit Project, but nothing is happening when I click that option under MavensMate. Thanks.

**Comment by srajagopalan1712** [comment]
+1, I just setup ST ST build 3065 and mavens 4.0.2. I create a Mavens project using our code checked out from p4. Even after my project is created, I see the Mavens create project popup still running and I had to go kill it. After I open my mavens project, I edit a class, save and it errors with above keychain store error. Edit project is not opening any dialog.

**Comment by m0gul** [comment]
+1
