### ISSUE TITLE
Sharing Rules won't sync

### ISSUE THREAD

**Issue by JodieM** [joeferraro/MavensMate-SublimeText#328]
Hi, no matter what I do I can't get Sharing Rules to sync to MavensMate. 

I edit the Project Settings, check AccountSharingRules in the Project Metadata, Update the Project, then Refresh the whole project from the Server. AccountSharingRules is not created as a folder in Mavens Mate and the AccountSharingRules in the Project Metadata gets unchecked. 

I thought that updating to 3.4.6 might fix this issue (as per https://github.com/joeferraro/MavensMate-SublimeText/issues/324) but it is still not working. 

I also tried turning off the tooling API as it is a production org (https://github.com/joeferraro/MavensMate-SublimeText/issues/316) and that did not fix it. 

Can Sharing Rules even be modified via the API or am I doing something wrong?

**Comment by ckoppelman** [comment]
I just added the following using API v31.0 and that worked.  Too bad it's not supported through the UI, and it's also too bad that [until API v.33.0 you can't use wildcards for grabbing SharingRules](http://www.salesforce.com/us/developer/docs/api_meta/Content/meta_sharingrules.htm):

```xml
    <types>
        <members>Account</members>
        <name>AccountSharingRules</name>
    </types>

```

**Comment by joralbert** [comment]
Hi, With mavensmate and sublime txt 3 I'm trying to get the CustomObjectOwnerSharingRules created on the org for a custom object.
I added to the mm_default_subscription the "OwnerSharingRule" value, and on the project->edit select thwhole list from the Metadata Subscription List, then refresh the Project Metadata and always the CustomObjectSharingRules, check that from the metadata, click on Update Project and nothing is added into the local directory relative to the Owner Sharing Rules. 

Mavensmate for sublime Text v4.0.5
