### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by MacHappy27** [joeferraro/MavensMate-SublimeText#337]
Timestamp: Wed, 19 Mar 2014 08:01:27
   Result: [OPERATION FAILED]: An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.

I was just performing a save.

**Comment by HebertOliveira** [comment]
I did the same configruration but It has not generate any log on the folder I've set.
Is there any other advice?
