### ISSUE TITLE
"Package Visibility: Method is not visible" Error

### ISSUE THREAD

**Issue by force2b** [joeferraro/MavensMate-SublimeText#340]
Getting an error in MavensMate when saving a class that references a global method in a managed package. I do not get this error saving the same code through Eclipse or through the Dev Console. The code saves fine through both of those, and it runs without error. Problem seems to be specific to saving through MM.

Operation: Compiling: C:\SalesForce.com\MavensMate\devSandbox\src\classes\xx_Integrations.cls
Timestamp: Tue, 25 Mar 2014 13:09:38
   Result: [COMPILE FAILED]: (xx_Integrations) Package Visibility: Method is not visible: lmsilt.ILTUtil.InvokePackageMethod(MAP<String,Object>)  (Line: 129)

**Comment by KalyanK** [comment]
Setting the attribute to false worked for me!! Thanks a lot joe
