### ISSUE TITLE
Cannot create new project

### ISSUE THREAD

**Issue by jeveleth** [joeferraro/MavensMate-SublimeText#35]
When I attempt to create a new project, I get the following error:

(INVALID_LOGIN) INVALID_LOGIN: Invalid username, password, security token; or user locked out.

SFDC Settings:
Project Name => Sandbox5
Salesforce Username => joshe@opendns.com.test
Salesforce Password => password
Server URL => test.salesforce.com

Local info:
ruby 1.8.7 (2011-12-28 patchlevel 357) [universal-darwin11.0]
"mm_workspace": "/Users/joshe/Projects"

ran the following about 30 min ago

```
ruby < <(curl -s https://raw.github.com/joeferraro/MavensMate-SublimeText/master/install.rb) 
```

**Comment by haripopuri** [comment]
I am getting "Account is required." error message.
