### ISSUE TITLE
Feature request: Play sound on compile events

### ISSUE THREAD

**Issue by dkurylo** [joeferraro/MavensMate-SublimeText#364]
Feature request:
Optionally, if Mavensmate successfully compiles a file (saves the file to server), a 'good' sound is played.
If it is unsuccessful, a 'bad' sound is played.

This way a user can close his eyes and think of next steps of implementation or have some rest if save is required to perform next steps.

**Comment by CloudJedi** [comment]
@dkurylo - Just checking i'm trying to check the link that you sent but unfortunately its not there anymore. Any chance we can review how we can make this work?

**Comment by dkurylo** [comment]
@CloudJedi the pull request has been already created, the feature has been already merged with the master and is available to the public for more than two years already.

**Comment by CloudJedi** [comment]
@dkurylo  - Thanks for the confirmation, may I know the process on how to enable it on the current version of the application? There was an upgrade where this feature got removed so I'm looking for ways to enable it.

**Comment by dkurylo** [comment]
@CloudJedi ah, I see. You are on MM v.7? AFAIR it's available on v6 only. You should install v.6 to re-enable it.
