### ISSUE TITLE
Issue creating New Project Windows 8

### ISSUE THREAD

**Issue by trevorrussell** [joeferraro/MavensMate-SublimeText#376]
When I create a new project the folders are created but at the end I get the error: "An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue." I enabled the logging and fount the following:

[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\Trevor\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\project.py", line 112, in retrieve_and_write_to_disk
    util.rename_directory(os.path.join(config.connection.workspace,self.project_name,"unpackaged"), os.path.join(config.connection.workspace,self.project_name,"src"))
  File "C:\Users\Trevor\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\util.py", line 231, in rename_directory
    os.rename(old_directory_name, new_directory_name)
WindowsError: [Error 5] Access is denied

**Comment by lewafa** [comment]
Which version was having the issue? I'm facing the same problem but still unable to fix it..

**Comment by sramadan** [comment]
I'm also having this issue on Windows 8. I'm using Sublime Text 3.0 build 3065

**Comment by VinitKumar-** [comment]
Hi,

I am facing this issue.Please suggest.

**Comment by pmf88** [comment]
Hi,
me too. any suggestion?

**Comment by Alexalex1432** [comment]
Having this issue currently on Windows 7 on Mavensmate for Sublime Text v4.0.2 and Sublime Text build 3083

**Comment by jeffrutter** [comment]
Hello,

I wanted to share what was the solution for me on this issue. I tried to create a new project in Mavensmate and was getting the same error code. I realized after uninstalling the McAfee trial software on my computer (To reinstall something better....) that it definitely had something to do with the firewall settings the trial software was using. My new AV service prompted me to decide whether to block the plug-in and after opting out of that I was able to create the 3 projects I had been trying to create all along.

Perhaps checking your Antivirus settings or Firewall settings could help!

**Comment by msrivastav13** [comment]
I can confirm this issue was due to McAfee.I removed McAfee and there was firewall blockage for few plugins.Once i got prompt to allow acess and now its all working great

**Comment by samuel012** [comment]
I just wanna share a fix for this. I'm also running on Windows 8, and has a McAfee AV pre-installed in my laptop. The McAfee Anti-Virus and Anti-Spyware version is 18. Simply turn it off when creating a project then just turn it on again afterwards. It worked for me.

**Comment by lucasbuyo** [comment]
I can confirm the same "the issue was due to McAfee", i've just uninstalled it and it works.
