### ISSUE TITLE
Getting [OPERATION FAILED]: list indices must be integers, not str error while saving a VF page

### ISSUE THREAD

**Issue by VinitKumar-** [joeferraro/MavensMate-SublimeText#395]
Hi,

I am getting [OPERATION FAILED]: list indices must be integers error while saving an Apex page.Below is the log for the same :-1: 
Creating new member
{"Body": "", "Name": "testmavensmate"}
Starting new HTTPS connection (1): ap1.salesforce.com
"POST /services/data/v28.0/tooling/sobjects/ApexPage HTTP/1.1" 400 None
---------------------
result from command execution
list indices must be integers, not str
<type 'exceptions.TypeError'>
list indices must be integers, not str
---------------------

---------------------
RESPONDING TO REQUEST
---------------------

{"body": "list indices must be integers, not str", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\vinit_kumar\\AppData\\Roaming\\Sublime Text 3\\Packages\\MavensMate\\mm\\lib\\request.py\", line 84, in execute\n    self.__printr(command_clazz.execute())\n  File \"C:\\Users\\vinit_kumar\\AppData\\Roaming\\Sublime Text 3\\Packages\\MavensMate\\mm\\lib\\commands\\metadata.py\", line 307, in execute\n    result = project.sfdc_client.compile_with_tooling_api(files, container_id)\n  File \"C:\\Users\\vinit_kumar\\AppData\\Roaming\\Sublime Text 3\\Packages\\MavensMate\\mm\\lib\\sfdc_client.py\", line 304, in compile_with_tooling_api\n    content_entity_id = response['id']\nTypeError: list indices must be integers, not str\n", "success": false}

**Comment by thajcak** [comment]
Had this issue come up today due to a Mismatched Class/File name. When I turned off the Tooling API the correct error came up and I could fix it. For me, this fixed the odd error.

**Comment by bradbumbalough** [comment]
Also had this issue when I had changes a class name without renaming the file. After doing that it worked  as normal.

**Comment by textual** [comment]
had same issue and from reading this list saw that it was due to a renamed file. i had a typo in original page name which also named the meta data file incorrectly as well. i changed the page and mate data files name but when i made a legit change to the page, i received the indices error. i read this thread and noticed the meta data file has a label for the page name and that was spelled incorrectly, fixed that and everything works. thanks github (and people on this thread)!

**Comment by driscom** [comment]
In case it helps others - I created a new component in MM and got this error when trying to save to server.  Tried to create same component in Salesforce with same name and found that the name was too long (40 char limit).

**Comment by hkeeble** [comment]
Had this issue when I renamed a class file, and the meta data file. Save the meta data file before trying to save the class after renaming.

**Comment by nwoolls** [comment]
Echoing previous feedback: disabling the tooling API option and then saving / compiling allowed the true error to be displayed in the console.

**Comment by mpaler** [comment]
My issue was that I dragged a visualforce page directly into my local project "page" folder and save it. Seems the ".page-meta.xml" is critical here. To fix, I deleted the file I brought in manually, and instead made the page using the Mavensmate > Metadata > New Visualforce Page menu item. Then I copied and pasted code into the blank page, saved and all was good.

**Comment by dodegaard** [comment]
Had same issue and root cause was the *cls-meta.xml file had disappeared for the cls file I was working on.  I removed the cls file from the server, cleaned project, readded the class and replaced the contents and all is good. Was not returning a line number with error which made our team think it was an MM issue and not SF compile.

**Comment by linked-2** [comment]
I am getting this error - shouldn't be getting it. Is it something I am doing or is this problem still lingering?

**Comment by rdehler** [comment]
I got this issue when I updated a project to use a new sandbox and tried to save a Visualforce page.

**Comment by clamdrive** [comment]
I have had this twice in recent weeks. Causee: renamed a class and had two files present locally with same class.

Might be overkill but it cleared the error:
- Deleted local extra file.
- Save the class code I want to a scratch file just in case.
- Metadata->Update project metadata
- Project->Clean Project
- Save class with required source code if refreshed version not what is required.
