### ISSUE TITLE
[OPERATION FAILED]: Resource  Not Found. Response content: [{u'errorCode': u'NOT_FOUND', u'message': u'Provided external ID field does not exist or is not accessible: <unknown>'}]

### ISSUE THREAD

**Issue by josetlaseca** [joeferraro/MavensMate-SublimeText#398]
I got this error when I try to save any change to either a class or a trigger.

I noticed (using the developer console) that Salesforce has changed its file extensions

.cls became .apxc
.trigger became .apxt

So I think that is the issue with SublimeText/Mavensmate that is preventing me to save any changes.

**Comment by sdhaliwal16** [comment]
@joeferraro I am getting the same error when I try to create a new Project and would not let me create a project.
WHen I open a project and try MavensMate > Utilities > Reset Metadata Container. The Reset Metadata Container button is not visible.  
What should I do?
