### ISSUE TITLE
Getting the error message 'An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue'

### ISSUE THREAD

**Issue by VinitKumar-** [joeferraro/MavensMate-SublimeText#405]
Hi ,

I turned off tooling API to false as I was getting a List indices error.Now,I am getting a different error while saving a VF page.Please find below the message:-

'HANDLING COMPILE!
{'body': 'list indices must be integers, not str', 'stack_trace': 'Traceback (most recent call last):\n  File "C:\\Users\\vinit_kumar\\AppData\\Roaming\\Sublime Text 3\\Packages\\MavensMate\\mm\\lib\\request.py", line 84, in execute\n    self.__printr(command_clazz.execute())\n  File "C:\\Users\\vinit_kumar\\AppData\\Roaming\\Sublime Text 3\\Packages\\MavensMate\\mm\\lib\\commands\\metadata.py", line 307, in execute\n    result = project.sfdc_client.compile_with_tooling_api(files, container_id)\n  File "C:\\Users\\vinit_kumar\\AppData\\Roaming\\Sublime Text 3\\Packages\\MavensMate\\mm\\lib\\sfdc_client.py", line 304, in compile_with_tooling_api\n    content_entity_id = response[\'id\']\nTypeError: list indices must be integers, not str\n', 'success': False}
Calling mm_interface
OPERATION: compile
{'params': {'files': ['C:\\Users\\vinit_kumar\\Mavensmate\\OutlookDev\\src\\pages\\acc.page']}, 'context': <sublime.View object at 0x000000000472A400>}
executing mm terminal call:
"C:\Program Files (x86)\MavensMate\App\python.exe" -E "C:\Users\vinit_kumar\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py" -o compile -c SUBLIME_TEXT_3
{"project_name": "OutlookDev", "workspace": "C:\\Users\\vinit_kumar\\Mavensmate", "files": ["C:\\Users\\vinit_kumar\\Mavensmate\\OutlookDev\\src\\pages\\acc.page"]}
response from mm: {"body": "An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.", "body_type": "text", "success": false}

HANDLING COMPILE!
{'body': 'An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.', 'success': False, 'body_type': 'text'}
Calling mm_interface
OPERATION: debug_log
{}
executing mm terminal call:
"C:\Program Files (x86)\MavensMate\App\python.exe" -E "C:\Users\vinit_kumar\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py" --ui -o debug_log -c SUBLIME_TEXT_3
{"project_name": "OutlookDev", "workspace": "C:\\Users\\vinit_kumar\\Mavensmate"}
response from mm: {"body": "UI Generated Successfully", "body_type": "text", "success": true, "time": "11.039999961853027"}

Calling mm_interface
OPERATION: compile
{'params': {'files': ['C:\\Users\\vinit_kumar\\Mavensmate\\OutlookDev\\src\\pages\\acc.page']}, 'context': <sublime.View object at 0x000000000472AA20>}
executing mm terminal call:
"C:\Program Files (x86)\MavensMate\App\python.exe" -E "C:\Users\vinit_kumar\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py" -o compile -c SUBLIME_TEXT_3
{"project_name": "OutlookDev", "workspace": "C:\\Users\\vinit_kumar\\Mavensmate", "files": ["C:\\Users\\vinit_kumar\\Mavensmate\\OutlookDev\\src\\pages\\acc.page"]}
response from mm: {"body": "An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.", "body_type": "text", "success": false}

HANDLING COMPILE!
{'body': 'An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.', 'success': False, 'body_type': 'text'}
Calling mm_interface
OPERATION: fetch_logs
{}
executing mm terminal call:
"C:\Program Files (x86)\MavensMate\App\python.exe" -E "C:\Users\vinit_kumar\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py" -o fetch_logs -c SUBLIME_TEXT_3
{"project_name": "OutlookDev", "workspace": "C:\\Users\\vinit_kumar\\Mavensmate"}
response from mm: {"body": "8 Logs successfully downloaded", "body_type": "text", "success": true, "time": "16.359999895095825"}
'

**Comment by atbussma** [comment]
Hi,

I've found this issue to occur when you do not have a metadata xml file associated with the component you are trying to save.  For the most part these "could" be generated.  If you have an existing *.page-meta.xml file you could just try renaming it acc.page-meta.xml (unless it has custom metadata - you might want to inspect that first).  Another option maybe better would be to save the file manually into the org using the Developer Console and then create a new MavensMate project for the org and download it (PITA).  This will give you an acc.page-meta.xml file.

For a feature request I'd really like it if MavensMate did the following in these cases (including the Tooling API handling):

```
default:  deploying using the Tooling API
if (error: failure suggests using Metadata API) {
  fallback:  deploying using the Metadata API
  if (!exists:  component metadata file) {
    attempt:  to pull one directly from the org and use that
    if (!exists:  component metadata file) {
        generate:  a default metadata file (to use for the request)
    }
  }
}
```

This would be great because then I never have to manually fiddle with "mm_compile_with_tooling_api" : true/false.  I never have to create a metadata file manually.

Alex
