### ISSUE TITLE
Sub-menus under Metadata, Debugging, Unit Testing disabled

### ISSUE THREAD

**Issue by KrishAnnangi** [joeferraro/MavensMate-SublimeText#407]
All Sub-menu items under Metadata, Debugging, Unit Testing, Apex Scripting, Server Diff, Utilities are disabled. I did not face any issues during Sublime Text 3 and MM installation. I am able to create and open a new project. I tried uninstalling, deleted directories, and re-installed but no luck.
I tried Sublime Text 3 build 3059 and MM 0.38.4 on Mac and it worked like a charm. I am facing issues on Windows PC

Using 
Sublime Text 3 build 3059
Windows 7 SP1 / [MavensMate.exe](http://push.mavensconsulting.netdna-cdn.com/mavensmate/builds/windows/MavensMate.exe)

Anyone faced similar issue? 

![Image](https://cloud.githubusercontent.com/assets/2177132/3396626/827c8928-fd12-11e3-8425-b7c000db7e62.png)
![Image](https://cloud.githubusercontent.com/assets/2177132/3396674/339425b8-fd13-11e3-884e-7e28357c9a54.png)
![Image](https://cloud.githubusercontent.com/assets/2177132/3396679/3f13c736-fd13-11e3-855d-d98635302024.png)
![Image](https://cloud.githubusercontent.com/assets/2177132/3396688/4f067c60-fd13-11e3-89e0-78338f264d47.png)

**Comment by dcobb2002** [comment]
I am encountering this same issue. I've been using MavensMate for months without encountering this problem before. Installed MavensMate API yesterday, so assume it's connected to that. Yesterday, after installing the API, I was able to continue to use the MavensMate sub menus.
