### ISSUE TITLE
Feature request: Allow to hide metadata "*-meta.xml" files in file explorer view

### ISSUE THREAD

**Issue by jheuvel** [joeferraro/MavensMate-SublimeText#408]
I believe this could be a useful feature for everyone that thinks a large list of classes/pages etc are hard to navigate... 
There may be a way to do this using a sublime plugin, but I think it could fit nicely with the MM app...

**Comment by cnaccio** [comment]
This helped a ton. I think everyone would prefer this be a default in MavensMate. Thanks!
