### ISSUE TITLE
Project Upgrade UI Not Opening

### ISSUE THREAD

**Issue by dbleier** [joeferraro/MavensMate-SublimeText#412]
I am running sublime-text 3, build 3059 on Ubuntu 13.10, Mavensmate 3.5.0

I have 1 project that when I try to do anything it says, "Your MavensMate project needs to by upgraded. Opening the upgrade UI." But nothing happens. Also if I try Edit Project, same thing. It's only this 1 project, all other projects work fine and upgraded fine.

The sublime console had the following to say:
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: compile
[MAVENSMATE]: {'params': {'files': ['/home/dovid/mm_workspace/Partners In Torah Dbdev Sandbox/src/classes/ManageDays.cls']}, 'context': <sublime.View object at 0x7f4b48db91d0>}
[MAVENSMATE]: executing mm terminal call:
[MAVENSMATE]: /usr/bin/python /home/dovid/.config/sublime-text-3/Packages/MavensMate/mm/mm.py -c SUBLIME_TEXT_3 -o upgrade_project --ui
[MAVENSMATE]: {"workspace": "/home/dovid/mm_workspace", "project_name": "Partners In Torah Dbdev Sandbox", "files": ["/home/dovid/mm_workspace/Partners In Torah Dbdev Sandbox/src/classes/ManageDays.cls"]}
[MAVENSMATE]: response from mm: {"body": "", "stack_trace": "Traceback (most recent call last):\n  File \"/home/dovid/.config/sublime-text-3/Packages/MavensMate/mm/lib/request.py\", line 70, in execute\n    tmp_html_file = util.generate_ui(self.operation,self.payload)\n  File \"/home/dovid/.config/sublime-text-3/Packages/MavensMate/mm/lib/util.py\", line 464, in generate_ui\n    creds = config.project.get_creds()\n  File \"/home/dovid/.config/sublime-text-3/Packages/MavensMate/mm/lib/project.py\", line 918, in get_creds\n    password = util.get_password_by_key(id)\n  File \"/home/dovid/.config/sublime-text-3/Packages/MavensMate/mm/lib/util.py\", line 165, in get_password_by_key\n    items = gnomekeyring.find_network_password_sync(key, 'MavensMate: '+key)\nNoMatchError\n", "success": false}

Same thing if I try to open the Edit Project UI. I have not recently changed my org password although it does look like there is some sort of credentials issue. Any suggestions?

Thanks,
Dovid

**Comment by Drobi83** [comment]
Yes, this is the same issue here.
