### ISSUE TITLE
Problem Creating New Project [Linux | Ubuntu 14.04]

### ISSUE THREAD

**Issue by daniel-huckins** [joeferraro/MavensMate-SublimeText#440]
Big fan of the plug-in for Windows, trying to use it on linux (maybe slightly better than a complete noob) but running into a few problems. 
Its not letting me create a New Project, getting the following from the console;
"""
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
WARNING:process:Could not import subprocess32 module, falling back to subprocess module
[MAVENSMATE]: executing mm terminal call:
[MAVENSMATE]: /usr/local/lib/python2.7 /home/daniel/.config/sublime-text-3/Packages/MavensMate/mm/mm.py -c SUBLIME_TEXT_3 -o new_project --ui
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: /bin/sh: 1: /usr/local/lib/python2.7: Permission denied

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 440, in is_enabled_
    ret = self.is_enabled()
  File "/home/daniel/.config/sublime-text-3/Packages/MavensMate/mavensmate.py", line 1945, in is_enabled
    fn, ext = os.path.splitext(active_view.file_name())
  File "X/posixpath.py", line 125, in splitext
  File "X/genericpath.py", line 92, in _splitext
AttributeError: 'NoneType' object has no attribute 'rfind'
"""
the Traceback repeats in the console 5 times
Also, the permission on python2.7 is 'drwxrwxrwx' so should have universal access (right?)

help/insight is appreciated, thanks

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe

**Comment by aleramesh** [comment]
I ran into the same problem today and I changed the owner of the workspace from root to my username and it worked. Hope it helps future googlers :)
