### ISSUE TITLE
I cant create new project (The local MavensMate server did not respond properly)

### ISSUE THREAD

**Issue by mefisto506** [joeferraro/MavensMate-SublimeText#454]
Hello when i install MavensMate and i try create new project i get message:

The local MavensMate server did not respond properly. This likely means it is not running or it is malfunctioning. Try restarting your text editor and MavensMate.app.

I have seen such problems like this but usually helped update. I don't know what i should do to fix this. 
I use sublime text 3, mavensmate v3.5.2, windows 8 64x
Please help me :)

**Comment by mukundgadave** [comment]
I spent many hours to fix this issue and finally I am able  to start with MavensMate with Sublime Text.
Open Sublime Text Edit, Navigate to MavensMate > Settings > User
1. Find "mm_server_port", you will get default value 7777.
2. Change this port to some other value, I did 7779 and it worked for me. (New port value must not be used for any other service/process)
