### ISSUE TITLE
Enhancement: Add Reset Metadata Container to Command Pallette

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate-SublimeText#459]
Currently you have to use menus to reset a metadata container, let's add it to command pallette so we can launch it directly.

**Comment by CSTufts** [comment]
Yes please, I would like to keybind it, unless i can already do that without adding it to the command palette.

**Comment by joeferraro** [comment]
fyi: reset metadata container has gone away in v5, feel free to install the beta: https://github.com/joeferraro/MavensMate-SublimeText#install

**Comment by CSTufts** [comment]
does the need for it go away Joe?
I will try it, i suppose. I rely heavily on it for work, how stable is it?

**Comment by joeferraro** [comment]
@CSTufts 

> does the need for it go away Joe?

yes, the way we're interfacing with the Tooling API has fundamentally changed. We create, submit, and delete the metadata container upon a successful compile vs. holding onto it as we did in v4 (this decision was based on discussions with Salesforce)

> I rely heavily on it for work, how stable is it?

quite stable (we've been running betas for months). you can certainly try it out and revert if it becomes an issue for you

**Comment by fusion27** [comment]
* per @CSTufts, I'd also like to set up a key binding to the **Reset Metadata Container** command [shown here](https://trello-attachments.s3.amazonaws.com/55e78fb2a0c984e520a612ec/1380x914/a8931702d7d50d7cf571d1af7939ec36/MMSublimeTweaker-02.jpg).  
* Seems like I fire this command 10-20 times/hour, would be great to reduce that to a keyboard shortcut.  
* Anyone possibly know how to set this one up?
