### ISSUE TITLE
MavensMate not responsive on OSX 10.7.x

### ISSUE THREAD

**Issue by IulianChiriac** [joeferraro/MavensMate-SublimeText#461]
Hello,

First, Thank you for such a GREAT plugin. I was happily and successfully using MavensMate till today.

I could not do anything today. I could not refresh projects or create new ones. At least the interface opened, but then I upgraded. I though maybe I needed to in order to get it to work.

After upgrading to MavensMate 3.5.4 and API 0.2.2, I click on MavensMate in the Sublime Text menu, then go to Project > New Project and nothing happens. 

Also no existing project refresh from server or anything else.

In the logs I get : 

OPERATION: new_project
{}
MmInstaller -->
mm command: 
'/Users/username/Library/Application Support/Sublime Text 3/Packages/MavensMate/mm/mm' -o new_project --ui -c SUBLIME_TEXT_3
{}
checking for updated mm version
mm is up to date (0.2.2), no further action needed
response from mm: 

It seems that MavensMate does not respond anything to requests. 

How can I fix it ? I really like MavensMate and I have a lot of work to do in the next few hours/days.

Thank you.

**Comment by karthikkornalies** [comment]
I'm having issue while creating new project. SublimeText/Mavensmate doesn't prompts the browser window to enter credentials. 

Sublime text : Build 3083

Mavens Mate for SublimeText : v4.0.5

Operating System : Windows 8

Mavens Console Message while creating new Project.

[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\Karthik\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --ui -o new_project
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: {


    "body": "UI Generated Successfully", 


    "body_type": "text", 


    "success": true, 


    "time": "1.2960000038146973"


}


[MAVENSMATE] failed to send community activity

-------
Im not sure what im missing here. Any thoughts would be really appreciated.
