### ISSUE TITLE
[Errno 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by geeljire** [joeferraro/MavensMate-SublimeText#470]
I'm increasingly being greeted by this error message when communicating with Salesforce:

`[Errno 10054] An existing connection was forcibly closed by the remote host`

This happens during compile, refresh, test runs, deploy, and other operations. Here's Sublime's console output for a refresh operation that returned this error:

```
[MAVENSMATE]: OPERATION: refresh
[MAVENSMATE]: {'context': <MavensMate.mavensmate.RefreshFromServerCommand object at 0x00000028CA6E3CF8>, 'params': {'directories': ['C:\\Users\\myusername\\projects\\myproject\\src']}}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\myusername\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.exe" -o refresh -c SUBLIME_TEXT_3
[MAVENSMATE]: {"workspace": "C:\\Users\\myusername\\projects", "project_name": "myproject", "directories": ["C:\\Users\\myusername\\projects\\myproject\\src"]}
[MAVENSMATE]: response from mm: {"body": "[Errno 10054] An existing connection was forcibly closed by the remote host", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 61, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project\", line 75, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client\", line 102, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client\", line 108, in login\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sforce.base\", line 490, in login\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 542, in __call__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 602, in invoke\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 637, in send\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http\", line 77, in send\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http\", line 118, in u2open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 404, in open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 422, in _open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 382, in _call_chain\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 1222, in https_open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 1187, in do_open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 1067, in getresponse\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 409, in begin\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 365, in _read_status\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\socket\", line 476, in readline\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\ssl\", line 246, in recv\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\ssl\", line 165, in read\nerror: [Errno 10054] An existing connection was forcibly closed by the remote host\n", "success": false}
```

I'm on Windows 8.1 with Sublime Text Build 3065 and MavensMate plugin v3.5.4.

**Comment by Gulshan-Doorgah** [comment]
I am affected by this problem also. Please help.

**Comment by AvailableUser** [comment]
I am seeing this in my production org, but not in my sandbox org.
It showed up in my sandbox org and then went away by itself, but in production it persists, even after multiple restarts.

**Comment by igolikov** [comment]
That means that SalesForce closes connection because 'Concurrent API Request Limit' is exceed

https://help.salesforce.com/HTViewHelpDoc?id=integrate_api_rate_limiting.htm

**Comment by AvailableUser** [comment]
I would like to reopen this bug.
My API usage is at 75% for the past 24 hours and I am still getting this error.
Is there perhaps a way to capture an error message that the Salesforce server sends when it closes the connection?

**Comment by igolikov** [comment]
I have the same issue with production instance (with sandbox it works fine). Also SF plugin for Eclipse doesn't work with production too and I receive same kind of error - Connection reset. 
That looks like SalesForce issue.

**Comment by igolikov** [comment]
AvailableUser, I just tried to use it via VPN connection and everything works fine

**Comment by AvailableUser** [comment]
The problem resolved itself after 3 days.
I wonder if there isn't a way to display a more meaningful error: include which remote host closed the connection and any error messages it may have sent.

**Comment by Rana283** [comment]
HI team am using sublime for Angularjs development here is problem with am not able to prettify the HTML ,css and Js am useing packagecontrol code:

 import urllib.request,os,hashlib; h = '2915d1851351e5ee549c20394736b442' + '8bc59f460fa1548d1514676163dafc88'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); urllib.request.install_opener( urllib.request.build_opener( urllib.request.ProxyHandler()) ); by = urllib.request.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); print('Error validating download (got %s instead of %s), please try manual install' % (dh, h)) if dh != h else open(os.path.join( ipp, pf), 'wb' ).write(by)  

Here is the Error am getting :ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
