### ISSUE TITLE
No Mavensmate Menu after Installing via Package Control

### ISSUE THREAD

**Issue by klawson23** [joeferraro/MavensMate-SublimeText#483]
Hi,

After following the [OS X Upgrade Instructions](http://mavensmate.com/Upgrade_Help) and manually deleting the MavensMate directory from the Packages folder and reinstalling MavensMate via Package Control, no MavensMate menu appears in Sublime text.

I am on OS X 10.9.4, Sublime Text build 3065, and I have downloaded version 4.0.3 of Mavensmate. My system is running Python 2.7.5 if that matters.

Thanks for whatever help you can provide!
Kyle

**Comment by sacsha30** [comment]
Hi 

I installed sublime 2.0.2 and tried installing mavensmate. But in install package list it is not showing mavenmate as option.

Please let me know if anybody else has faced the same problem.

TIA

**Comment by steals** [comment]
Hello, @sacsha30 
Tyr to install SublimeText 3 http://www.sublimetext.com/3
I don't think the SublimeText version 2 is supported.

**Comment by sacsha30** [comment]
Strange that it is not available for most stable version of Sublime but is only available for beta version.
