### ISSUE TITLE
Questions on to-from MM and SF

### ISSUE THREAD

**Issue by kennesk** [joeferraro/MavensMate-SublimeText#486]
This isn't an issue but I cannot find any docuemntation on what the difference is between some MM commands.

For instance, what is the difference between these commands (they all pull from the server):
- Clean Project
- Refresh from Server
- Edit/Update Project
(Also, is there any way to avoid having *all* the meta.xml files pulled over?)

Also, what is the difference between these commands (they both push to the server):
- Deploy to Server
- Compile Project

Thanks.

**Comment by haripopuri** [comment]
Hi

With new MavensMate app, the file saving time is increased a lot and sometimes it even throws timeout errors. Do you know why?

Thanks
