### ISSUE TITLE
Cannot save to Salesforce in one project

### ISSUE THREAD

**Issue by ghost** [joeferraro/MavensMate-SublimeText#499]
Hello.  I have one project where I suddenly cannot save any changes to Salesforce.  I see a Success result in Sublime Text, but nothing happens in the sandbox.  I can create a new file and it will be created in the sandbox, but when I edit the file the changes are not saved to the sandbox.

This was working fine a couple days ago.  I have other projects where saving works fine.

I started a brand new project for the same sandbox and it still doesn't work.  I have a colleague working in the same sandbox also using Sublime + MavensMate and he can save his work.  I ran Eclipse and was able to save to the sandbox.

I'm running OS X 10.9.4, Sublime Text build 3065, MavensMate 4.0.2

In the mm.log file

```
Updating existing member
{"Body": "public with sharing class AAA_TEST {\n\tpublic AAA_TEST() {\n// comments\t\n\t}\n}\n", "ContentEntityId": "01pJ00000006p4WIAQ", "MetadataContainerId": "1dcJ0000000D9ceIAC"}
Starting new HTTPS connection (1): healthleads--CXFBUILD.cs10.my.salesforce.com
"POST /services/data/v30.0/tooling/sobjects/ApexClassMember HTTP/1.1" 400 None
----> post to tooling member failed
[MAVENSMATE CAUGHT ERROR]
None

---------------------
result from command execution
None
<type 'NoneType'>
---------------------


---------------------
RESPONDING TO REQUEST
---------------------


None
```

In the Sublime Text console

```
[MAVENSMATE]: OPERATION: compile
[MAVENSMATE]: {'params': {'files': ['/Users/dcheng/Documents/MavensMate/Health Leads CXFBUILD/src/classes/AAA_TEST.cls']}, 'context': <sublime.View object at 0x1111d7090>}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: '/Users/dcheng/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/mm/mm' -o compile -c SUBLIME_TEXT_3
[MAVENSMATE]: {"files": ["/Users/dcheng/Documents/MavensMate/Health Leads CXFBUILD/src/classes/AAA_TEST.cls"], "project_name": "Health Leads CXFBUILD", "workspace": "/Users/dcheng/Documents/MavensMate"}
[MAVENSMATE]: response from mm: 
[MAVENSMATE]: Issue handling compile result in callback
[MAVENSMATE]: No JSON object could be decoded
[MAVENSMATE]: HANDLING COMPILE!
[MAVENSMATE]: 
```

**Comment by bolaurent** [comment]
Not much detail to add, but I just experienced the same problem. "Clean project" resolved it for me. 

My project had one class and one page. Each of them would apparently compile correctly, but the content on the server was not being updated. I checked the mm log, and discovered the following (at the tail end of the log, setting DEBUG):

Starting new HTTPS connection (1): cs14.salesforce.com
"POST /services/data/v31.0/tooling/sobjects/ApexPageMember HTTP/1.1" 400 None
----> post to tooling member failed
[MAVENSMATE CAUGHT ERROR]
None

---------------------
result from command execution
None
<type 'NoneType'>
---------------------


---------------------
RESPONDING TO REQUEST
---------------------


None
