### ISSUE TITLE
Saving files to Salesforce not working - Result hanging

### ISSUE THREAD

**Issue by aj2taylo** [joeferraro/MavensMate-SublimeText#500]
Starting this morning, when I save a file, the panel shows the "Result" line spinning.

I've restarted Mavensmate a few times, refreshed the project from Salesforce to eliminate any files being out of synch.

I periodically get a "Success" response, but if I check the Last Modified Date on the file on Salesforce, it shows it wasn't updated at all.

Checking the Sublime Text console, I see the following:

Writing file [local file path]/src/classes/Branch_Plan_Extension.cls with encoding UTF-8 (atomic)
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: compile
[MAVENSMATE]: {'context': <sublime.View object at 0x00000000042BCF98>, 'params': {'files': ['[local file path]\src\classes\Branch_Plan_Extension.cls']}}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\Andrew Taylor\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.exe" -o compile -c SUBLIME_TEXT_3
[MAVENSMATE]: {"project_name": "[project name]", "files": ["[local file path]\src\classes\Branch_Plan_Extension.cls"], "workspace": "C:/Users/Andrew Taylor/mavensmate"}
[MAVENSMATE]: response from mm: 
[MAVENSMATE]: Issue handling compile result in callback
[MAVENSMATE]: No JSON object could be decoded
[MAVENSMATE]: HANDLING COMPILE!
[MAVENSMATE]: 

Any thoughts?

**Comment by aykut-github** [comment]
I had same issue.I tried "mm_compile_with_tooling_api" = false but it was not worked. At the end  I solve it by MavenMate->Utilities->Reset Metadata Container. I hope it can work for some of other cases.
