### ISSUE TITLE
OPERATION FAILED error when compiling visualforce page to production

### ISSUE THREAD

**Issue by barrettcox80** [joeferraro/MavensMate-SublimeText#504]
Seeing an OPERATION FAILED error in the console when I attempt to compile a Visualforce page on a production site.

- Sublime Text 3, Mavensmate v4.0.2, Mac OS X 10.9.5
- mm_compile_with_tooling_api set to false in my project settings

Result: [OPERATION FAILED]: {"checkOnly": false, "createdByName": "Admin Supportpay", "ignoreWarnings": false, "startDate": "2014-10-30T23:41:49.000Z", "status": "Failed", "numberTestErrors": "38", "numberComponentErrors": "0", "numberComponentsDeployed": "1", "lastModifiedDate": "2014-10-30T23:42:02.000Z", "runTestsEnabled": true, "createdDate": "2014-10-30T23:41:49.000Z", "createdBy": "005i0000001DqMJ", "details": {"componentSuccesses": [{"created": false, "createdDate": "2014-10-30T23:41:50.000Z", "componentType": null, "fileName": "unpackaged/package.xml", "success": true, "changed": true, "fullName": "package.xml", "deleted": false}, {"created": false, "createdDate": "2014-10-30T23:41:50.000Z", "success": true, "componentType": "ApexPage", "fileName": "unpackaged/pages/RegistrationIframeLearnMore.page", "id": "066i0000004JdAzAAK", "changed": true, "fullName": "RegistrationIframeLearnMore", "deleted": false}], "runTestResult": {"numTestsRun": "38", "numFailures": "38", "failures": [{"time": "-1.0", "name": "TestRig", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWOAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TestRig"}, {"time": "-1.0", "name": "testPDW", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000002vle4AAA", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "testPDW"}, {"time": "-1.0", "name": "TestTaskobject", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWPAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TestTaskobject"}, {"time": "-1.0", "name": "TestUpdateOfMerchantOnContact", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003V8lqAAC", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TestUpdateOfMerchantOnContact"}, {"time": "-1.0", "name": "TodoList", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWQAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TodoList"}, {"time": "-1.0", "name": "TransactionController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWRAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TransactionController"}, {"time": "-1.0", "name": "TransactionControllerTest", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWSAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TransactionControllerTest"}, {"time": "-1.0", "name": "TransactionWrapper", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWTAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TransactionWrapper"}, {"time": "-1.0", "name": "TransactionWrapperTest", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWUAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TransactionWrapperTest"}, {"time": "-1.0", "name": "TriggerTests", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWVAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TriggerTests"}, {"time": "-1.0", "name": "testSendEmailFlowPlugin", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWbAAO", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "testSendEmailFlowPlugin"}, {"time": "-1.0", "name": "Test_ChatterAssassin", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000002vleKAAQ", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "Test_ChatterAssassin"}, {"time": "-1.0", "name": "RegWizardTest", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFW5AAO", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line 219, column 13: Method does not exist or incorrect signature: [RegWizardNew].saveFixedOrders()", "packageName": "RegWizardTest"}, {"time": "-1.0", "name": "ReportsController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFW6AAO", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "ReportsController"}, {"time": "-1.0", "name": "RestAttribute", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFW7AAO", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "RestAttribute"}, {"time": "-1.0", "name": "RestToDo", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFW8AAO", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "RestToDo"}, {"time": "-1.0", "name": "SendEmail", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWCAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SendEmail"}, {"time": "-1.0", "name": "SiteLoginController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWDAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SiteLoginController"}, {"time": "-1.0", "name": "SiteLoginSampleSFController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003V8llAAC", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SiteLoginSampleSFController"}, {"time": "-1.0", "name": "SiteRegisterController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWEAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SiteRegisterController"}, {"time": "-1.0", "name": "SMW_AZMerchantsController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWAAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SMW_AZMerchantsController"}, {"time": "-1.0", "name": "SMW_CaseCompCtrl", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWBAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SMW_CaseCompCtrl"}, {"time": "-1.0", "name": "SMWLoginController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFW9AAO", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SMWLoginController"}, {"time": "-1.0", "name": "startHereController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWZAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "startHereController"}, {"time": "-1.0", "name": "StringUtil", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWFAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "StringUtil"}, {"time": "-1.0", "name": "submitForApproval", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWaAAO", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "submitForApproval"}, {"time": "-1.0", "name": "SubscriptionController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWGAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SubscriptionController"}, {"time": "-1.0", "name": "SubscriptionPaymentBatch", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWHAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SubscriptionPaymentBatch"}, {"time": "-1.0", "name": "SubscriptionPaymentBatchTest", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWIAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SubscriptionPaymentBatchTest"}, {"time": "-1.0", "name": "SubscriptionPaymentSchedular", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWJAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SubscriptionPaymentSchedular"}, {"time": "-1.0", "name": "SummaryEmailsBatch", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWKAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SummaryEmailsBatch"}, {"time": "-1.0", "name": "superSort", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000002vleFAAQ", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "superSort"}, {"time": "-1.0", "name": "SupportOrderHistoryController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWLAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SupportOrderHistoryController"}, {"time": "-1.0", "name": "SupportOrderInsertController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWMAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SupportOrderInsertController"}, {"time": "-1.0", "name": "SupportPayLoginController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003UokFAAS", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "SupportPayLoginController"}, {"time": "-1.0", "name": "TEGenController", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000002vleEAAQ", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "TEGenController"}, {"time": "-1.0", "name": "XMLDom", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWXAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "XMLDom"}, {"time": "-1.0", "name": "WeeklySummaryEmails", "methodName": null, "stackTrace": {"@xsi:nil": "true"}, "id": "01pi0000003TFWWAA4", "namespace": {"@xsi:nil": "true"}, "type": "Class", "message": "line -1, column -1: Previous load of class failed: regwizardtest", "packageName": "WeeklySummaryEmails"}], "totalTime": "0.0"}}, "done": true, "numberComponentsTotal": "1", "numberTestsTotal": "38", "numberTestsCompleted": "0", "id": "0Afi0000006yLZaCAM", "rollbackOnError": true, "success": false, "completedDate": "2014-10-30T23:42:02.000Z"}

**Comment by ralphcallaway** [comment]
closing this, saving metadata to production isn't currently a feature, deploy should be used instead from a sandbox environment
