### ISSUE TITLE
How to preselect listed metadata when deplyoing to server from package.xml cloned from Git?

### ISSUE THREAD

**Issue by SebasCanseco** [joeferraro/MavensMate-SublimeText#506]
Whenever I pull from the git repo of my team and there's new metadata I need to deploy those changes to my sandbox/dev org. I use the Mavensmate Deploy To Server feature, but I've realized that the preselected metadata doesn't match the new meta or even changes I did.

Don't you think it would be awesome that Mavensmate pre populated the metadata to deploy to the server from the package.xml you have locally? And that should work when you're editing the project metadata as well. 

What are your thoughts on this?

**Comment by ralphcallaway** [comment]
already implemented closing, @SebasCanseco please re-open if you don't think the request is truly in there
