### ISSUE TITLE
Unable to compile on MavenMate

### ISSUE THREAD

**Issue by vinjoshi** [joeferraro/MavensMate-SublimeText#511]
I installed Maven(as plugin to sublime) and created the project for SFDev. The metadata is downloaded but under MavensMate, only open project and create project options are enabled. Other options under MavensMate are disabled as well. I’m not able to deploy the class to server nor I'm able to create new metadata from menu.. Any Idea what can be the issue? One of my friend had license which he's not using, I'm using his license. can that be the issue?

**Comment by ralphcallaway** [comment]
@vinjoshi using your buddies license isn't going to be the issue

sounds like you just might not be clicking in the right place, for those options to show up you'll want to make sure the active file in the editor is a salesforce file

can you post some screenshots of what's going on? so we can get a better picture of your issue
