### ISSUE TITLE
Unable to Create a Project from an Existing Folder in Workspace

### ISSUE THREAD

**Issue by atbussma** [joeferraro/MavensMate-SublimeText#517]
When I open a folder in Sublime Text and then right click on that folder the MavensMate context menu appears empty as in the following picture:

![mavensmate](https://cloud.githubusercontent.com/assets/6679374/5115312/d0befe5e-700d-11e4-88b0-ae6f19781ef6.png)

This is without regard to the folder being within the workspace or not.  I was hoping to create a new MavensMate project for an existing Force.com 'project' stored in a Git repository on my machine.  As a workaround I am able to create a new MavensMate project and then clone my repository into that directory.

Versions:
Sublime Text 3 (beta)
MavensMate v4.0.1

**Comment by ralphcallaway** [comment]
@atbussma the create project flow could use some work (and we do accept contributions from community members)

a quick fix will get this working, first move the project out of your workspace, then open it in sublime and create the new project, which will in turn move it back to the workspace

simply put, the new project page isn't smart enough to tell that the project it's creating already exists in it's current location, so no reason to care about it's presence

**Comment by seanhharrison** [comment]
What is the secret formula?

![screenshot](https://cloud.githubusercontent.com/assets/808408/9022449/55601c74-383b-11e5-93e9-70931e3cb988.png)
