### ISSUE TITLE
Folder sidebar becomes empty in Sublime Text 3

### ISSUE THREAD

**Issue by dmcheng** [joeferraro/MavensMate-SublimeText#519]
I have noticed with some projects that the folder file list in the left sidebar will become empty, though nothing has happened to the files on my local drive.  If I reset the metadata container, the file list reappears immediately, but at some point it will disappear again.

I have tried deleting the project and re-creating it, but eventually the file list will disappear again.

This has happened to about 20% of the projects I've worked on.  I can't see any pattern in them.

Has anyone else seen this?  I'm running OS X Mavericks 10.9.5 with the latest Sublime Text 3 and Mavensmate.

**Comment by ralphcallaway** [comment]
closing for now, this is a ST3 issue

**Comment by jkarttunen** [comment]
Seeing this again, Build 3083

**Comment by eastdacc** [comment]
For me it isn't completely empty, it shows the top folder and it is fixed by right clicking in it and doing a 'Find in folder...'
