### ISSUE TITLE
can't update Mavensmate ...I don't even know where to start

### ISSUE THREAD

**Issue by hstephens** [joeferraro/MavensMate-SublimeText#520]
Hello, 
I am still pretty new to this and tried to download this program and plugin in October. I got frustrated and stopped. 

I wanted to give it another try, but after redownloading Sublime Text, all of my previous settings were in there again. I am wondering if there is a way to get a clean slate and attempt it again from scratch. Is this possible?
When I tried to download the new update, Nothing happens on the screen, but in the console I see errors (below). Can someone please help me with the error or to get a clean slate?
DPI scale: 1.25
startup, version: 3065 windows x32 channel: stable
executable: /C/Program Files (x86)/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files (x86)/Sublime Text 3
packages path: /C/Users/hstephens/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/hstephens/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 8
zip path: /C/Program Files (x86)/Sublime Text 3/Packages
zip path: /C/Users/hstephens/AppData/Roaming/Sublime Text 3/Installed Packages
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 2 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 169 cache hits: 169
pre session restore time: 0.0883834
using gamma: 1.9 (err: 81.5966)
startup time: 0.138383
first paint time: 0.140383
launching: /C/Program Files (x86)/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin MavensMate.config
reloading plugin MavensMate.install
reloading plugin MavensMate.mavensmate
forcing MavensMate Diff to reload itself
loaded 837 snippets
reloading plugin MavensMate.util
plugins loaded
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: >>> starting threaded MavensMate server!
[MAVENSMATE] skipping update check
[WinError 2] The system cannot find the file specified

**Comment by ralphcallaway** [comment]
@hstephens doesn't look like you've posted to this for some time, going out on a limb and assuming that a clean install fixed things for you and closing it, please re-open if that's not the case
