### ISSUE TITLE
undefined symbol: rl_signal_event_hook when creating a new project

### ISSUE THREAD

**Issue by kennethyeung815** [joeferraro/MavensMate-SublimeText#523]
I'm getting a symbol lookup error whenever I'm trying to create a new project. I've tried re-installing sublime, mavensmate, bash and python nothing has worked so far. Any help will be much appreciated.

[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: /home/kenneth/.config/sublime-text-3/Packages/User/MavensMate/mm/mm -c SUBLIME_TEXT_3 --ui -o new_project
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook

sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook
{
    "body": "UI Generated Successfully", 
    "body_type": "text", 
    "success": true, 
    "time": "1.1317319869995117"
}

**Comment by ralphcallaway** [comment]
yikes, this is pretty low level, this could be a tricky one to sort out

if you guys are still running into this please enable plugin logging http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging and post the relevant logs

also, please provide details about your os and architecture and python version (i.e. windows 8, 64 bit, python 2.7)

the requests to the underlying api that drives the plugin are done over the command line and seems something is going wrong there

**Comment by ralphcallaway** [comment]
as @kennethyeung815 points out base 4.3 got a bug that seems to be causing issues see https://bugs.archlinux.org/task/39533

looks like the bug was fixed back in march, but couldn't tell from the details

since this doesn't appear to be a st3 mm plugin issues, closing this out, but re-open if you feel that's not the case and can provide some additional diagnostic details

**Comment by Galiaf47** [comment]
I am trying to install mm on my arch linux at home and I've got this error too. Don't know how to fix it.

**Comment by dantuck** [comment]
This is still not resolved. I am unable to downgrade to bash 4.2 so if anyone has another workaround that would be great!

**Comment by Galiaf47** [comment]
dantuck, I was unable to downgrade too, but I've found a way to fix this on my Arch Linux.
I deleted ~/.config/sublime-text-3/Packages/User/MavensMate/mm/libreadline.so.6

Could you tell me, does this solve your problem too, please?

**Comment by booms8** [comment]
Had the same issue; can confirm removing libreadline fixed it for me as well.
