### ISSUE TITLE
Unstable plugin_host on Windows

### ISSUE THREAD

**Issue by dkurylo** [joeferraro/MavensMate-SublimeText#524]
This happens 0 to 5 times a day when developing. Sometimes no problems for a whole day, sometimes it is popping as a popcorn.
While saving the file to the server, there is a possibility of plugin_host to stop working. Sometimes it is enough to perform a click on some place of code. Sometimes it is when you're coding, while some other file is being saved. The problem appears more frequently when there are several files in the save queue, or when several projects are opened in separate ST3 windows. After that error all MM functionality is stopped, and it is required to close ST3 with all its windows opened, and open it again to reload MM.
This is not a problem of a current release, this has happened for half of a year at least with different MM releases. Also, no problems on Lunix platform were found - this is just a Windows issue.
![screenshot 2014-12-04 11 22 04](https://cloud.githubusercontent.com/assets/5858499/5296129/33538cd2-7ba9-11e4-9f27-43e6c0d628d2.png)

**Comment by devosmaarten** [comment]
Hello, Do you have any comment on this? I'm expierencing the same thing for the moment, the different is that I try to connect to Salesforce Through python...

**Comment by dkurylo** [comment]
No, I was not able to locate or fix the problem. Still experiencing the issue several times a day. Luckily, it vanishes after closing all ST windows and re-opening them. Untill the next time it fails.

**Comment by ralphcallaway** [comment]
is this still going on? this sounds like a real pain

my understanding is plugin_host is the python api that handles web requests and other plugin coordination from plugin (i could be way off honestly), perhaps you might take a look at making sure you're on the latest ST 3 version?

if this keeps happening you might consider doing a custom install of the mm core api via pip, or via source, python has often been at the root of a lot of these sort of issues, see http://mavensmate.com/Getting_Started/Users and http://mavensmate.com/Getting_Started/Developers

closing for now, please re-open if this is still ocurring, or you have additional diagnostic info
