### ISSUE TITLE
Files opened from "Find Results" dialog don't save to server

### ISSUE THREAD

**Issue by daveespo** [joeferraro/MavensMate-SublimeText#530]
I'm mystified. I can't figure out why sometimes when I save a VF Page or Component, it doesn't trigger the server side save. Additionally, the 'Compile Active File' is grayed out. I have to do the Force Save to get it to go up

http://screencast.com/t/drpdW2GmNk

What controls whether the file saves to the server or not? I can't seem to spot the cause

Thanks

**Comment by daveespo** [comment]
Ok, I figure out the repro case -- It has to do with the is_mm_file() method in util.py

When you open a file using the project tree on the left, it opens with a lower case "c:\users\esposito". Example: 

http://screencast.com/t/dDGHPp3Dafu

But if I do a "Find in files" search and click on the file, it opens it with "C:\Users\esposito"

http://screencast.com/t/pzDhw1fm

and

http://screencast.com/t/n4UYgDnVsER

This causes the case-sensitive test on line 261 of util.php to return false

            if os.path.exists(filename) and os.path.join(project_directory,"src") in filename:

And of course, the root cause is that my mm_workspace was lowercase:

	"mm_workspace" : "C:\\Users\\esposito\\Documents\\....",

I tried to patch this -- I tried using os.path.abspath and os.path.normpath hoping that it would normalize the case but it doesn't seem to change the case of the string

@joeferraro, I guess I'm out of easy ideas here so if you don't have anything for me to try, I guess this just needs to go into the pile of 'Windows sucks'

**Comment by ralphcallaway** [comment]
@daveespo i've noticed this is an area things have trouble, typically with whether menu options are visibled/enabled in various cases, it's astonishing how many permutations there are to consider 

thanks for the great diagnostic info, feel free to submit a pull request to mm if you want to try patching it
