### ISSUE TITLE
MavensMate compile problem

### ISSUE THREAD

**Issue by dcarr178** [joeferraro/MavensMate-SublimeText#535]
I have been using Sublime Text 3 and MavensMate for a while now without problem. But starting yesterday everything has gone heywire and I’m not sure what’s happening. Hopefully you have dealt with something similar before and can give me some pointers.

The problem is when I edit a class or page file in MM and save it, the console compiles the file on the server and says the compile was successful. However, when you actually pull up the class/page in the Salesforce instance directly, the file hasn’t changed at all. And then I insert an intentional code error that would normally cause a compile error but MM compiles the file and says successful.

I tried rebooting my computer to bounce the MM application and then I deleted my project and started over with a brand new MM project and it’s still happening. For now all I can do is write my code locally, then copy and paste into my browser and compile there. It’s horrible.

**Comment by ralphcallaway** [comment]
@dcarr178 i've run into a similar issue before and it ended up that mavensmate just wasn't reporting a failed compilation

you might try doing the same change in the dev console and see if you get a compile error

in order for us to look deeper, please enable plugin logging, and post the results http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging

**Comment by ralphcallaway** [comment]
closing for now, please re-open if you're still experience and can provide diagnostic info
