### ISSUE TITLE
Unable to create a new project

### ISSUE THREAD

**Issue by ursatish** [joeferraro/MavensMate-SublimeText#536]
I am unable to create a new project. I followed the steps as per the documentation but on creating a new project, I get the following error:

DPI scale: 1
startup, version: 3065 linux x32 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/satish/.config/sublime-text-3/Packages
state path: /home/satish/.config/sublime-text-3/Local
hardware concurrency: 4
zip path: /opt/sublime_text/Packages
zip path: /home/satish/.config/sublime-text-3/Installed Packages
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 173 cache hits: 173
pre session restore time: 0.443713
using gamma: 1 (err: 0)
startup time: 0.781631
first paint time: 0.789766
launching: /opt/sublime_text/plugin_host
loaded 837 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
reloading plugin MavensMate.config
reloading plugin MavensMate.mavensmate
reloading plugin MavensMate.util
plugins loaded
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: /home/satish/.config/sublime-text-3/Packages/User/MavensMate/mm/mm --ui -o new_project -c SUBLIME_TEXT_3
[MAVENSMATE]: {}
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/satish/.config/sublime-text-3/Packages/MavensMate/lib/mm_interface.py", line 327, in run
    response_body = '\n'.join(mm_response)
TypeError: sequence item 0: expected str instance, bytes found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/home/satish/.config/sublime-text-3/Packages/MavensMate/lib/mm_interface.py", line 331, in run
    strs.append(line.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 139: invalid start byte

Package Control: No updated packages

FYI: The OS is ubuntu 14.04

The user settings under mavensmate are as follows:

MavensMate settings
NOTE: MavensMate user settings will override MavensMate default settings
To override default MavensMate settings, modify user-specific settings (MavensMate --> Settings --> User) 
** Most changes require a SublimeText restart **
*/

{
	//set to absolute location where you wish your MavensMate project to reside
	//if the location does not exist, MavensMate will attempt to create it
	//for example: "/Users/username/Documents/workspaces/mavensmate" (notice the absolute path)
	//WINDOWS USERS: it's probably best to set this like so: C:\\path\\to\\your\\workspace
	//****NEW****: you can now set mm_workspace to an array of locations on your file system
	//EXAMPLE:
	// "mm_workspace" : [
	// 		"/my/workspace",
	// 		"/my/other/workspace",
	// 		"/my/super/secret/workspace"
	// ]
	"mm_workspace" : ["/home/satish/Sublimetext/workspace"],

	//set if you're behind a proxy (you can also set via export HTTP_PROXY, export HTTPS_PROXY)
	//----IMPORTANT: you MUST escape the 2 slashes after http: and https: as shown below (dont ask, it's a dumb JSON-with-comments parsing issue)
	//examples: 
	// 	"mm_http_proxy"  : "http:\/\/10.10.1.10:3128",
	// 	"mm_https_proxy" : "http:\/\/10.10.1.10:1080"
	//
	// HTTP Basic Auth
	// 	"mm_http_proxy"  : "http:\/\/user:pass@10.10.1.10:3128/",
	// 	"mm_https_proxy" : "http:\/\/user:pass@10.10.1.10:1080/"

	"mm_http_proxy" : "",

	"mm_https_proxy" : "",

	//set to desired Salesforce.com API version (tooling api functionality requires 27.0+)
	"mm_api_version" : "31.0",

	//generate from https://mavensmate.herokuapp.com. used to capture high-level usage statistics for community functionality like collaboration, gamification
	"mm_community_api_token" : "",

	//if true, MavensMate will automatically hide the debug panel upon a successful operation
	"mm_hide_panel_on_success" : true,

	//the amount of time (in seconds) before MavensMate hides the debug panel upon a successful operation
	"mm_hide_panel_time" : 0,

	//if true, MavensMate will capture the save file operation and compile to the Salesforce.com server automatically 
	"mm_compile_on_save" : true,

	//if false, mavensmate will store/retrieve sensitive data like passwords in a less secure way
	//set to false only if having issues specifically with keyring or gnome-keyring
	"mm_use_keyring" : true,

	//if true, MavensMate will check for server conflicts and present a server diff when it finds a conflict
	"mm_compile_check_conflicts": true,

	//if true, MavensMate will present local/server diff view when conflict is found for the purposes of merging changes (beta)
	"mm_diff_server_conflicts": true,

	//if true, MavensMate will scroll to the line of a reported exception when there is a compilation error
	"mm_compile_scroll_to_error": true,

	//if true, MavensMate will rollback compiles when an error is encountered
	"mm_compile_rollback_on_error": true,

	//if true, MavensMate will hook into the Sublime Text completions API to offer code assistance
	"mm_autocomplete" : true,

	//if true, MavensMate will check for updates to the mm executable when Sublime Text starts
	"mm_check_for_updates" : true,

	//if true, MavensMate will look for and download pre-releases (beta versions) of the MavensMate API, mm
	"mm_beta_user" : false,

	//if true, MavensMate will automatically install updates to the MavensMate API, mm
	"mm_auto_install_mm_updates" : true,

	//possible values: CRITICAL, ERROR, WARNING, DEBUG, INFO
	"mm_log_level" : "INFO",

	//location where mm debug log should be placed (must be existing path)
	//windows users: please set like so: C:\\path\\to\\your\\logs
	"mm_log_location" : "",

	//if true, mavensmate will send usage statistics (NEVER sensitive information like usernames/passwords/etc) for development, reporting, & debugging purposes (see util.py for source of the call)
	"mm_send_usage_statistics" : true,

	//the path of the mm command line tool
	//"default" means the mm directory is a top-level directory in the package root (MavensMate/mm)
	//if you want MavensMate for Sublime Text to point to a different mm install, please set its path here (some/other/directory/mm)
	"mm_path" : "default",

	//if true, mavensmate will open UIs in default browser
	//linux/windows users: mavensmate UIs are static HTML files, so ensure your browser is set up to open .HTML files by default
	"mm_use_browser_as_ui" : false, 

	//(advanced users only) set to true if you want to use python 2.7 to run mm.py (mm_python_location and mm_py_location must be set)
	"mm_developer_mode" : false,

	//set to location of your python 2.7 install (mm_developer_mode must be set to true)
	"mm_python_location" : "/usr/bin/python",

	//if you wish to run mm via python, you must set this to the location of your mm.py file
	"mm_mm_py_location" : "/path/to/mm.py",

	//linux users: the location of your "subl" executable
	"mm_subl_location" : "/usr/bin/subl",

	//windows users: set to the location of your sublime_text.exe
	"mm_windows_subl_location" : "C:/Program Files/Sublime Text 3/sublime_text.exe",

	//specify a path for custom wsdl files here. wsdls must be named: apex.xml, partner.xml, metadata.xml, tooling.xml
	"mm_wsdl_path" : "",

	//OSX only: the location of your Sublime Text install
	"mm_plugin_client_location" : "/Applications",

	//OSX only: the name of your plugin client app (Sublime Text.app, Sublime Text 3.app, etc.)
	"mm_osx_plugin_client_app_name" : "Sublime Text 3.app",

	//set to true to use the tooling api to compile apex metadata (if you're experiencing any compile issues, set this to false to use the metadata api)
	"mm_compile_with_tooling_api" : true,

	//set to true if you want a history of your executed apex scripts in project/apex-scripts
	"mm_log_anonymous_apex" : true,

	//set to true to play notification sounds
	"mm_play_sounds" : true,

	//local server port
	"mm_server_port" : 7777,

	//mavensmate will attempt to compile when savings files with the following extensions
	"mm_apex_file_extensions": [
		".page",
		".component",
		".cls",
		".object",
		".trigger",
		".layout",
		".resource",
		".remoteSite",
		".labels", 
		".app",
		".dashboard",
		".permissionset",
		".workflow",
		".email",
		".profile",
		".scf",
		".queue",
		".reportType",
		".report",
		".weblink",
		".tab",
		".letter",
		".role",
		".homePageComponent",
		".homePageLayout",
		".objectTranslation",
		".flow",
		".datacategorygroup",
		".snapshot",
		".site",
		".sharingRules",
		".settings",
		".callCenter",
		".community",
		".authProvider",
		".customApplicationComponent",
		".quickAction",
		".approvalProcess",
		".html",
		".apxc",
		".apxt"
	],

	//template location, e.g. "remote" or "local" ("remote" refers to templates located on github)
	"mm_template_location": "remote",

	//template location 
	//if "mm_template_location" is set to "local", set to absolute location of the directory where you've forked the MavensMate-Templates project
		//example: "mm_template_source" : "/path/to/templates"
	//if "mm_template_location" is set to "remote", set to github location)
		//example: "mm_template_source" : "username/reponame/branchname"
	//project directory/repository must be in the format found here: https://github.com/joeferraro/MavensMate-Templates
	"mm_template_source": "joeferraro/MavensMate-Templates/master",
	
	//the default metadata available in a project (may be set on a per-project basis in the "advanced" tab of the new and edit project UIs)
	"mm_default_subscription" : [
		"ApexClass",
		"ApexComponent",
		"ApexPage",
		"ApexTrigger",
		"StaticResource",
		"CustomObject",
		"Profile"
	],

	//ignore metadata from managed packages (highly recommended)
	"mm_ignore_managed_metadata" : true,

	//the number of the most recent apex debug logs to download during the "fetch logs" command
	"mm_number_of_logs_limit" : 10,

	//choices: "metadata" or "apex". "metadata" is recommended, however if your tests are taking forever to run, try switching to "apex"
	//we're working on async testing api support in 0.36
	"mm_test_api" : "metadata",

	//if true, mavensmate will store all deployment packages in your project's "deploy" directory
	"mm_archive_deployments" : true,
	
	//if true, mavensmate will set the purgeOnDelete to true during metadata deletes (a hard delete)
	"mm_purge_on_delete" : false,

	"mm_verbose" : false,

	//set to false if during completions, the size of your .org_metadata file is bogging down the editor during code completion
	"mm_use_org_metadata_for_completions" : true,

	//set to false if index symbol indexing during project creation/upgrade is causing timeouts
	"mm_mass_index_apex_symbols" : false,

	//set to false if you want to use the async apex testing endpoint (beta)
	"mm_use_legacy_test_ui" : true,

	//if true, a log will be generated for every test run during "run all tests" command
	"mm_download_logs_during_run_all_tests" : false,

	//timeout (in seconds) for calls to the Salesforce.com servers
	"mm_timeout" : 10,

	//*BETA* if true, MavensMate will compare the state of the destination org(s) before deployment
	"mm_compare_before_deployment" : true,

	//Advanced users only: if true, MavensMate will not check if your project was created using an older version of MavensMate
	"mm_skip_legacy_check" : false
}

**Comment by farooq-knr** [comment]
Please resolve the above case i am also having same problem

Thanks & Regards
MD Farooq Ahmed

**Comment by ralphcallaway** [comment]
@farooq-knr @ursatish take a look at #218 (dig farther down for this bug), some other users have reported this problem and have steps to fix it

we thought this got fixed earlier but looks like it's still happening

**Comment by ralphcallaway** [comment]
setup a test box with ubuntu 14.04 LTS and python 2.7.6 and not getting this issue

@farooq-knr and @ursatish  past users have reported success with manual installation of the python core, please give that a try

closing for now, please re-open if you're unable to get things working with a custom python install, if that happens it will help to have some more details about your python version and whether you're on 32 or 64 bit systems (this seems to not occur with 64 bit systems)

**Comment by munis** [comment]
@farooq-knr  @farooq-knr  Were you able to resolve this issue. I am having the same problem and I am running it on Kubuntu 14.04 . @ralphcallaway Can you advise as well ? I tried to see the other issue, didn't help I have Python 2.7.6 installed on my system.

**Comment by amolsable007** [comment]
I am getting following error.

Whoops, unable to parse the response. Please enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging) and post relevant log(s) to a new issue at https://github.com/joeferraro/MavensMate-SublimeText
[RESPONSE FROM MAVENSMATE]: /usr/bin/python: can't open file '/path/to/mm.py': [Errno 2] No such file or directory

I am using 32 bit ubuntu 12.04 and sublime text 3.

**Comment by pgANESUNI** [comment]
Hello
I am new to Sales force and started instaaling sublime text editor and mavens mate in windows 10.When i choose create project,the project creation html page is opening in chrome .i gave the details like project name ,userid and password it is giving the following exception
Pls help me on this

ERROR:suds.client: gpavang@gmail.com KIDdTvH7vN1lJXhd4KQD5wrM {"body": "Server raised fault: 'INVALID_LOGIN: Invalid username, password, security token; or user locked out.'", "stack_trace": "Traceback (most recent call last):\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request\", line 93, in execute\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.commands.project\", line 39, in execute\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.project\", line 112, in retrieve_and_write_to_disk\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sfdc_client\", line 96, in init\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sfdc_client\", line 110, in login\nWebFault: Server raised fault: 'INVALID_LOGIN: Invalid username, password, security token; or user locked out.'\n", "success": false}
