### ISSUE TITLE
unable to create new project in mavenmate

### ISSUE THREAD

**Issue by mayuri24** [joeferraro/MavensMate-SublimeText#537]
when i click on new project
"Your [mm_workspace] setting is not configured properly. Please ensure any locations specified in mm_workspace exist on the system, then try your operation again." this error is generate.
How to configure mm_workspace?

**Comment by gazazello** [comment]
Hi! I hope you figured out this one. But just in case you can click on "MavensMate" button on Sublime's main menu (the rightmost button). From dropdown menu choose "Settings" -> "User". There one of the setting line's is (or should be):
"mm_workspace" : "full_path_to_your_workspace_directory"
Workspace is a directory, where all your project directories will be stored.
Hopefully this helps
thanks!

**Comment by joeferraro** [comment]
thanks @gazazello
