### ISSUE TITLE
Sublime Text 3: "GoTo Symbol" not seeing SF metadata

### ISSUE THREAD

**Issue by deckblad** [joeferraro/MavensMate-SublimeText#538]
ST3 ver 3065
MM ver 4.0.2
Windows 7

I'm not seeing any references when I try the Goto Symbol action in Sublime Text. I've tried clearing out my user's \AppData\Local\Sublime Text 3\Index. I've deleted and re-created the project. I've updated the project metadata index. I've refreshed Apex symbols.

What are common causes of this issue? What additional information might you want to see?

Thanks.

**Comment by joeferraro** [comment]
What file types are you referring to?

**Comment by deckblad** [comment]
I'm trying to reference standard Salesforce class files.

**Comment by deckblad** [comment]
Can I provide any additional info? I'd really like to get MM working like it used to. I'm referring to the GoTo: Symbol menu. On windows, it's CTRL+Shift+R. It used to be that I could hit that key combo, type a class name, and sublime would show me a list of declarations that I could then select to open a file with that classname in it.

**Comment by deckblad** [comment]
I've gone as far as removing ST3, deleting all ST3 user folders, re-installed all. I still can't auto-complete or go-to symbols.

**Comment by deckblad** [comment]
I've tried clearing my Index as suggest here. This doesn't help either.
https://www.sublimetext.com/forum/viewtopic.php?f=3&t=14349

**Comment by deckblad** [comment]
Ok, turns out I had to set Sublime's syntax highlighting to Java for .cls extensions.

View -> Syntax -> Open All With Current Extension As -> Java -> Java

**Comment by deckblad** [comment]
I guess it's simple enough to realize that Sublime wouldn't know what symbols to look for it it didn't recognize the file type. Thing is, it was already syntax highlighting before I changed this setting. So, it wasn't quite apparent to me. Not your fault, Joe.
