### ISSUE TITLE
local variable 'meta_type' referenced before assignment

### ISSUE THREAD

**Issue by GarethKavanagh** [joeferraro/MavensMate-SublimeText#539]
I'm trying to modify the metadata of a report folder, to stop it causing an error on deployment. When I try to modify the file and save it I get the following error:

local variable 'meta_type' referenced before assignment

I had a look at the log and I found this:

[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "/Users/josephferraro/Development/Github/mm/build/mm/out00-PYZ.pyz/mm.commands.metadata", line 387, in execute
UnboundLocalError: local variable 'tmp' referenced before assignment

---------------------
result from command execution
{"body": "local variable 'meta_type' referenced before assignment", "body_type": "text", "success": false}
<type 'str'>
---------------------

---------------------
RESPONDING TO REQUEST
---------------------

{"body": "local variable 'meta_type' referenced before assignment", "body_type": "text", "success": false}

This report folder seems weird to me in any case because there is no corresponding source file for it, but I definitely need to change it so I can get my jenkins build back working any help would be greatly appreciated.

**Comment by ralphcallaway** [comment]
yep, can you give the full name for the report metadata file? seems like we're having issues preparing that to save and reports have nuances in their file structure that can gum things up

short term i'd recommend making this change on the server and then refreshing unless you want to wait on a patch (everyone who helps out with this does it on their own time and has day jobs, so speed is not always available)

you might also try toggling the tooling api on and off and see if that makes a difference (it might not)

**Comment by GarethKavanagh** [comment]
Hi Ralph, I just removed the report from the project and now add reports manually to my managed package. I don't have the details of the problem anymore so you can probably just close this.

**Comment by ralphcallaway** [comment]
@GarethKavanagh i was able to make some progress on this, the compile was failing due to being unable to translate the file to a package.xml for retrieval, there is a patch that keeps this from exploding, but it may mean that your report still isn't retrieved. I expect there is something unsual about the name of the report you were retrieving

leaving this open until we merge the patch, if you remember the name of the report and it's file path that would be helpful, but if not i'm sure it'll pop up again for someone else

**Comment by GarethKavanagh** [comment]
![screen shot 2015-04-27 at 12 34 22](https://cloud.githubusercontent.com/assets/928533/7345924/d3e379e0-ecd9-11e4-9383-140ae1f28784.png)
here you go Ralph, I added the report again, here it is in the folder tree. Is that all you needed? I don't know if this is exactly the way it looked before as it's a good while ago since I looked at it. 

Thanks for your help, it's much appreciated.

**Comment by ralphcallaway** [comment]
@GarethKavanagh yep, that's what i was looking for, the code is parsing the filenmae /project/src/reports/Gordon_Games_Reports/My_Red_Opportunities.report into a suitable package.xml file for the refresh, so this helps me know what file path it's not properly parsing
