### ISSUE TITLE
Toggle among multiple environments in one MM-ST project

### ISSUE THREAD

**Issue by boxfoot** [joeferraro/MavensMate-SublimeText#541]
Like @ralphcallaway  (as discussed in #319), I end up having to switch among SF environments a lot.  My current work-around is keeping several copies of my repository around, so I can have separate MM-ST projects for each environment.

Would be great if we could store multiple credentials on one project, and have a UI for toggling among which one is active.

**Comment by ralphcallaway** [comment]
would definitely second this, hot swapping between environments without re-entering credentials would be ideal

it's a bit rarer, but on occasion i'll have repos with the same credentials, perhaps credentials could be stored outside the project and the same username could then be re-used across multiple projects
