### ISSUE TITLE
Can we exclude pieces of metadata because of deploy problems?

### ISSUE THREAD

**Issue by lewafa** [joeferraro/MavensMate-SublimeText#543]
Salesforce - Whenever we deploy from Staging to Production, few items (like below) in the metadata always error out.

Custom Object --> Idea, SocialPersona
Layout --> FeedItem, SocialPersona and SocialPost.
Email Template --> Unfiled#public.

**Comment by defabien** [comment]
Yeah, It would be great if you could exclude certain pieces of metadata, like the Account object, but not other objects. Perhaps this is already possible?

At the moment, when we deploy, some objects give problems from sandbox to production, so you have to manually uncheck them each time you deploy. Nothing big, but would be a nice time saver.

**Comment by joeferraro** [comment]
I'm a bit confused by this issue. If you do not want to deploy those items, don't select them during the deploy process. Am I misunderstanding the problem? If you have a specific deployment you'd like to perform repeatedly, name the deployment and you will be able to select that deployment in the metadata tab for future deployments.

**Comment by defabien** [comment]
Deselecting them repeatedly takes time, as you said. It's not that much time, but it adds up. Especially when you have very short release cycles and when you are doing hotfixes. Sometimes you also make mistakes, forget that "Idea" causes problems on deployment, and you are greeted with an error screen after +-3 mins.

Naming the deployment is also not a good solution as you often have to refresh the metadata (when you created new objects, layouts, ... in the UI) and then the old deployment becomes outdated. (unless I'm missing something)

So a negative filter on specific metadata that is causing problems on deployment would be a big timesaver for me.

**Comment by ralphcallaway** [comment]
@defabien interesting stuff, have you taken a look at ant? i use it a lot for deployment stuff since it's very flexible and there are tons of articles out there to tweak it

i do like the idea of being able to exclude metadata from the deployment on a project or global basis, but honestly i don't use the plugin for deployment since i love ant so much

**Comment by defabien** [comment]
I now use the tooling API directly for some things here and there, in
conjunction with mm, st3, grunt and git it is quite powerful!

I'll have to check ANT and see if I can automate some more stuff. Thanks
for the tip!


www.sparklink.be + fabien@sparklink.be + 32 496 39 76 04
Ankerrui 9 + 2000 Antwerpen + België



2015-04-18 19:16 GMT+02:00 Ralph Callaway <notifications@github.com>:
