### ISSUE TITLE
Unable to  parse resonse error  for Generate apex test coverage report

### ISSUE THREAD

**Issue by sabbella** [joeferraro/MavensMate-SublimeText#544]
hi joe,

When I generate the apex test coverage report from sandbox org, I have no issues but when
I generate test coverage report from production. It is giving this wierd error.

"Whoops, unable to parse the response. Please enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging) and post relevant log(s) to a new issue at https://github.com/joeferraro/MavensMate-SublimeText"

I am getting response in the json format but not the usual editor window where get the class and related coverage details.

Any help is much appreciated.

Thanks,
Venkata

**Comment by ralphcallaway** [comment]
@venkata 

usually this is salesforce doing something slightly funky in their response (they're determined to avoid consistency in my mind), and the error message is correct in that we can't parse something

per the error instructions, you'll need to enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging) and post relevant log(s)

closing for now, re-open if you can add some log files

**Comment by DavidCDean** [comment]
It does this consistently for me too. It spits out the 15k+ lines of json (cannot be posted here), but that's it.
