### ISSUE TITLE
Project Settings not overriding User settings 

### ISSUE THREAD

**Issue by Starz26** [joeferraro/MavensMate-SublimeText#546]
Have the Mac version

In user settings I have:

	//ignore metadata from managed packages (highly recommended)
	"mm_ignore_managed_metadata" : true,

in Project Settings I Have

	//ignore metadata from managed packages (highly recommended)
	"mm_ignore_managed_metadata" : false,

When editing the project or attempting to deploy a project and looking at the Metadata (after clicking refresh) there is nothing listed under Apex Classes

if I change the USER setting to be false then the classes show up.

Since this is a Patch org all the classes are namespaced and thus do not appear when the setting is set to true. Obviously I do not want the user default to be set to false, I only want this to be set to false for the project.

I have confirmed that if I set the user to false then the classes show up and if I sent it to true then they do not regardless of the setting of the project settings.

**Comment by Starz26** [comment]
Any help here?

**Comment by ralphcallaway** [comment]
i have seen similar issues before and not having time to dig into this further atm, it's probably a bug with how settings are getting pulled

@Starz26, it's a pretty small group of people who maintain this and it's all on the their spare time, so it's hard to say when someone is going to look at this. we do accept pull requests and other community contributions

**Comment by Starz26** [comment]
@ralphcallaway - Thanks, just looking for confirmation that it is a bug and not something that I am doing wrong...... If I find the time I might look into it as well....

**Comment by ralphcallaway** [comment]
@Starz26 it's a bug, will keep it open so we remember to get it fixed

**Comment by chunwu** [comment]
"mm_api_version" is also a victim. This bug has affected us a lot as we are migrating several projects from Force.com eclipse to MavensMate but they have all different api versions. Refreshing project metadata on the the "Edit Project" UI does not respect the mm_api_version in project level setting. It uses the user level setting instead. This can be confirmed by checking the config/.session file after the index refreshing.
