### ISSUE TITLE
Mavensmate v4.0.2 update to v4.0.3 problem

### ISSUE THREAD

**Issue by Hrastopow** [joeferraro/MavensMate-SublimeText#550]
Hello,

I am having problems updating to v4.0.3. According to your documentation the plugin shoud update itself via the package control system, which i have installed, but it doesnt. If I open MavensMate console or the "about" page from menu bar, it shows that I still have v4.0.2 installed. I also tried deleting all mavensmate folders and files, and manually copying the github repo folder into Sublime's packages folder but the problem remains. Is this only a "visual" error and the plugin itself is in fact updated, or are there any other problems?

Thank you for your help, with this great plugin!

Miha

**Comment by ralphcallaway** [comment]
@Hrastopow just release v4.0.4-prerelease and noticed that the about page still says v4.0.2

if you browse to the packages folder (super-shift-p, type browse packages), and go into the mavens mate folder, you can open a file called messages.txt, if it lists 4.0.3 in there you're on 4.0.3

let us know which it is, since either way we need to update the about text code, or fix the upgrade issue

**Comment by ralphcallaway** [comment]
as a workaround, you can also remove the mavensmate package and then reinstall and you'll be able to get the latest version

**Comment by ralphcallaway** [comment]
turns out we didn't update the text that drives the version number for 4.0.3, so that's a known issue, but do double check that there wasn't an upgrade issue :)

**Comment by Hrastopow** [comment]
Hi, I checked the messages.json and it lists 4.0.3 :) Here's the copy-paste.. 

> {
> 	"install": "messages/install.txt",
> 	"4.0.2": "messages/4.0.2.txt",
> 	"4.0.3": "messages/4.0.3.txt"
> }

So the 4.0.4 will fix it I guess? :) Thank you for your help.

**Comment by steals** [comment]
Just added:
"install_prereleases":
	[
		"MavensMate"
	],
into User settings of Package control and restarted Sublime. After restart Mavensmate was updated to 4.0.4 but in "About" window it still says 4.0.2

**Comment by ralphcallaway** [comment]
@steals just noticed that, just pushed v4.0.4-prerelease.2 (will take a while to hit package control) which fixes the about window (still will be in issue in v4.0.3)

fyi, another user pointed out you can look at <sublime_package_folder>/MavensMate/package-metadata.json and see the version based on package control (so doesn't suffer from the issue of forgetful developers not updating our own version config file)
