### ISSUE TITLE
Errors when attempting to connect MM to SFDC project fork

### ISSUE THREAD

**Issue by rbarton24** [joeferraro/MavensMate-SublimeText#554]
When cloning an SFDC Fork locally, I am having trouble connecting MM.  I have tried several different folder configurations and I get a different error each time.  I am on Windows 7 and have recently updated MM.  I am following the documentation by dragging the sfdc-uat-fork file to Sublime, right-clicking and selecting MavensMate>Create MavensMate Project...

Workspace: C:/sfdc-uat-fork
src file: C:/sfdc-uat-fork/sfdc-uat-fork/src
Project Name: sfdc-uat-fork
Error: "A project with this name already exists in your workspace

Workspace: C:/sfdc-uat-fork
src file: C:/sfdc-uat-fork/TempFolder/src
Project Name: sfdc-uat-fork
Error: "Destination path 'C:/sfdc-uat-fork\TempFolder' already exists"

Workspace: C:/sfdc-uat-fork
src file: C:/sfdc-uat-fork/src
Project Name: sfdc-uat-fork
Error: "Could not find "src" directory in project root"

Moved src file and workspace to home directory where I have existing projects connected at C:/Users/rbarton/sfdc-uat & C:/Users/rbarton/sfdc-randy:
Workspace:C:/Users/rbarton/sfdc-uat-fork
src file: C:/Users/rbarton/sfdc-uat-fork/src
Project Name: sfdc-uat-fork
Error: "[Error 5] Access is denied"

Moved back to C:/:
Workspace: C:/sfdc-uat-fork
src file: C:/sfdc-uat-fork/sfdc-uat-fork/src
Project Name: sfdc-uat-fork
Error: [Errno 2] No such file or directory: u'C:/sfdc-uat-fork\\sfdc-uat-fork\\sfdc-uat-fork.sublime-project'

Is there a better workflow to accomplish the following with MM?
Each developer develops in their own sandbox and upon code completion, submits a pull request to the main UAT sandbox.  Also, each developer is able to pull updates made to UAT sandbox.  We are currently trying to accomplish this by having a master UAT repository and a forked repository for each developer sandbox, but unable to connect MM to the forked repositories.

**Comment by ralphcallaway** [comment]
@rbarton24 felt the same way when i first got started with mm, a bit confused, but yes there is a workflow

- clone down into any folder but your workspace 
- open in ST3 
- right click root folder (parent of /src folder)
- create mavens mate project

when that happens, mavens mate will move it over to your workspace and create the config

however, if there is already a folder with the same name in your workspace it'll error, so if you have trouble with this, you'll want to check your workspace and remove that folder
