### ISSUE TITLE
Unable to create a new project in Mavensmate Windows

### ISSUE THREAD

**Issue by arunbnair85** [joeferraro/MavensMate-SublimeText#557]
I have installed Mavensmate in my Mac and windows successfully. But while create a new project in windows,its opening up a page in my Internet Explorer .I have entered my details and clicked on "New project" but nothing is happening.However I was able to create a project in my Mac machine where its opening up a nice UI to enter the details with respect to the browser in Windows. Is there any way I can get the same options in Windows as well ?

**Comment by ralphcallaway** [comment]
@arunbnair85 try setting `mm_use_browser_as_ui` to false (although I'd expect it was already false since that's the default)

if you're still having difficulty please enable plugin logging http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging and post some the log details

**Comment by arunbnair85** [comment]
@ralphcallaway Thanks for your suggestions. As you expected mm_use_browser_as_ui settings is already set to false.
I have changed by default browser to chrome and now I am able to create new project. However its still opening chrome browser page instead mavensmate UI to create a new project.

Thanks 
Arun Nair

**Comment by joeferraro** [comment]
You'll need to change your system .html file association to Chrome, it's not enough to set the default browser.

**Comment by KaushikRay** [comment]
Hello I am facing the same error. And not working even with Chrome.

- tried installing sublime and mavenmate
- both on latest version
- Tried Chrome / FF

This is the debug I got - 

~~~
--------------------------------------------
---------- NEW OPERATION REQUESTED ---------
--------------------------------------------

new_project
Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='new_project', quiet=False, respond_with_html=False, ui_switch=True, uid=None, verbose=False)
{'operation': 'new_project', 'args': Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='new_project', quiet=False, respond_with_html=False, ui_switch=True, uid=None, verbose=False), 'ui': True, 'verbose': False, 'client': 'SUBLIME_TEXT_3'}

--------------------------------------------
UI operation requested, attempting to launch MavensMate UI
---------------------
result from command execution
{'body': 'UI Generated Successfully', 'body_type': 'text', 'success': True, 'time': '1.246000051498413'}
<type 'dict'>
---------------------


---------------------
RESPONDING TO REQUEST
---------------------


{
    "body": "UI Generated Successfully", 
    "body_type": "text", 
    "success": true, 
    "time": "1.246000051498413"
}
~~~

**Comment by KaushikRay** [comment]
I just noticed that this is a little different bug. I will log a new bug.

**Comment by ralphcallaway** [comment]
@arunbnair85 to answer you're original question, the "UI" on mac is just a light weight browser, which is not currently available on windows

you can take your pick of which browsers open the file as previously mentioned by managing what browser opens .html files

in terms of the project not being created, you'll want to open up the developer console for whichever browser you're using and see if there are any javascript errors there, that should help figure out why you can't create a new project

for my testing, i noticed that IE was complaining about active x controls and i had to go through a security warning on win 8 before it would work, the same thing doesn't appear to be an issue on another win 7 machine with chrome

closing this out, re-open if you're still having issues or have further diagnostic info

**Comment by prasanthabr** [comment]
I seem to have similar issues as @arunbnair85. I have changed the default browser to chrome and dont really see any errors per se. In fact, the status on sublime says that operation is successful and nothing else happens. Would it matter that i am using a portable version of sublime? I have updated the sublime exe location on mm based on a previous error

**Comment by joeferraro** [comment]
You'll need to change your system .html file association to Chrome, it's not enough to set the default browser.

**Comment by Petegarner** [comment]
Hi, I am having a similar issue. Can someone walk me through the steps to make Chrome the default browser, and change the system .html file association to Chrome?  I looked in the User and Default settings in MavensMate, but cannot find where to make the change.  Thanks in advance!

**Comment by SVSathwick** [comment]
@joeferraro, how can I change the .html file association. Can you please let me know the steps.

**Comment by ajaylanki** [comment]
If someone still has issue with defaulting Chrome as browser for Mavensmate. Please follow the below steps. I personally tried on my Windows 7 and it worked.

1. Go to Control Panel
2. Click Programs
3. Click Default Programs
4. Click Set Default Programs
5. Select Google Chrome on the left side
6. Click Choose default for this program.
7. Under the Extensions, select .htm, .html etc.

![image](https://cloud.githubusercontent.com/assets/861406/14048088/6f3dbc44-f282-11e5-8401-1d2d331f5bb4.png)
