### ISSUE TITLE
local variable 'meta_type' referenced before assignment

### ISSUE THREAD

**Issue by debdeepmazumder** [joeferraro/MavensMate-SublimeText#559]
Hi,

I am getting this error when I 'Refresh from server' package.xml. Below is data from log file. I am clearing out my credentials.

------------------------------------------------Log-------------------------------------------------------------------------

--------------------------------------------
---------- NEW OPERATION REQUESTED ---------
--------------------------------------------

refresh
Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='refresh', quiet=False, respond_with_html=False, ui_switch=False, uid=None, verbose=False)
{u'files': [u'C:\\Debdeep\\Development\\WES_Phase2\\src\\package.xml'], u'project_name': u'WES_Phase2', 'verbose': False, 'args': Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='refresh', quiet=False, respond_with_html=False, ui_switch=False, uid=None, verbose=False), 'client': 'SUBLIME_TEXT_3', 'ui': False, u'workspace': u'C:\\Debdeep\\Development', 'operation': 'refresh'}

--------------------------------------------

sandbox
endpont is ::: 
https://test.salesforce.com/services/Soap/u/31.0
GETTING USER INFO
(GetUserInfoResult){
   accessibilityMode = False
   currencySymbol = None
   orgAttachmentFileSizeLimit = 115343360
   orgDefaultCurrencyIsoCode = None
   orgDisallowHtmlAttachments = False
   orgHasPersonAccounts = False
   organizationId = "00De0000005Us23EAC"
   organizationMultiCurrency = True
   organizationName = "XXXXXXXXX"
   profileId = "00e40000000qxADAAY"
   roleId = None
   sessionSecondsValid = 7200
   userDefaultCurrencyIsoCode = "USD"
   userEmail = "<cleared email id>"
   userFullName = "Debdeep Mazumdar"
   userId = "005e0000002MSzFAAW"
   userLanguage = "en_US"
   userLocale = "en_US"
   userName = "<cleared user name>"
   userTimeZone = "America/New_York"
   userType = "Standard"
   userUiSkin = "Theme3"
 }
---------------------
result from command execution
local variable 'meta_type' referenced before assignment
<type 'exceptions.UnboundLocalError'>
local variable 'meta_type' referenced before assignment
---------------------

---------------------
RESPONDING TO REQUEST
---------------------

{"body": "local variable 'meta_type' referenced before assignment", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 93, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.metadata\", line 173, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project\", line 475, in get_retrieve_result\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.util\", line 1156, in get_metadata_hash\nUnboundLocalError: local variable 'meta_type' referenced before assignment\n", "success": false}

------------------------------------------------End of Log-----------------------------------------------------------------

**Comment by ralphcallaway** [comment]
@debdeepmazumder you're trying to refresh you're package.xml, which isn't refreshable, so it's errorring

you can use the refresh command on any folders that are part of the project, and any salesforce files that come from salesforce, i.e. apex classes
