### ISSUE TITLE
Path errors after rebuilding computer and restoring project files

### ISSUE THREAD

**Issue by dmcheng** [joeferraro/MavensMate-SublimeText#560]
Hello.  I had to rebuild my Mac and I accidentally used a different username when reinstalling (davidcheng instead of dcheng).  After I restored all files, in my project folder I edited the sublime.workspace file to change the paths, but when I open a project in Sublime and go to MavensMate > Edit Project, the MavensMate server window does not appear.

Also, when I try to refresh any file from the Salesforce server, I get an error "Could not find project in workspace: /Users/dcheng/Documents/Mavensmate", so it's still referencing the old path.

Is the path tracked in another file that I have to edit?

Thanks
David

**Comment by ralphcallaway** [comment]
wouldn't think it would affect existing projects, but the workspace is set in the mavens mate settings right at the top `mm_workspace`, you can edit that setting there
