### ISSUE TITLE
Not able to refresh project from Salesforce

### ISSUE THREAD

**Issue by apexforcedev** [joeferraro/MavensMate-SublimeText#561]
Can't save files, etc but just trying to get my code updated with what is on the server. Just started happening today on a consistent basis. Has happened in the past, but usually clears itself up and I am able to work, not the case today 04/15/2015.

Thank you, please respond back to apexforcedev@gmail.com
Dave Galligher

--------------------------------------------
---------- NEW OPERATION REQUESTED ---------
--------------------------------------------

refresh
Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='refresh', quiet=False, respond_with_html=False, ui_switch=False, uid=None, verbose=False)
{u'project_name': u'pdev2', 'verbose': False, u'directories': [u'C:\\Projects\\Salesforce\\Pkgs_Unmanaged\\pdev2\\src'], 'args': Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='refresh', quiet=False, respond_with_html=False, ui_switch=False, uid=None, verbose=False), 'client': 'SUBLIME_TEXT_3', 'ui': False, u'workspace': u'C:/Projects/Salesforce/Pkgs_Unmanaged', 'operation': 'refresh'}

--------------------------------------------

GETTING USER INFO
---------------------
result from command execution
<urlopen error _ssl.c:495: The handshake operation timed out>
<class 'urllib2.URLError'>

---------------------

---------------------
RESPONDING TO REQUEST
---------------------

{"body": "<urlopen error _ssl.c:495: The handshake operation timed out>", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 61, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project\", line 75, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client\", line 86, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sforce.base\", line 590, in getUserInfo\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 542, in __call__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 602, in invoke\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 637, in send\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http\", line 77, in send\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http\", line 118, in u2open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 404, in open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 422, in _open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 382, in _call_chain\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 1222, in https_open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 1184, in do_open\nURLError: <urlopen error _ssl.c:495: The handshake operation timed out>\n", "success": false}

**Comment by ralphcallaway** [comment]
@apexforcedev fyi you've got sensitive info in this request, you'll want to scrub credentials when posting logs

**Comment by ralphcallaway** [comment]
@apexforcedev and since the internet never forgets you should probably go ahead and change your password

**Comment by apexforcedev** [comment]
Thanks, got distracted on posting, changing it now.

**Comment by apexforcedev** [comment]
Also removed creds from original posting (but your point is well taken), do you have any idea @ralphcallaway as to what is going on, getting additional issues on just saving a file. Here is the critical data minus the creds and the source code :) Seems to be all related.

--------------------------------------------
---------- NEW OPERATION REQUESTED ---------
--------------------------------------------

compile
Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='compile', quiet=False, respond_with_html=False, ui_switch=False, uid=None, verbose=False)
{u'files': [u'C:\\Projects\\Salesforce\\Pkgs_Unmanaged\\pdev2\\src\\pages\\VP_ProjectList.page'], u'project_name': u'pdev2', 'verbose': False, 'args': Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='compile', quiet=False, respond_with_html=False, ui_switch=False, uid=None, verbose=False), 'client': 'SUBLIME_TEXT_3', 'ui': False, u'workspace': u'C:/Projects/Salesforce/Pkgs_Unmanaged', 'operation': 'compile'}

retrieve request: 
{u'ApexPage': [u'VP_ProjectList']}
----> 
{'name': u'ApexPage', 'members': [u'VP_ProjectList']}
{u'inFolder': False, u'xmlName': u'ApexPage', u'suffix': u'page', u'directoryName': u'pages', u'metaFile': True}
---request payload---
{'apiVersion': '28.0', 'unpackaged': {'types': [{'name': u'ApexPage', 'members': [u'VP_ProjectList']}]}}
result of retrieve: 


(AsyncResult){
   done = False
   id = "09So0000002WEcXEAW"
   state = "Queued"
 }
---> result is not done
waiting for retrieve request ...
Updating existing member

<source code here....>

Starting new HTTPS connection (1): na17.salesforce.com
---------------------
result from command execution
HTTPSConnectionPool(host='na17.salesforce.com', port=443): Max retries exceeded with url: /services/data/v28.0/tooling/sobjects/ApexPageMember (Caused by <class 'socket.error'>: [Errno 10054] An existing connection was forcibly closed by the remote host)
<class 'requests.exceptions.ConnectionError'>
HTTPSConnectionPool(host='na17.salesforce.com', port=443): Max retries exceeded with url: /services/data/v28.0/tooling/sobjects/ApexPageMember (Caused by <class 'socket.error'>: [Errno 10054] An existing connection was forcibly closed by the remote host)
---------------------


---------------------
RESPONDING TO REQUEST
---------------------


HTTPSConnectionPool(host='na17.salesforce.com', port=443): Max retries exceeded with url: /services/data/v28.0/tooling/sobjects/ApexPageMember (Caused by <class 'socket.error'>: [Errno 10054] An existing connection was forcibly closed by the remote host)

**Comment by ralphcallaway** [comment]
looking at the logs it seems like salesforce is slower than usual, and our polling algorithm is being too aggressive and getting throttled

this is the first time i've seen this, so my guess is that this is a recent salesforce change, or they're just unusually slow

short term, this error is specific to the tooling api, if you switch to using the metadata api you should be able to continue working. to do this set `mm_compile_with_tooling_api` to false in your mavensmate user settings

**Comment by apexforcedev** [comment]
I did do a check earlier today on NA17 and they did have issues, but supposedly they fixed them at 05:49 UTC. I'll try your suggestion regarding the tooling api.

**Comment by apexforcedev** [comment]
Setting the tooling api to false did NOT make a difference, getting 'The read operation timed out', here is the log dump:

--------------------------------------------
---------- NEW OPERATION REQUESTED ---------
--------------------------------------------

compile
Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='compile', quiet=False, respond_with_html=False, ui_switch=False, uid=None, verbose=False)
{u'files': [u'C:\\Projects\\Salesforce\\Pkgs_Unmanaged\\pdev2\\src\\classes\\VP_ResourceManager.cls'], u'project_name': u'pdev2', 'verbose': False, 'args': Namespace(client='SUBLIME_TEXT_3', format='json', offline=False, operation='compile', quiet=False, respond_with_html=False, ui_switch=False, uid=None, verbose=False), 'client': 'SUBLIME_TEXT_3', 'ui': False, u'workspace': u'C:/Projects/Salesforce/Pkgs_Unmanaged', 'operation': 'compile'}

--------------------------------------------
retrieve request: 
{u'ApexClass': [u'VP_ResourceManager']}
----> 
{'name': u'ApexClass', 'members': [u'VP_ResourceManager']}
{u'inFolder': False, u'xmlName': u'ApexClass', u'suffix': u'cls', u'directoryName': u'classes', u'metaFile': True}
---request payload---
{'apiVersion': '28.0', 'unpackaged': {'types': [{'name': u'ApexClass', 'members': [u'VP_ResourceManager']}]}}
result of retrieve: 


(AsyncResult){
   done = False
   id = "09So0000002WElUEAW"
   state = "Queued"
 }
---> result is not done
waiting for retrieve request ...
---------------------
result from command execution
The read operation timed out
<class 'ssl.SSLError'>
The read operation timed out
---------------------


---------------------
RESPONDING TO REQUEST
---------------------


{"body": "The read operation timed out", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 93, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.metadata\", line 324, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.local_store\", line 130, in check_for_conflicts\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client\", line 226, in execute_query\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sforce.partner\", line 144, in query\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sforce.base\", line 529, in query\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 542, in __call__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 602, in invoke\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 637, in send\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http\", line 77, in send\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http\", line 118, in u2open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 404, in open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 422, in _open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 382, in _call_chain\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 1222, in https_open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 1187, in do_open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 1067, in getresponse\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 409, in begin\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 365, in _read_status\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\socket\", line 476, in readline\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\ssl\", line 246, in recv\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\ssl\", line 165, in read\nSSLError: The read operation timed out\n", "success": false}

**Comment by ralphcallaway** [comment]
@apexforcedev not much we can do about that, we're kind of expecting salesforce to respond to the requests, that error is saying we tried to check the status of the retrieve and the request timed out before we heard from salesforce, you'll need to keep retrying and monitor trust

you can also try using the dev console although i expect the performance issue that's affecting you will be present there

**Comment by apexforcedev** [comment]
Thanks for the response on this, it started working again. The weird thing was that the timeout did NOT occur in a Mac OS environment, but did fail on a Windows 7. Very strange, as of right now it is working on both....
