### ISSUE TITLE
Result: [OPERATION FAILED]: Whoops, unable to parse the response. Please enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging)

### ISSUE THREAD

**Issue by pawarmangesh** [joeferraro/MavensMate-SublimeText#566]
I did drag the new apex project into ST3 editor and tried to create MavensMate project by right clicking on the project I am facing following error -
Result: [OPERATION FAILED]: Whoops, unable to parse the response. Please enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging)

Referred previous similar issue logged and according to that did change the api version of all files from 31.0 to 30.0.
Also did change "mm_api_version" to 30.0
What to do next? Could you please provide me the solution?

**Comment by ralphcallaway** [comment]
@pawarmangesh please enable plugin logging and post applicable logs

**Comment by pawarmangesh** [comment]
@ralphcallaway Thank you for your quick response.
I did already enabled plugin logging by updating user setting as -
"mm_log_level" : "DEBUG"
"mm_log_location" : "\\path\\to\\my\\logs"

And here is what I can see in log details when I am trying create a new project in sublime using mavensmate -
-------------------------------------------------------------------------------------------
Loading MavensMate for Sublime Text
mm_installer -->
checking for updated mm version
mm is up to date (0.2.4), no further action needed
Calling mm_interface
OPERATION: new_project
{}
mm command: 
"C:\Users\Mangesh\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" --ui -c SUBLIME_TEXT_3 -o new_project
{}
response from mm: Traceback (most recent call last):

  File "<string>", line 6, in <module>

  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module

  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm", line 6, in <module>

  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module

  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 6, in <module>

  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module

  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.config", line 55, in <module>

  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.config", line 38, in __get_base_path

AttributeError: 'module' object has no attribute '_MEIPASS'

**Comment by ralphcallaway** [comment]
@pawarmangesh that doesn't look like a valid path for a windows system, i'd expect something like `C:\\dev\\mmlogs` (the settings file require `\` to be escaped so that we can include comments in json)

the log you posted is actually the sublime text console, which is useful, but the mavensmate log will give more details about the project error. the console appears to be erroring due to the invalid login path ...

**Comment by pawarmangesh** [comment]
@ralphcallaway  Ok.
But could you please help me to set the path for logs? Because I did set path as 
"mm_log_location" : "D:/Mavensmate/RC"
in mavensmate user setting. Still I am facing the same issue while creating new project.
Is it something problem related to my OS (like 32-bit system)?
I have tried each and every solution available on internet but failed.
Am I missing something while installation?
It will be very helpful for me if post some steps to make mavensmate successfully work on my system.
Thank you for your reply.

**Comment by ralphcallaway** [comment]
do you see anything in D:/MavensMate/RC, any log files? If so can you post them? 

when you click new project, does the new project UI load?

**Comment by pawarmangesh** [comment]
@ralphcallaway 
I did set following logging setting -
"mm_log_level" : "DEBUG",
"mm_log_location" : "D:/Mavensmate/RC/mm_logs",
And when I am trying to create new project there were 2 text files got created under mm_logs named-
"mmst" and "mmui".

In mmst text file I am having this  -
-------------------------------------------------------
Loading MavensMate for Sublime Text
mm_installer -->
checking for updated mm version
Calling mm_interface
mm is up to date (0.2.4), no further action needed
OPERATION: new_project
{}
mm command: 
"E:\softwares\E&TC\Sublime Text 3 portable\Data\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 -o new_project --ui
{}
response from mm: Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm", line 6, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 6, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.config", line 55, in <module>
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.config", line 38, in __get_base_path
AttributeError: 'module' object has no attribute '_MEIPASS'

In mmui text file I am having this  -
-------------------------------------------------------

starting local MavensMate UI server

Also when I click on new project the new project UI does not load.

**Comment by ralphcallaway** [comment]
@pawarmangesh it appears that this is related to a low level issue with python, that can probably get patched (but that will take a while)

unfortunately it looks like you'll need to install the core mm api directly to get this working

i'd start with using pip since that's the quickest (see option 3 http://mavensmate.com/Getting_Started/Users)

you can also run with the source code directly (see the steps below "mavens mate sublime text" in the setting up your development environment section of http://mavensmate.com/Getting_Started/Developers)

**Comment by ralphcallaway** [comment]
if you could also provide some details about your OS so we can try and reproduce this issue (seems like recent windows version have the most of these sort of issues)

**Comment by pawarmangesh** [comment]
@ralphcallaway  Sure.
Windows 7 Ultimate (32-bit)

**Comment by pawarmangesh** [comment]
@ralphcallaway  Any luck regarding this issue?

**Comment by ralphcallaway** [comment]
@pawarmangesh no, this one is likely to be around for a while since we can't reproduce it, as far as i can tell something with the python installer that isn't working correctly

have you tried my suggestions for manually installing the mm core api?

**Comment by ralphcallaway** [comment]
pyinstaller issue: https://github.com/pyinstaller/pyinstaller/issues/801 https://github.com/pyinstaller/pyinstaller/pull/1102

**Comment by pawarmangesh** [comment]
@ralphcallaway  Sorry for late reply.
Yup its working for me now. Thank you so much for your precious help.
