### ISSUE TITLE
Apex syntax highlighting on 'global' keyword

### ISSUE THREAD

**Issue by jdcrensh** [joeferraro/MavensMate-SublimeText#568]
It would be nice if the Apex syntax highlighting for class and member keywords also included 'global'. I can add it myself by editing the Apex syntax file that gets created, but it's an annoyance to do so whenever there's an update to the plugin.

**Comment by jdcrensh** [comment]
Worked around this update overwriting issue by copying my customized Apex syntax file into `~/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/sublime/lang`.

**Comment by ralphcallaway** [comment]
@jdcrensh happy to take a look at a pull request if you want to adjust the syntax file in the package, see https://github.com/joeferraro/MavensMate-SublimeText/pull/540 for an example of updates to the syntax highlighting
