### ISSUE TITLE
mm_template_source not pulling templates

### ISSUE THREAD

**Issue by JPipkin** [joeferraro/MavensMate-SublimeText#569]
We have a custom library of apex templates on GitHub and they are not showing up as available options anymore (as of last week). All we see are the standard Mavensmate templates. 

Settings:
"mm_template_location": "remote",
"mm_template_source": "JPipkin/ApexTemplates/master",

Thanks

**Comment by halldor-kaptio** [comment]
Shouldn't the "mm_template_source" only be used if the "mm_template_location" is set to "local" ?

**Comment by ralphcallaway** [comment]
@JPipkin fix should be in place for this in v4.0.5-prerelease, there was a bug in some new functionality

can you turn on pre-releases for mavensmate and let me know if that fixes you're issue? see `install_prereleases` setting for package control in https://packagecontrol.io/docs/settings

**Comment by JPipkin** [comment]
@ralphcallaway That did the trick. Thanks!
