### ISSUE TITLE
Default key mappings

### ISSUE THREAD

**Issue by swervo** [joeferraro/MavensMate-SublimeText#573]
This keymap:

{  "keys": ["super+shift+d"], "command": "compile_tabs" }

clashes with the default sublime keymap for duplicate line (which I use all the time).
I'm aware that I can change this in Sublime (or in the plugin itself - which is what I have done) but wouldn't it be better if this plugin used a different key combination?

I can submit a PR if required - and a suggestion for an alternative is suggested.

**Comment by ralphcallaway** [comment]
totally agreed, i'd overriden this myself to be super+shift+s which is analagous with other "Save All" commands since i love super+shift+d for duplicate line

@joeferraro any attachment to this key binding? @swervo go ahead and submit a PR

**Comment by swervo** [comment]
PR submitted.

**Comment by swervo** [comment]
This issue seems to have comeback somehow but I'm not sure how as the keymapping was changed and has not been changed back.

I'm using Sublime 3083 with v6 of MavensMate. Any ideas?

I'm going to remove the package for now as I'm not using it.

**Comment by ralphcallaway** [comment]
@swervo i know sublime text has some tools for looking at key mappings, they might be helpful for troubleshooting, at the end of the day the user key mappings take precedence, so you should be able to override any strange package behavior you don't like

at least for me `super-shift-d` is duplicating lines as expected ...

**Comment by batjaa** [comment]
Why was this closed? Where do I find the key mappings for MM?

**Comment by ralphcallaway** [comment]
@batjaa you can browse the keybindings for any package you install, the extension is `.sublime-keymap` which you could search for to find it, or browse to the packages folder 

on my machine (mac os x) the path is `/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/MavensMate/sublime/keymaps`, there are different keymap files for different systems

**Comment by ralphcallaway** [comment]
@swervo sounds like you might have updated the keybinding in the mavensmate package directory, that'll work, but sublime overwrites that folder when the package is upgraded, you'll want to update the keybinding in the user packages folder, i did this on my machine 

you probably want something like this in your user keybinding file, it brings back the native duplicate line and changes compile tabs super-shift-s which i like
```
[
    {  "keys": ["super+shift+d"], "command": "duplicate_line" },
    {  "keys": ["super+shift+s"], "command": "compile_tabs"}
]
```

on my machine the user keybinding file is `/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap`

fyi, this is all stuff that's common to all packages, you'll want to dig into the sublime text 3 package develop docs for more

**Comment by swervo** [comment]
Thanks @ralphcallaway I now use VS Code (which is excellent BTW, and also free) so I don't have this problem anymore.
