### ISSUE TITLE
Running Apex Tests no longer working

### ISSUE THREAD

**Issue by pepefloyd** [joeferraro/MavensMate-SublimeText#574]
Since yesterday, after I select the test class I want to run and clicking on "Run Tests" , nothing happens. This is the only information in the log file. There is nothing in the debug logs so I don't think the test is even executed.

Starting new HTTPS connection (1): cs13.salesforce.com

**Comment by ralphcallaway** [comment]
hmm, that's strange, working over here, can you provide
- operating system
- plugin version
- mm api version
- output of sublime text console
- output of mavensmate console

long list i know, but these issues can surface in a bunch of different locations

**Comment by pepefloyd** [comment]
Sure. 

OS: Win 7
Plugin Version: 4.0.5
mm version:  0.2.41
=================================
Operation: Running Apex Test for testDocumentation
Timestamp: Wed, 13 May 2015 16:11:40
   Result: Success
==========================================
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: unit_test
[MAVENSMATE]: {'context': <MavensMate.mavensmate.RunActiveApexTestsCommand object at 0x0000000004609518>, 'params': {'selected': ['testDocumentation']}}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\garcij19\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --ui -o unit_test
[MAVENSMATE]: {"workspace": "C:\\Users\\garcij19\\mavensmate", "project_name": "DEV", "selected": ["testDocumentation"]}
[MAVENSMATE]: response from mm: {
    "body": "UI Generated Successfully", 
    "body_type": "text", 
    "success": true, 
    "time": "2.078000068664551"
}
===========================================

**Comment by pepefloyd** [comment]
I am closing this one as it seems like is caused by a corporate firewall.

**Comment by EricSSH** [comment]
@pepefloyd Did you confirm this was a firewall issue? I am getting the same issue

**Comment by pepefloyd** [comment]
Yep. It was caused by some changes done in our network.

On Tuesday, 15 December 2015, EricSSH <notifications@github.com> wrote:

> @pepefloyd <https://github.com/pepefloyd> Did you confirm this was a
> firewall issue? I am getting the same issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate-SublimeText/issues/574#issuecomment-164914831>
> .
>


-- 
José Garcia Ponce
