### ISSUE TITLE
Duplicate save operations when using non-Single Sublime Layout

### ISSUE THREAD

**Issue by Alexalex1432** [joeferraro/MavensMate-SublimeText#583]
Steps to reproduce:

In sublime menu
View -> Layout -> Rows 2 (or Columns 2, either works)
Open the same .cls file in both areas
Use CTRL+S to save

Two save operations are kicked off, one of them always fails. I searched and couldn't seem to find any previous reports for this.
![bugreport](https://cloud.githubusercontent.com/assets/5090871/7919257/ebca409c-084b-11e5-908f-ba50d7d86100.png)

EDIT: The amount of save operations seems to be tied to the amount of "windows" you have. If I do Rows 3, I have 3 concurrent saves kicked off at the same time.

Using:
Mavensmate for Sublime Text v4.0.5
Sublime Text 3 Stable Build 3083

**Comment by nixil** [comment]
I met the same issue.

**Comment by ralphcallaway** [comment]
i believe the key here is that you have the same file open in multiple tabs, i've run into it a bunch, been wanting to look into this but have gotten good at just ensuring i don't have the same file open in multiple locations
