### ISSUE TITLE
New Project Window not Opens

### ISSUE THREAD

**Issue by karthikkornalies** [joeferraro/MavensMate-SublimeText#589]
Hello Team,

I'm having issue while creating new project. SublimeText/Mavensmate doesn't prompts the browser window to enter credentials.

Sublime text : Build 3083

Mavens Mate for SublimeText : v4.0.5

Operating System : Windows 8

Mavens Console Message while creating new Project.

MAVENSMATE: Calling mm_interface
MAVENSMATE: OPERATION: new_project

MAVENSMATE: mm command: 
MAVENSMATE: "C:\Users\Karthik\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --ui -o new_project

MAVENSMATE: response from mm: {

"body": "UI Generated Successfully", 

"body_type": "text", 

"success": true, 

"time": "1.2960000038146973"
}

MAVENSMATE failed to send community activity

Im not sure what im missing here. Any thoughts would be really appreciated.

Thanks In advance,

Karthik Kornalies

**Comment by ahujaa** [comment]
@karthikkornalies were you able to fix this? I'm having the same issue, not sure what to do

**Comment by karthikkornalies** [comment]
Can you try defaulting your Browser as Internet Explorer, that sorted my issue. For me earlier it was pointing to Chrome. Please let me know if that works for you.

Thanks,
Karthik Kornalies
