### ISSUE TITLE
Links on Create Project do not work

### ISSUE THREAD

**Issue by pbattisson** [joeferraro/MavensMate-SublimeText#600]
Clicking on the 3 links at the bottom of the "New Project" window seems to have no action undertaken.

<img width="759" alt="screen shot 2015-07-14 at 15 32 57" src="https://cloud.githubusercontent.com/assets/795556/8675778/ad3beb78-2a3d-11e5-9d99-8e7e7272a66b.png">

**Comment by joeferraro** [comment]
yeah spoke with @kylethornton about this. this is because you're using MavensMateWindowServer which I'm seriously considering deprecating. The desired experience can be achieved by setting `mm_use_browser_as_ui` to `true` in your user settings (restart required).
