### ISSUE TITLE
Unable to install/update mavensmate api(mm) 

### ISSUE THREAD

**Issue by rajeevdubey007** [joeferraro/MavensMate-SublimeText#606]
Hi,

I am trying to install mavensmate api(mm) but unable to install, I am getting following error:

"could not install mm, please generate/check logs and report GitHub issue"

Please help on this issue

**Comment by joeferraro** [comment]
Please check the Sublime Text console and paste any relevant output

**Comment by rajeevdubey007** [comment]
in console I got following:

[MAVENSMATE]: user mm_path value is default, but mm not installed, forcing install
[MAVENSMATE]: {'html_url': 'https://github.com/joeferraro/mm/releases/tag/v0.2.4', 'id': 543050, 'draft': False, 'name': 'v0.2.4', 'target_commitish': 'master', 'tag_name': 'v0.2.4', 'body': '- Resolves package.xml parsing issue', 'tarball_url': 'https://api.github.com/repos/joeferraro/mm/tarball/v0.2.4', 'upload_url': 'https://uploads.github.com/repos/joeferraro/mm/releases/543050/assets{?name}', 'published_at': '2014-09-08T16:29:45Z', 'assets_url': 'https://api.github.com/repos/joeferraro/mm/releases/543050/assets', 'created_at': '2014-09-08T16:24:26Z', 'author': {'id': 54157, 'gravatar_id': '', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'html_url': 'https://github.com/joeferraro', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'login': 'joeferraro', 'type': 'User', 'url': 'https://api.github.com/users/joeferraro', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'zipball_url': 'https://api.github.com/repos/joeferraro/mm/zipball/v0.2.4', 'assets': [{'id': 232483, 'created_at': '2014-09-08T16:32:11Z', 'name': 'mm-linux.tar.gz', 'download_count': 1258, 'updated_at': '2014-09-08T16:32:16Z', 'size': 13496681, 'content_type': 'application/gzip', 'label': '', 'uploader': {'id': 54157, 'gravatar_id': '', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'html_url': 'https://github.com/joeferraro', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'login': 'joeferraro', 'type': 'User', 'url': 'https://api.github.com/users/joeferraro', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232483', 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-linux.tar.gz', 'state': 'uploaded'}, {'id': 232484, 'created_at': '2014-09-08T16:32:29Z', 'name': 'mm-osx-v0.2.4.zip', 'download_count': 10838, 'updated_at': '2014-09-08T16:32:36Z', 'size': 11164657, 'content_type': 'application/zip', 'label': None, 'uploader': {'id': 54157, 'gravatar_id': '', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'html_url': 'https://github.com/joeferraro', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'login': 'joeferraro', 'type': 'User', 'url': 'https://api.github.com/users/joeferraro', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232484', 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-osx-v0.2.4.zip', 'state': 'uploaded'}, {'id': 232481, 'created_at': '2014-09-08T16:30:18Z', 'name': 'mm-win-v0.2.4.zip', 'download_count': 19753, 'updated_at': '2014-09-08T16:30:22Z', 'size': 11502317, 'content_type': 'application/octet-stream', 'label': '', 'uploader': {'id': 54157, 'gravatar_id': '', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'html_url': 'https://github.com/joeferraro', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'login': 'joeferraro', 'type': 'User', 'url': 'https://api.github.com/users/joeferraro', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232481', 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip', 'state': 'uploaded'}], 'url': 'https://api.github.com/repos/joeferraro/mm/releases/543050', 'prerelease': False}
[MAVENSMATE]: latest asset ---->
[MAVENSMATE]: {'id': 232481, 'created_at': '2014-09-08T16:30:18Z', 'name': 'mm-win-v0.2.4.zip', 'download_count': 19753, 'updated_at': '2014-09-08T16:30:22Z', 'size': 11502317, 'content_type': 'application/octet-stream', 'label': '', 'uploader': {'id': 54157, 'gravatar_id': '', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'html_url': 'https://github.com/joeferraro', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'login': 'joeferraro', 'type': 'User', 'url': 'https://api.github.com/users/joeferraro', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232481', 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip', 'state': 'uploaded'}
[MAVENSMATE]: attempting to download:   https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip
[MAVENSMATE] failed to send community activity
Traceback (most recent call last):
  File "./urllib/request.py", line 1248, in do_open
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 1206, in connect
  File "./ssl.py", line 245, in wrap_socket
  File "./ssl.py", line 345, in __init__
  File "./ssl.py", line 341, in __init__
  File "./ssl.py", line 548, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rajeevd\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 189, in run
    self.install()
  File "C:\Users\rajeevd\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 310, in install
    with urllib.request.urlopen(download_url) as response, open(os.path.join(sublime.packages_path(),"User","MavensMate",zip_name), 'wb') as out_file:
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 475, in open
  File "./urllib/request.py", line 587, in http_response
  File "./urllib/request.py", line 507, in error
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 692, in http_error_302
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1283, in https_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
[MAVENSMATE]: [MAVENSMATE] could not install mm
[MAVENSMATE]: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
[MAVENSMATE]: handling result of mm update!!!
Package Control: No updated packages
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}

Is it happening because of limited access?

**Comment by joeferraro** [comment]
You likely have a firewall or local network issue that's preventing you from downloading the mavensmate api from github

**Comment by rajeevdubey007** [comment]
okk, Thanks joe :+1:
