### ISSUE TITLE
Create Resource Bundle not working

### ISSUE THREAD

**Issue by KaushikRay** [joeferraro/MavensMate-SublimeText#611]
Hello,

I am trying to create resource bundle for my static resources, but not able to when I run the "Create Resource Bundle" command, it shows the resource-bundles folder in explorer, but have nothing in it.

Any further details that I can check or give, please let me know. 

Also, I get [Resource bundle creation complete] in console, but there is nothing under resource-bundle folder.

Thanks

**Comment by roulupen** [comment]
Same problem I'm facing. Did you get any solution for this?

**Comment by KaushikRay** [comment]
Nope..possibly because of some network restrictions I am facing this. Are you using it in office network where there can be restrictions?

**Comment by roulupen** [comment]
Got the solution. Basically if you'r zip file directly contains your static resource files then it won't work. You need to add a base folder inside the zip.

Example: Let say I have style.css and action.js then my zip file should contain..

Zip Root/<AnyFolderName>/style.css
Zip Root /<AnyFolderName>/action.js
