### ISSUE TITLE
MM 5.0: Code coverage not showing

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate-SublimeText#613]
sometimes I am able to see code coverage numbers but even then I can't click on the show coverage button. Error in debug console.

<img width="753" alt="mavensmate___mercdev_r6_and_gso--mercdevr6___meeting_process_workflows___salesforce_com_-_performance_edition" src="https://cloud.githubusercontent.com/assets/757939/8831623/90314822-3071-11e5-9e98-607a8eb17343.png">

**Comment by joeferraro** [comment]
Is the file in question in your project?

**Comment by kylethornton** [comment]
Yes, it is.

**Comment by joeferraro** [comment]
@kylethornton can you be sure to post any relevant mavensmate.log's with your reports? thanks

**Comment by kylethornton** [comment]
This is all I had. There seemed to be nothing relevant: https://gist.github.com/kylethornton/a4ab2b262c4d60680b4e

**Comment by joeferraro** [comment]
resolved in mm-app 0.0.9
