### ISSUE TITLE
Unit tests fail when running a single test with error

### ISSUE THREAD

**Issue by rapsacnz** [joeferraro/MavensMate-SublimeText#620]
Here is the error:

ERROR:suds.client: 00DK0000007bboT!ARkAQFrS3z0DIqY_hiJikwo6z0IH5hU8Macws1IdoZgpgLKYSk3E8fYOvutl.9k_uDmXEJ6oRPpzr6y8RoaAGRcCT250Vcvg Apex_code DEBUG UEsDBBQAAAAIAHpvA0cAAAAAAgAAAAAAAAAGAAAAbW0uemlwAwBQSwMEFAAAAAgAem8DR8EzMER0AAAAhAAAABYAAAB1bnBhY2thZ2VkL3BhY2thZ2UueG1sNcyxCsIwEIDh2TxFuN1c1CIiSbp17qAPcKRnLTW50gTx8XWo4w8/n2s/6aXfvJZJsoeDsaA5RxmmPHq437r9BdqgXE9xppH1787Fw7PW5YpYhBZTHrJGNlESHq09o20wcaWBKkFQO7fh4dQY6/BfyuFmhi9QSwECFAMUAAAACAB6bwNHAAAAAAIAAAAAAAAABgAAAAAAAAAAAAAApIEAAAAAbW0uemlwUEsBAhQDFAAAAAgAem8DR8EzMER0AAAAhAAAABYAAAAAAAAAAAAAAKSBJgAAAHVucGFja2FnZWQvcGFja2FnZS54bWxQSwUGAAAAAAIAAgB4AAAAzgAAAAAA true true false CEOTest_Payment_WS {"body": "Server raised fault: 'INVALID_OPERATION: runTests can only be used with a testLevel of RunSpecifiedTests'", "stack_trace": "Traceback (most recent call last):\n File \"mm.request\", line 93, in execute\n File \"mm.commands.unittest\", line 30, in execute\n File \"mm.commands.unittest\", line 106, in execute\n File \"mm.sfdc_client\", line 191, in deploy\n File \"mm.sforce.metadata\", line 227, in deploy\n File \"suds.client\", line 542, in __call__\n File \"suds.client\", line 602, in invoke\n File \"suds.client\", line 649, in send\n File \"suds.client\", line 702, in failed\n File \"suds.bindings.binding\", line 265, in get_fault\nWebFault: Server raised fault: 'INVALID_OPERATION: runTests can only be used with a testLevel of RunSpecifiedTests'\n", "success": false}

**Comment by kylethornton** [comment]
See https://github.com/joeferraro/MavensMate/issues/451. If you roll your api version back to 33 it should solve your issue.

**Comment by joeferraro** [comment]
dup, thanks @kylethornton

**Comment by mubeen-qawi** [comment]
Hello Kyle, getting the same error, even though I am on api version 33.0. Any help would be much appreciated

**Comment by nwoolls** [comment]
Any idea what else could cause this? I am getting this as well for tests that worked previously (minutes / hours ago) with no changes to the code or XML.

Running the Unit Tests from the UI on a separate machine still works. I've tried setting the API version to 33 (even though it works fine at 34 on another machine) but it didn't help.

This is on OS X with version 4.0.5 of MM. The error / issue doesn't happen with the latest betas, but again this worked until very recently with 4.0.5 as well.
