### ISSUE TITLE
MM 5.0 nonnumeric port: 'None' error on start

### ISSUE THREAD

**Issue by steals** [joeferraro/MavensMate-SublimeText#622]
Updated to mavensmate 0.0.38-beta17, updated MM ST plugin and now I get following error:
=============> Loading MavensMate for Sublime Text
/usr/local/bin/node
/usr/local/bin/npm
/usr/local/bin/mavensmate
nonnumeric port: 'None'

**Comment by joeferraro** [comment]
What is your `mm_server_port` setting?

**Comment by steals** [comment]
56248 as specified in  default settings.
And I don't override it in user settings.

**Comment by joeferraro** [comment]
thanks. yeah it seems there's an odd race condition preventing cli.py from reading settings on startup. looking into it ...

**Comment by joeferraro** [comment]
@steals thanks for testing. please also keep in mind that when v5 goes live, it will be reliant upon the newly-created [mavensmate-app](https://github.com/joeferraro/mavensmate-app), which is an Electron wrapper around the `mavensmate` core. This ensures users do not have to install node/dependencies/native bindings. You can of course start testing that now, as you see fit, or you can continue to run beta versions of `mavensmate`.
