### ISSUE TITLE
Frequently lose connection to mm server

### ISSUE THREAD

**Issue by yippie** [joeferraro/MavensMate-SublimeText#623]
If I have SublimeText open for a while without using a MavensMate project (such as working on other files or projects) or if I have it open and open an existing MavensMate project, SublimeText will not be able to connect to the server even after restarting the server.  The fix is to restart SublimeText and then it works again.

This happens several times per day.

Running MavensMate v5.0.0 and server v0.0.38-beta18

**Comment by joeferraro** [comment]
I believe this has been addressed in this most recent release(s) of the app. feel free to re-open if you continue to experience it @yippie
