### ISSUE TITLE
Cannot create new project. Server did not respond properly.

### ISSUE THREAD

**Issue by kushney** [joeferraro/MavensMate-SublimeText#624]
I get this error when trying to create new project from ui html page:
<The local MavensMate server did not respond properly. This likely means it is not running or it is malfunctioning. Try restarting your text editor and MavensMate.app.>
After restarting Sublime Text I get new error: <Not connected. Verify Network.>
In html debugger I see that HTTP Post to http://127.0.0.1:7777/generic/async returns net::ERR_CONNECTION_RESET. But I have 7777 port opened on localhost. I simply can't create new project =(

**Comment by joeferraro** [comment]
Please include version number on any new issue

**Comment by kushney** [comment]
Windows 10
MavensMate for Sublime Text v4.0.5
MavensMate API v0.2.41
Sublime Text 3 Build 3083

**Comment by joeferraro** [comment]
can you please enable logging and attach any relevant log(s)? http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging

**Comment by kushney** [comment]
mm.log is empty file. Next are mmst and mmui
![image](https://cloud.githubusercontent.com/assets/10085582/9251545/688d15a4-41dc-11e5-8ab6-a191ca136aa9.png)
![image](https://cloud.githubusercontent.com/assets/10085582/9251551/728de34e-41dc-11e5-9884-fde2cfe597d6.png)
