### ISSUE TITLE
Request to the local MavensMate server failed. please ensure the MavensMate app is running.

### ISSUE THREAD

**Issue by soni21deep** [joeferraro/MavensMate-SublimeText#626]
Hi,

I opened mm today and got this error "Request to the local MavensMate server failed. please ensure the MavensMate app is running." and its occuring all the time, due to this, I can't do anything.

I am using MavensMate for Sublime Text v5.0.0-beta.2

Any help will be appreciable.

Thanks
Deepak

**Comment by vinodkr** [comment]
Hi Soni,

I also faced issue with Mavens Mate beta version (v5.0.0-beta.2), I could not resolve this problem.
What I have done is, I have uninstalled mavens mate and re-installed stable version V4.0.5. It working fine for me.

**Comment by r7ay** [comment]
See [this message](https://github.com/joeferraro/MavensMate-SublimeText/blob/master/messages/5.0.0.txt).

You need to install and run [mavensmate-app](https://github.com/joeferraro/mavensmate-app/releases).

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate/issues/483

**Comment by joeferraro** [comment]
@r7ay is correct. If you do not wish to test the prereleases, you should set your `install_prereleases` [Package Control setting](https://packagecontrol.io/docs/settings) to false (or, if you're managing `install_prereleases` as an array, remove `"MavensMate"` from the array of packages). If you'd like to test this prerelease, you need to install and run mavensmate-app as the instructions indicate.

**Comment by soni21deep** [comment]
Thanks everyone.

@joeferraro I tried to update install_prereleases Package Control setting to false, but failed. It won't allow me to update on that file, but i can update other settings.

Do we have stable release of mavesmate-app?

Thanks

**Comment by soni21deep** [comment]
@joeferraro Joe, I got it, actually I need to add this in user settings, not the default. Before I was trying to update default setting which is not editable.

Thanks

**Comment by aovri** [comment]
I have updated "install_prereleases to false in Package control > Settings - User, but still get the same error:  
"Result: [ERROR]: Request to the local MavensMate server failed. please ensure the MavensMate-app is running."
I don't want to install the new release. How can I fix this issue?

**Comment by joeferraro** [comment]
@aovri 

```
cd /sublime/text/packages/path
git clone https://github.com/joeferraro/MavensMate-SublimeText "MavensMate"
cd MavensMate
git checkout tags/v4.0.5
```

**Comment by aovri** [comment]
Hmmmm... Just did the steps outlined. Restarted Sublime. When going to an existing Salesforce project still getting the same error:
ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved. For more information, please visit https://github.com/joeferraro/MavensMate-app#mavensmate-app

Anything else I could do?

**Comment by grisdip** [comment]
I had to open MavensMave application directly and set the workspace path, that fix my error, but If I close MavensMate could not run anything on sublime.

**Comment by aovri** [comment]
I'll try that. I'd assume that the following path is correct for cloning MavensMate:
/applications/Sublime Text.app/Contents/MacOS/Packages?

**Comment by joeferraro** [comment]
something like `/Users/<your username>/Library/Application Support/Sublime Text 3/Packages`

**Comment by howshannon** [comment]
I've installed on my machine with success and used this earlier today without issue. Tried to install on a colleague's machine following the same exact steps, but got the error below. Now, when I go to Settings > User Plugin Settings on my machine with my install (which has never been an issue before), my MavensMate gives me this issue.

[ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved. For more information, please visit https://github.com/joeferraro/MavensMate-app#mavensmate-app

**Comment by joeferraro** [comment]
Do you have MavensMate-app installed? Is it running? https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.6

**Comment by howshannon** [comment]
Yes, yes. v5.0.0.

**Comment by joeferraro** [comment]
@howshannon that's not a valid mm-app version

**Comment by aovri** [comment]
Great. Thanks, Joe. It's working now. Just had to reset the mm_workspace value.

**Comment by howshannon** [comment]
That's the version we both have. Installed package control for Sublime, then got it from Package Control > MavensMate

**Comment by joeferraro** [comment]
Right, that's your plugin version (5.0.0). In MM for ST 5+, there's a companion app called MavensMate-app that needs to be installed and running, hence the error message

```
ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved. For more information, please visit https://github.com/joeferraro/MavensMate-app#mavensmate-app
```

For more info, see release notes: https://github.com/joeferraro/MavensMate-SublimeText/blob/master/messages/5.0.0.txt

Do you have MavensMate-app installed and running?

**Comment by howshannon** [comment]
Thank you. Ok, installed the app and still have the same error after restarting Sublime. Upon launching the app, I received a Windows firewall error - not sure that's causing the issue since I've deployed/built projects last week without issue. Was MavensMate updated this week to require the app/additional permissions?

**Comment by howshannon** [comment]
AHHHHHH! User freaking error. Sorry I was being such a dolt. 1. Open app 2. Open Sublime.

Jeeeeeeeeeze.

**Comment by joeferraro** [comment]
@howshannon no worries, it's confusing for folks, which is certainly understandable! We're working to make the messaging a little clearer

**Comment by howshannon** [comment]
It is pretty clear. I just have low comprehension. :)

**Comment by Benzeen-Talha** [comment]
It took me couple of hours to fix the issue even after reading all the above posts. Error and Instructions are not clear. Tried to open my project and got the message saying MavensMate App is required  and I was thinking what is that.. !!!??? On a Mac the first step to fix this issue is to install the App... took me time to comprehend that. However, working now so thanks to all.
Cheers
