### ISSUE TITLE
Cannot refresh folder from server

### ISSUE THREAD

**Issue by JPipkin** [joeferraro/MavensMate-SublimeText#628]
Whenever I right click my project folder in Sublime Text and go to Mavensmate > Refresh from Server, the console throws the error: 
"Operation: Refreshing: C:\Users\J. Pipkin\Desktop\MavensMate\DevX
Timestamp: Tue, 18 Aug 2015 07:20:03
   Result: [ERROR]: Cannot read property 'inFolder' of undefined"

How do I refresh my project's metadata now with the new release?

Version: MavensMate for Sublime Text v5.0.0-beta.2

**Comment by joeferraro** [comment]
to revert your project to server state, run the clean project command

**Comment by JPipkin** [comment]
@joeferraro Running the clean project command is erasing everything in the src folder in the project.

**Comment by joeferraro** [comment]
> Running the clean project command is erasing everything in the src folder in the project.

this should only happen if you have an empty `package.xml`

Can you set `mm_log_location` and `mm_log_level` in your MavensMate.app global settings and attach the relevant logs? thanks

**Comment by JPipkin** [comment]
@joeferraro The clean project command is working correctly now. I'm not sure what happened before (2 of our developers reported the same thing) but looks like it is fixed. You can close this issue. 

Thanks!
