### ISSUE TITLE
Editor doesn't open new metadata after creation (Beta)

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate-SublimeText#630]
Using prelease v5.0.0-beta2

when a new piece of metadata is created in the new mavensmate app ui, it no longer opens the file in the text editor

migrated from https://github.com/joeferraro/mavensmate-app/issues/6

**Comment by joeferraro** [comment]
hey @ralphcallaway fyi this has been fixed in v0.0.1-beta4 of mavensmate-app https://github.com/joeferraro/mavensmate-app/releases

**Comment by ralphcallaway** [comment]
sweet, thanks @joeferraro
