### ISSUE TITLE
"Create Lightning Component" ignores checkboxes selected

### ISSUE THREAD

**Issue by gbreavin** [joeferraro/MavensMate-SublimeText#633]
I created a New Lightning Component through the MavensMate menu - the MavensMate app pops up and asks for a Name, Description, and presents some checkboxes about whether a Controller, Helper, Style, Documentation, and Renderer should be created.

These checkboxes seem to be ignored - the .cmp is created, but none of the other files are.

I'm using v5.0.0-beta.3. Apologies in advance if PEBCAK.

**Comment by joeferraro** [comment]
@gbreavin thx for the report! :+1:

**Comment by joeferraro** [comment]
@gbreavin this issue is addressed in MavensMate.app (no need to update Sublime Text) `v0.0.1-beta4` https://github.com/joeferraro/mavensmate-app/releases

**Comment by gbreavin** [comment]
@joeferraro Thanks, I upgraded this morning, working for me :)
