### ISSUE TITLE
Conflict Diff Viewer Not Loading with v5.0.0

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate-SublimeText#634]
Using v5.0.0-beta.2

If a server conflict was detected pre v5.0.0 the a diff viewer was loaded. With v5.0.0-beta2 a dialog is presented asking if user would like to overwrite server version, but no option to view diff.

Not sure if this was an intentional removal of the feature ...

**Comment by joeferraro** [comment]
do you have `mm_diff_server_conflicts` set in your Sublime Text settings?

**Comment by ralphcallaway** [comment]
@joeferraro nope, don't have that setting, looks like it's not in the project settings either, not sure if i had it before or whether it was overwritten during the upgrade

added it to my user settings and doing some testing

**Comment by ralphcallaway** [comment]
that was it, thanks @joeferraro 

added the setting to my user settings and it's working as expected now
