### ISSUE TITLE
[Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by fishdag** [joeferraro/MavensMate-SublimeText#639]
Hi,
Every action i try to do results with this error. Couldn't find any information about it?
Any help please?

I'm using MavensMate for Sublime Text v4.0.5, on Sublime Text 3.
OSX Yosemite 10.10.5

**Comment by volubilis** [comment]
I have been experiencing the same issue since today. There absolutely no obvious reason from a setup perspective. Anyone with advice?

**Comment by volubilis** [comment]
OSX Yosemite 10.10.3

**Comment by joeferraro** [comment]
Guys nothing changed on our side, this is likely a Salesforce issue. Until it's proven this is a MavensMate issue, will close.
