### ISSUE TITLE
Validate/Deploy to server: System keychain service not supported

### ISSUE THREAD

**Issue by georgesguigui** [joeferraro/MavensMate-SublimeText#642]
Hi,
I'm using SublimeText3 with MavensMate for Sublime Text v5.0.0-beta.2 on a windows 7 (64bits).
When I'm trying to validate deployment (or deploy to server), following error message appears:
"System keychain service not supported".
![image](https://cloud.githubusercontent.com/assets/1609526/9443686/6f3510d6-4a93-11e5-8527-bbeef610145e.png)

I try recreate project from scratch.
Same error always occurs.

I also try to disable mm_use_keyring (set it to false in MavensMate UI):
![image](https://cloud.githubusercontent.com/assets/1609526/9443719/b9501864-4a93-11e5-97c2-0df29b221030.png)

But error message still appears.

Regards,

**Comment by joeferraro** [comment]
@georgesguigui thanks for the report, we're looking into it

**Comment by joeferraro** [comment]
@georgesguigui v0.0.1-beta7 of mavensmate-app resolves this keychain issue https://github.com/joeferraro/mavensmate-app/releases/tag/v0.0.1-beta7

I'm going to close this issue for now. If you still experience it, please feel free to re-open
