### ISSUE TITLE
Default Success/Failure save sound not playing

### ISSUE THREAD

**Issue by Aijaz13** [joeferraro/MavensMate-SublimeText#645]
When I am saving the File the default success/failure sound are not playing.
I have an updated mm API.

**Comment by brosiusad** [comment]
Same here.  After upgrading to v5.0-beta5, I get no sounds. I also see there are no prefs (global, user or default) to set the sound preferences, like there was in the previous version.  Is the sound feature gone?

**Comment by dmcheng** [comment]
I'm having the same issue - no sounds when saving in Sublime.  I have mm v5.0, running OS X.   The mavensmate-app does make sounds when running unit tests.

**Comment by Avarga954** [comment]
I have the same issue i have checked all the config files and they are all enabled
(╯°□°）╯︵ ┻━┻

**Comment by CSTufts** [comment]
to throw my two cents in, I customized my sounds and modified the pref file, but now cannot navigate back to the preference file (and it appears that the update blew up the customization as I used the saem file path the app uses by default

mac osx 10.9.5, SublimeText 3 B3083, latest mm app as of today. let me know if you need any more info

thanks for the quick response Joe!

**Comment by gpauriyal** [comment]
i am facing the same issue. I have correctly enable the sound setting using Mavensmate app. But no help.
It is little inconvenient not to hear sounds As early it was easy to know if my code was saved or not even though  i am not watching the compilation.

**Comment by beswickm** [comment]
I also miss the sounds

**Comment by Rsalyme** [comment]
I miss the sounds myself

**Comment by Katulka** [comment]
I really the sounds the most ;)
