### ISSUE TITLE
Cannot connect to Salesforce.com through plugin 

### ISSUE THREAD

**Issue by provantresource** [joeferraro/MavensMate-SublimeText#646]
![timeout](https://cloud.githubusercontent.com/assets/14079966/9631601/1785d2ee-5150-11e5-8e73-162f40382e03.PNG)
Not sure what is going on here. I am running windows 7 on my pc and I've installed / Unistalled so many times I've lost count. I'm now seeing the interface to enter my log in credentials and nothing is happening once I submit my credentials (New IE Window Pops Open) .. nothing happens. Any insight would be great so I could start using this tool. 

Thanks in advance

**Comment by provantresource** [comment]
{"body": "[Errno 2] No such file or directory: u'C:\\\\Users\\\\ablair\\\\Desktop\\\\Sublime\\\\Sample Project B

**Comment by joeferraro** [comment]
@provantresource Hi, the APIs in the current version of the Sublime Text plugin will be deprecated as of v5 (which is in beta). Given we will not be fixing issues in the v4 codebase, I'd recommend installing the v5 beta (https://github.com/joeferraro/MavensMate-SublimeText#install). 

To install the v5 beta:

1. Add "MavensMate" to your "install_prereleases" Package Control user setting in Sublime Text
![screen shot 2015-09-02 at 9 10 17 am](https://cloud.githubusercontent.com/assets/54157/9632003/79242b02-5152-11e5-8672-d91bb549cee6.png)
![package_control_sublime-settings_ _df15-react-communities-ios](https://cloud.githubusercontent.com/assets/54157/9632015/8cf6d800-5152-11e5-925e-627995a4aef5.png)
2. Install mavensmate-app from https://github.com/joeferraro/mavensmate-app/releases
3. Configure your workspace(s) in the mavensmate-app settings menu
![screen shot 2015-09-02 at 9 12 00 am](https://cloud.githubusercontent.com/assets/54157/9632042/b56e7392-5152-11e5-999e-27793f692ec6.png)
