### ISSUE TITLE
Error loading syntax file Visualforce.sublime-syntax

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate-SublimeText#650]
version: v5.0.0-beta4

after the beta 4 getting this error message on start up
```
Error loading syntax file "Packages/MavensMate/sublime/lang/Visualforce.sublime-syntax": Error parsing plist xml: expected < in file Packages/MavensMate/sublime/lang/Visualforce.sublime-syntax on line: 1
```

i've run into this in the past so hopefully i can resolve, but wanted to flag in case we want to update the v5.0.0-beta4 release notes to include instructions for addressing this

side note, the release notes never display for me, not sure why ... seems like an st3 issue since i haven't seen any release notes for any package in quite a while and i know some have been upgraded

**Comment by joeferraro** [comment]
does a close and re-open of the file resolve that issue?

**Comment by ralphcallaway** [comment]
nope, checked that the yaml in the syntax file was good, looks line ...

quit and restart a couple times and it keeps happening every time i open a .page file ...

going to try re-installing the package to see if that does anything

**Comment by joeferraro** [comment]
hmmm https://github.com/DisposaBoy/GoSublime/issues/262#issuecomment-20557372

**Comment by joeferraro** [comment]
also ...

![sublime_forum_ _view_topic_-__solved__missing_syntax_file_errors](https://cloud.githubusercontent.com/assets/54157/9796015/db83e1aa-57c1-11e5-8dc4-ceddc1b583cd.png)

**Comment by ralphcallaway** [comment]
i've gotten similar errors a lot over the years, usually was something with caching of an old syntax file

**Comment by ralphcallaway** [comment]
yeah, removing the session sounds familiar, clean install didn't change anything, trying the session/cache/index wipe to see if those work

**Comment by joeferraro** [comment]
also try closing any open windows: https://github.com/gerardroche/sublime-php-grammar/issues/9#issuecomment-108865807

**Comment by ralphcallaway** [comment]
no dice, removed the session, mavensmate cache, and cleared the index files, still getting the error

since this is a no syntax file those might not be applicable, i noticed that the mavensmate cache didn't include the visualforce syntax file (but did included all the apex grammars)

**Comment by ralphcallaway** [comment]
yeah, i'm closing all windows and projects, and quitting and restarting st3 each time, hmmm, the error just doesn't seem all that helpful

**Comment by ralphcallaway** [comment]
stupid question, but is the syntax file loading correctly for you?

**Comment by ralphcallaway** [comment]
heading into a meeting, could this be that this syntax format isn't available yet?

there is a note on http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/extensibility/syntaxdefs.html

that says this is only available as of build 3084, and only on the dev channel (could be out of date)

looks like i'm on build 3083 ... maybe that's the issue? could you be writing this on the dev version of st3?

**Comment by joeferraro** [comment]
great find, had no idea. will figure out how to workaround

**Comment by ralphcallaway** [comment]
sweet, glad i could help track it down, now just need some more time to actually do some coding ... it's projects, projects, projects over here!

**Comment by b-wilder** [comment]
It seems a mavensmate update that was pushed today broke this again for the visualforce syntax only. I tried all the stuff ralphcallaway did and it didn't work.

**Comment by joeferraro** [comment]
@b-wilder What version of Sublime are you using

**Comment by b-wilder** [comment]
I just updated to the latest minor version of v3

**Comment by joeferraro** [comment]
build 3114? https://www.sublimetext.com/3

**Comment by b-wilder** [comment]
Yes.

 Prior to upgrading sublimetext to this build apex syntax also wasn't working.

**Comment by mattparkerls** [comment]
I'm getting the same but also for Apex syntax: 
`Error loading syntax file "Packages/MavensMate/sublime/lang/Apex.sublime-syntax": Error parsing plist xml: expected < in file Packages/MavensMate/sublime/lang/Apex.sublime-syntax on line: 1`

I've had mm_auto_install_mm_updates and mm_check_for_updates both set for false for months - somehow I also received the update.

**Comment by b-wilder** [comment]
mattparkerls same here. I had auto-updates turned off.

**Comment by mattparkerls** [comment]
Ah actually my Sublime build is 3065 - but strange the issues started the same as the 3114 build release

**Comment by joeferraro** [comment]
3065 does not support .sublime-synax, 3114 does. I'd recommend updating to 3114 (which has resolved the issue for me)

**Comment by mattparkerls** [comment]
Yep - joe just tried that myself and it solved the problem.  No longer receiving either apex or visualforce syntax errors. Thanks man

**Comment by joeferraro** [comment]
cheers, @mattparkerls

**Comment by b-wilder** [comment]
3114 resolved the issue with apex for me but I still get it for visualforce. Any suggestions beyond clearing out the sublime session?

**Comment by joeferraro** [comment]
@b-wilder what version of MM are you using?

**Comment by b-wilder** [comment]
@joeferraro admittedly i don't know how to check. I can see from the lastmodified date on the files that it got updated today.

**Comment by joeferraro** [comment]
MavensMate > About MavensMate

**Comment by b-wilder** [comment]
"we decided to roll back to the v4.0.5 codebase, which is the version you are running now (v6)"

However everything in the Packages/MavensMate and Packages/MavensMate/lib folder has a last modified date of today

**Comment by Prophyt** [comment]
Having the same issue, running 3114.

**Comment by BenMacAttk** [comment]
I am having the same issue as well, running 3114 with MM v6.0.2

**Comment by joeferraro** [comment]
Hm, I've testing 6.0.2 and 7.0.0 on 3114 and don't have any syntax definition issues. There may be a local Sublime Text cache that's causing the error message (this has happened to me before with our plugins). You may try re-installing ST and/or MM or restarting your machine to see whether that clears any ST indices that may be causing the problem.

**Comment by MaggiePlusPlus** [comment]
I have 3114 and 6.0.2 and get same visualforce syntax error

**Comment by Prophyt** [comment]
I have reinstalled Sublime, and MM, and cleared the local cache; issue continues

**Comment by shrawanraina** [comment]
I cleared the cache but getting the same visualforce syntax error. Running 3114 & 6.0.2

**Comment by FabricioPatrocinio** [comment]
Não tem solução, apenas exclua a pasta **Installed Packages** onde o sublime text 3 está instalado. Tudo voltará ao normal.
Se estiver usando Linux Mint ou Ubuntu use:
**cd .config**
**xdg-open .**
Depois disso instale novamente seus pacotes, e vá notando qual deles vai acabar fazendo com que gere o mesmo erro, com isso, basta você ter em mente qual vai comprometer, e nunca mais instalar ele até isso ser resolvido pelo pessoal que cria tais pacotes.
