### ISSUE TITLE
Custom Templates not working

### ISSUE THREAD

**Issue by dougporter-revelant** [joeferraro/MavensMate-SublimeText#651]
I'm receiving an error message:

{"checkOnly": false, "completedDate": "2015-09-10T19:56:26.000Z", "createdBy": "00561000000I7mu", "createdByName": "Admin", "createdDate": "2015-09-10T19:56:25.000Z", "details": {"componentFailures": {"changed": false, "componentType": "ApexClass", "created": false, "createdDate": "2015-09-10T19:56:25.000Z", "deleted": false, "fileName": "unpackaged/classes/controllerTest.cls", "fullName": "controllerTest", "lineNumber": "1", "problem": "unexpected token: '<EOF>'", "problemType": "Error", "success": false}, "componentSuccesses": {"changed": true, "componentType": null, "created": false, "createdDate": "2015-09-10T19:56:25.000Z", "deleted": false, "fileName": "unpackaged/package.xml", "fullName": "package.xml", "success": true}, "runTestResult": {"numFailures": "0", "numTestsRun": "0", "totalTime": "0.0"}}, "done": true, "id": "0Af3B0000004mPHSAY", "ignoreWarnings": false, "lastModifiedDate": "2015-09-10T19:56:26.000Z", "numberComponentErrors": "1", "numberComponentsDeployed": "0", "numberComponentsTotal": "1", "numberTestErrors": "0", "numberTestsCompleted": "0", "numberTestsTotal": "0", "rollbackOnError": true, "runTestsEnabled": true, "startDate": "2015-09-10T19:56:25.000Z", "status": "Failed", "success": false}

In a template that I created, code:

/********************************************************************************
*
*	Unit Test Name:		{{ api_name }}
*	Class to test:		{{ class_name }}
*	Created By:			First Last 
*	Created On:			01/01/2015
*	Last Modified On:	01/01/2015
*	Last Modified By:	First Last  
*
*	Revision Log:		01/01/2015 - Initial creation
*
********************************************************************************/

@isTest
private class {{ api_name }}  {
	
	//create class level instance of class being tested
	//private static {{ class_name }} controller;
	
	static testMethod void test_{{ class_name }}() {
		//construct starter data and instantiate class being tested
		init();
		
		//modify data as needed and use system.assert() to test.
		
		//close test method
		close();
	}

	static testMethod void testUnitMethod1() {
		//construct starter data and instantiate class being tested
		init();
		
		//modify data as needed, call unitMethod (add parameters and return if needed)
		//controller.unitMethod1();
		
		//use system.assert() or assertEquals() to test.
		//system.assertEquals(controller.variable, 'expected value');
		
		//close test method
		close();
	}

	static testMethod void testUnitMethod2() {
		//construct starter data and instantiate class being tested
		init();
		
		//modify data as needed, call unitMethod (add parameters and return if needed)
		//controller.unitMethod2();
		
		//use system.assert() or assertEquals() to test.
		//system.assertEquals(controller.variable, 'expected value');
		
		//close test method
		close();
	}

	static testMethod void testUnitMethod3() {
		//construct starter data and instantiate class being tested
		init();
		
		//modify data as needed, call unitMethod (add parameters and return if needed)
		//controller.unitMethod3();
		
		//use system.assert() or assertEquals() to test.
		//system.assertEquals(controller.variable, 'expected value');
		
		//close test method
		close();
	}

	static void init() {
		//create all starter data in one method.
		createData();

		//instantiate class being tested. Add parameters as needed.
		//controller = new {{ class_name }}();
		
		test.StartTest();
	}

	static void close() {
		test.stopTest();
	}

	static void createData() {
		//create all starter data. Note that objects may have dependencies,
		//and will require those records to be created previously.
	}
	
} 

And when I open the file, it's empty. Any idea why that would be?

**Comment by joeferraro** [comment]
Hi @dougporter-revelant, can you please update your issue according to the guidelines? https://github.com/joeferraro/MavensMate-SublimeText/blob/master/CONTRIBUTING.md#submitting-issues

cheers

**Comment by dougporter-revelant** [comment]
Thanks @joeferraro for the quick response. Here's the remaining info that you requested (I think this is everything):

Platform: Windows 7
MavensMate Version: 0.2.41

Steps to reproduce: 
- Created template, placed in local templates folder.
- Updated package.json to include file in Apex Classes.
- Click Mavensmate -> Metadata -> New Apex Class
- Select created template name
- Put names in for parameters
- Receive error

Alternatively, as a side note, I attempted to update to the prerelease and can't see the template at all, after updating the template path and selecting local.

**Comment by dougporter-revelant** [comment]
After a complete uninstall and reinstall of MavensMate, I tried to replicate the issue again, and using MavensMate v4.0.5, it succeeded in creating the test class. :)
