### ISSUE TITLE
Set current class in editor as the test class to run by default

### ISSUE THREAD

**Issue by rwollmuth** [joeferraro/MavensMate-SublimeText#654]
Hi,

  In previous versions, when you chose to open the Apex Class Runner UI while on a test class, it would check that class by default. Could we add this in again?

Thanks!

**Comment by brosiusad** [comment]
+1

**Comment by daeschwed** [comment]
Hi all
me again, digging up ancient stuff…
This works just as expected and outlined in the issue.
@joeferraro suggesting to close this one, too.

for completeness sake, this post is based on the following setup:
OS X El Capitan v10.11.4
Sublime Text 3 Build 3103
MavensMate for Sublime Text v7.0.0-beta.1
MavensMate-app v0.0.11-beta1

Cheers
the swedish guy
