### ISSUE TITLE
If multiple Sublime Text windows open (in different environments), choose Metadata-> New <anything> creates in one editor and opens in another.

### ISSUE THREAD

**Issue by rwollmuth** [joeferraro/MavensMate-SublimeText#655]
I have had this problem previously as well. If I happen to have multiple Sublime Text windows open and choose to create a new Apex Class (for example) in one of the windows, the class is created in the secondary (non-selected) environment and the code is popped up in the primary window. 

Steps to reproduce:

1) Open 2 Sublime Text windows in 2 different environments
2) Choose MavensMate->Metadata->Create Apex Class
3) Expected: The class will be created in the selected window and the editor will pop up the new class
    What's happening: The class is created in the non-selected environment and the editor pops up the new class in the selected environment.

**Comment by joeferraro** [comment]
unfortunately, there's no way for us to resolve this given the limitations of the Sublime Text executable at this time
