### ISSUE TITLE
Open Project menu item missing in v5 beta.5

### ISSUE THREAD

**Issue by nwoolls** [joeferraro/MavensMate-SublimeText#656]
The rest of the Project menu items are there. This is under OS X with the MavensMate-app running. Menu looks / works right in 1.0.3 of Atom.

**Comment by joeferraro** [comment]
@nwoolls nice catch. you can still run the open project command via the command palette, fyi

**Comment by nwoolls** [comment]
@joeferraro I only see "MavensMate: New Project" for project commands available int he palette.

![screen shot 2015-09-21 at 12 23 40 pm](https://cloud.githubusercontent.com/assets/1683618/9997700/a517e736-605b-11e5-9cb7-4b6808f42327.png)
