### ISSUE TITLE
Indexing Metadata Fails

### ISSUE THREAD

**Issue by yippie** [joeferraro/MavensMate-SublimeText#657]
MavensMate app v0.0.2.

If I pull files from Github in a project but the package.xml/metadata had not been updated I get an error when trying to run unit tests.

"Invalid project metadata cache. Run Index Metadata command to reset the cache."

This error is annoying but fine.  The bug is when I select "Update Project Metadata" it fails with the error:

Operation: Indexing Metadata
Timestamp: Wed, 23 Sep 2015 13:39:13
   Result: [ERROR]: Cannot assign to read only property 'fullName' of 00530000005T9xZAAS

The same error happens if I try to edit the project metadata and click the refresh button to get the new classes to show. This leaves me in a position where I have to clean the project before I can continue.

**Comment by yippie** [comment]
New symptom to what I think is the same issue.  If the index is in this bad state, I cannot save files to Salesforce servers.  The save operation sits in progress indefinitely (I let it run for 30 min multiple times).  Like above, cleaning the project fixes it.

**Comment by joeferraro** [comment]
thanks @yippie. any idea how the index gets to a bad state?

**Comment by yippie** [comment]
Yes, git!

This seems to happen any time I pull someone else's changes down from git into my local project.  I think because the index doesn't match what is now in my codebase it is bugging out.

This has happened after every git pull I have done with one of my projects this past week.  Totally untested theorizing, but each pull has also involved a delete or rename that might be causing issues with the index thinking something is there but isn't.

**Comment by joeferraro** [comment]
i think you're probably 100% right. will keep it in mind, but not sure there's a better answer at the moment than cleaning the project.

what does your .gitignore look like?

**Comment by yippie** [comment]
The .gitignore checked into the project looks like this:

/config
*.sublime-settings
*.sublime-workspace
*.sublime-project
*.DS_Store
*.orig

/apex-scripts

**Comment by yippie** [comment]
@joeferraro There might be something else going on.  Even after cleaning the project, if I go to edit project then try to refresh the metadata, I getting this error.

**Comment by yippie** [comment]
Killing the .org_metadata and running the metadata index again does not fix it.  The indexing runs into the same error.

**Comment by joeferraro** [comment]
@yippie it seems like there could be multiple issues here. any chance you could help me distill this into clear steps to reproduce?

**Comment by yippie** [comment]
Yes, I will see if I can reproduce this in a new project.

**Comment by russlevy** [comment]
I had the same issue after upgrade from 4->5.

**Comment by joeferraro** [comment]
fyi this fix is here: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta2

**Comment by thegogz** [comment]
I can confirm the beta fixes the issues listed above, however its a bit of a pain in a fast moving project to do this every time you do a pull, is it possible to trigger the cache refresh from a CLI? if so a git hook should be able to trigger this

**Comment by Brian-Triplett** [comment]
@joeferraro I've been getting this same issue with release 0.0.10.  I did a fresh clone my repo, created a new MM project, then attempted to run unit tests and received a "Invalid project metadata cache. Run Index Metadata command to reset the cache.".  Upon trying the reset I get the "[ERROR]: Cannot assign to read only property 'fullName'" message.

**Comment by candacegu** [comment]
Just ran into this issue again and discovered the following work around: Uncheck custom objects from metadata subscription list, refresh metadata index, go back and recheck customObjects, run refresh metadata index again.
