### ISSUE TITLE
Not able to open project - windows

### ISSUE THREAD

**Issue by cmaiquel** [joeferraro/MavensMate-SublimeText#659]
The error is in "mavensmate.py", line 1569, in run workspaces = mm_core_settings['mm_workspace']
KeyError: 'mm_workspace'.

Seems that its not finding ".mavensmate-config.json". If I go to line 1568 and change this:

 mm_core_settings = util.parse_json_from_file(os.path.join(home, '.mavensmate-config.json')) 
workspaces = mm_core_settings['mm_workspace']

 to this:

mm_core_settings = sublime.load_settings('mavensmate.sublime-settings')
workspaces = mm_core_settings.get('mm_workspace')

It works !
But anyway there should be a reason for not finding that file (.mavensmate-config.json) in the user home directory.

Thanks !!!

**Comment by joeferraro** [comment]
@cmaiquel 

I imagine you're on a v5 beta? (please always include platform/versions https://github.com/joeferraro/MavensMate-SublimeText/blob/master/CONTRIBUTING.md)

thanks for the bug report. actually, `sublime.load_settings('mavensmate.sublime-settings')` are not core settings, those are plugin settings. Do you have mavensmate-app installed and running? Have you configured your workspaces there?

**Comment by cmaiquel** [comment]
@joeferraro 
Sorry I forgot to mention the version. 
I'm on v5 beta6 - windows 10. I have mavensmate-app installed and running, and I put my config there, such as workspace ... 
The thing is that sublime plugin was not finding '.mavensmate-config.json' I guess It has to be in the user/home
