### ISSUE TITLE
Account is required error on MavensMate

### ISSUE THREAD

**Issue by haripopuri** [joeferraro/MavensMate-SublimeText#663]
Hi,

I opened Sublime and looks like Mavens Mate updated to version 5. It says:

MavensMate for Sublime Text v5.0.0

[ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved. For more information, please visit https://github.com/joeferraro/MavensMate-app#mavensmate-app

I downloaded mavensmate app from github and installed. I opened MavensMate app and updated my workspace to point to my existing folder and opened a project.

When I am trying to save code, it opened a "Fix Project" window in MavenaMate app. I entered my username and password + token, then I get the "Account is required." message.

What account do I need and where to configure that?

Thanks
Hari

**Comment by joeferraro** [comment]
Hi @haripopuri apologies for the issue, this has been resolved in mavensmate-app v0.0.6 https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.6
