### ISSUE TITLE
Project missing?

### ISSUE THREAD

**Issue by mtwomey** [joeferraro/MavensMate-SublimeText#664]
I'm not familiar with the internal workings of MM, but it appears to have auto-upgraded. It prompted me to download and install the app, which I did. However, my project no longer seems to be there. Can I continue with my existing project somehow? 

v0.0.6 / Mac / Sublime 3

**Comment by mtwomey** [comment]
Ok - I added the path to the project into the "Array of local workspaces". It seems to work, just double-checking that this should be all I need?

**Comment by joeferraro** [comment]
Yes, this is all you need to do. :+1:
