### ISSUE TITLE
Unable to Open/Create project from Sublime

### ISSUE THREAD

**Issue by gazazello** [joeferraro/MavensMate-SublimeText#665]
Today I was forced to install new MavensMate.app v 5. But in order to open an existing project or create a new one I have to choose application with cursor and click on "Open Project". The command in Sublime CMD+SHIFT+O is not working anymore. How to fix that?

**Comment by joeferraro** [comment]
@gazazello apologies for the confusion, but you can open existing projects 3 different ways:
1. opening the directory in Sublime Text
2. using the MavensMate menu in Sublime Text > Project > Open Project
3. using the "Open Project" option in MavensMate-app

**Comment by gazazello** [comment]
@joeferraro thanks for response!
I am talking about option 2 in your list. It's not working for me anymore. I tried to reinstall MavensMate.app, restarting Sublime, restarting MavensMate. Nothing of that helped.

**Comment by joeferraro** [comment]
What version of MavensMate-app are you running? https://github.com/joeferraro/MavensMate-app

**Comment by gazazello** [comment]
I downloaded and installed this MavensMate-app-v0.0.6-osx-x64.zip
MavensMate in Sublime says "Version 5"

**Comment by xiiDev** [comment]
I have the same problem:(

**Comment by LKozakewycz** [comment]
I have the same issue where this no longer works and I really liked it because I was able to open projects within a split second. Now I have to take control of the mouse and can lose precious time in order to open another project. 

Would be nice to see this return.

**Comment by ScriptMonkey00** [comment]
I don't know if it's related, but I'm running on Ubuntu 14.04 and app 0.0.6.  My Open Project also doesn't work (nor does it work from the app) but when I try from the mavensmate pulldown in Sublime Text I get this in the console:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/home/scriptmonkey00/.config/sublime-text-3/Packages/MavensMate/mavensmate.py", line 1603, in run
    if util.get_friendly_platform_key() != 'windows':
  File "/home/scriptmonkey00/.config/sublime-text-3/Packages/MavensMate/util.py", line 33, in get_friendly_platform_key
    return friendly_platform_map[sys.platform]
KeyError: 'linux'

**Comment by joeferraro** [comment]
@ScriptMonkey00 what is the value of your `mm_sublime_text_executable_location` MM for ST plugin setting?

**Comment by ScriptMonkey00** [comment]
It was set to /usr/local/bin/subl but when I use which subl, I get usr/bin/subl, so I changed that in my config file but nothing changed.

**Comment by joeferraro** [comment]
@ScriptMonkey00 would you mind testing this again on 5.0.1? thanks

**Comment by ScriptMonkey00** [comment]
Unfortunately it's unchanged on my linux system (other than the hotkey for open being restored, which I'm very very grateful for by the way).

It still breaks with the same error.

**Comment by gazazello** [comment]
I resolved issue in my case!!!
When I was setting Workspace location in Global settings I put this:
[  "Users/my_name/my_workspace_path"  ]
And almost everything worked!! But notice that the path is RELATIVE and starts with "Users", but it should start with "/Users". So after I made that path absolute, Open/Create from Sublime with hotkeys started working again!!! Just look if any of paths in Global settings is relative and replace it with absolute.
Like this:
[  "/Users/your_name/your_workspace_path"  ]

**Comment by ScriptMonkey00** [comment]
Just wanted to add that I Was told a while ago by Joe to try again when 5.0.5 was released and I thought I'd mention here that the problem seems resolved on my Ubuntu system.  

Thanks again!
