### ISSUE TITLE
Have to separately start Mavens Mate application every time I start Sublime

### ISSUE THREAD

**Issue by gazazello** [joeferraro/MavensMate-SublimeText#666]
If I close MavensMate and close Sublime, then open Sublime I expect it to automatically start MavensMate behind the screen (like it used to do before this forced update). But instead I receive error message:
"Could not contact local MavensMate server, please ensure MavensMate-app is installed and running".
If I separately start MavensMate.app and after that start Sublime, then it works fine.
But every time I start MavensMate.app it asks for permission to accept incoming connections. Probably if I make it remember the setting, Sublime won't complain and will be able to start MavensMate itself. I have MacOs firewall turned ON, but I added MavensMate.app to list of allowed applications. And it still keeps asking permission every time I start.

**Comment by gazazello** [comment]
I just checked signature of MavensMate.app and codesign says "code object is not signed at all"

**Comment by LKozakewycz** [comment]
I think that is the way Mavensmate is now as all of my team have to do the same as well. This is a little frustrating to have to keep opening the application everytime we want to code. Would be nice to have this as a background process or in the system tray and automatically open when sublime does.

**Comment by joeferraro** [comment]
https://github.com/joeferraro/MavensMate-SublimeText/commit/6d643259b2f19f309f631f63301a65ce3eca7364 adds menu item to open the app and adds "Open MavensMate-app" command to the ST command palette. You can also set `mm_start_mavensmate_app` to `true` (and ensure `mm_mavensmate_app_location` is valid), which will open the app automatically for you.
