### ISSUE TITLE
OS X: Error contacting local MavensMate server

### ISSUE THREAD

**Issue by dmcheng** [joeferraro/MavensMate-SublimeText#667]
The Mavensmate 5 update ran on my OS X machine today.  Most of my projects are working, but a critical project is not.  In Sublime, I get  "Error contacting local MavensMate server" for most Mavensmate tasks like Open Mavensmate UI, creating new metadata, etc.  In the MM app, when I try to open the project, I just get "Loading" and the spinning wheel.  After a long time the wheel disappears and there's just an empty white screen for the "localhost" tab.

Does it have to do with OS X Keychain?  I notice that I've been prompted to allow keychain access for each project that I open in the MM app.  I click Always Allow and the other projects are working fine.

I installed the app and have it running.  I've set a debug log but I'm not seeing any clear errors in it.

I'm using OS X 10.10.5, Sublime 3 build 3083.

Here are the errors I'm seeing in the sublime console.

[MAVENSMATE]: Error contacting local MavensMate server: ''
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'error': "Request to the local MavensMate server failed. ''"}

**Comment by joeferraro** [comment]
Apologies for the inconvenience. Are you behind a firewall? Is there anything in the MavensMate-app console(s) ("Advanced" status bar menu)?

**Comment by dmcheng** [comment]
Hi Joe.  No, I'm not behind a firewall.  On the Advanced menu are Toggle Core Developer Tools and Toggle Mavensmate App Developer Tools.

**Comment by joeferraro** [comment]
When you say "most tasks" aren't functional, which ones are functional? For example can you create a new project from within MavensMate-app?

**Comment by dmcheng** [comment]
Yes, I can create a new project in MM-app directly, or in Sublime Text when I'm in any other project except one project.

The only issues I'm having are centered on a single project - I can't open it in MM-app (hangs for a long time, then a blank white screen with "localhost" tab).  When I open the project in Sublime Text, I get the "contacting" errors when I choose Run MavensMate UI, or Project > any options, or Metadata > any options.

**Comment by joeferraro** [comment]
Very odd. OK, can you do me a favor and tell me a little more about this project that is causing issues? What is the project's path? What are the contents of its config/.settings file? What are the contents of its package.xml?

**Comment by dmcheng** [comment]
I updated my Windows machine and was able to open the project on the Windows machine, though I did have to re-enter my Salesforce password for the project.  Should I try deleting the keychain entry on my Mac?

On the Mac, the project path is /Users/davidcheng/Documents/MavensMate/Health Leads CXFBUILD.  The .settings file is:
{
    "username": "david.cheng@idealistconsulting.com.cxfbuild", 
    "environment": "sandbox", 
    "project_name": "Health Leads CXFBUILD", 
    "workspace": "/Users/davidcheng/Documents/MavensMate", 
    "org_url": "", 
    "namespace": "", 
    "id": "4IJAVGAUC9520O3E3D72KC5DMXA29S8T", 
    "metadata_container": "1dcK00000002rxLIAQ", 
    "subscription": [
        "ApexClass", 
        "ApexComponent", 
        "ApexPage", 
        "ApexTrigger", 
        "StaticResource", 
        "CustomObject", 
        "Profile"
    ]
}

**Comment by dmcheng** [comment]
It's working now - This morning I deleted the config folder and three sublime files (sublime-project, sublime-settings, and sublime-workspace), dragged the project folder into an empty Sublime window and recreated the Mavensmate project.

The new .settings file now omits CustomObject and Profile.  I wonder if the issue was related to those items and the package.xml.

**Comment by joeferraro** [comment]
@dmcheng this is related to the default subscription setting in mavensmate-app
