### ISSUE TITLE
Apex script debug logs no longer open automatically after running

### ISSUE THREAD

**Issue by mjmoore** [joeferraro/MavensMate-SublimeText#669]
1. Create a new apex script.
2. Type something simple like `System.debug('Hello world');`
3. Run script.
4. Debug log is not automatically show as it should be.

Discovered after update to v5 with MavensMateApp dependency.

**Comment by mjmoore** [comment]
I would argue that this is a regression rather than an enhancement. The behaviour was present in previous versions of MavensMate-SublimeText, and was broken after the inclusion of the standalone MavensMate-App.

**Comment by joeferraro** [comment]
I would agree, however, the new Tooling API endpoint for executing anonymous does not return a log id for the apex you just executed. This is frustrating and a worse UX, for sure. This is one of those difficult situations where I'd like to stay current with the most modern and best-supported Salesforce API endpoints, however, in this case the experience is degraded & somewhat out of my control. Let me do some research to figure out whether we can execute anonymous against the legacy "apex" SOAP endpoint without performance degradation.
