### ISSUE TITLE
Mavensmate-app win7 - Confirm folder replace occurring at every metadata refresh 

### ISSUE THREAD

**Issue by saurabhkul** [joeferraro/MavensMate-SublimeText#671]
Hello,

I have updated to Mavensmate-app and whenever i refresh any metadata files it gives windows notification Confirm Folder Replace saying "This destination already contains a folder named 'UNPACKAGED'". This is very annoying since it is showing at every refresh and it blocks actual refresh. Please resolve this as soon as possible. 

Thanks,
![image](https://cloud.githubusercontent.com/assets/6883686/10192763/3f91f03a-679c-11e5-827d-44b8eeddb560.png)

**Comment by nsanthosh718** [comment]
I am facing the same issue and it is irritating. Is there any resolution for this yet?

**Comment by joeferraro** [comment]
Hi, would you guys mind downloaded https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.7-beta2 to see whether this resolves your issue?

**Comment by fricco** [comment]
@joeferraro I just tried it and is working. thank you!

**Comment by joeferraro** [comment]
@fricco :+1:

**Comment by saurabhkul** [comment]
Its resolved after updating to 0.0.7. Thanks for quick help.
