### ISSUE TITLE
Could not connect to local Mavensmate Server

### ISSUE THREAD

**Issue by nsanthosh718** [joeferraro/MavensMate-SublimeText#672]
Hello Joe,

I am not able to refresh or create any project after V5.0.0 update. I tried to uninstall and re-install app but did not work either. And this is in Windows. Can you please help? 

Error:
Result: [ERROR]: Request to the local MavensMate server failed. please ensure the MavensMate-app is running.

[ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved. For more information, please visit https://github.com/joeferraro/MavensMate-app#mavensmate-app

Thanks,
Santhosh

**Comment by rpbeam** [comment]
Same issue with me. Windows 7 behind a firewall and it has been working for along time.  I just got an upgrade downloaded.

**Comment by Eric-He** [comment]
I am having the same issue. It's been working for a long time.

**Comment by nsanthosh718** [comment]
It is resolved for me. For the latest release, Mavensmate came up with the UI for Windows as well similar to OS X and introduced global settings which can be modified from this UI.

Steps:
1) Install Mavensmate app
2) Update Mavensmate following the steps provided in the documentation
3) Update Global settings

There you go. Happy Coding!

**Comment by joeferraro** [comment]
If you're having firewall/proxy issues, we're tracking that issue here: https://github.com/joeferraro/MavensMate-app/issues/24

**Comment by joeferraro** [comment]
closing here, tracking all firewall/proxy issues here: https://github.com/joeferraro/MavensMate-app/issues/24
