### ISSUE TITLE
Improve search feature in debug log viewer in MavensMate-app

### ISSUE THREAD

**Issue by mikepaisner** [joeferraro/MavensMate-SublimeText#675]
When viewing the debug logs, there is no way to search the text of the debug logs.

The debug logs aren't very useful if I can't quickly search the contents of them.

Please prioritize adding a search feature.

Mike

**Comment by joeferraro** [comment]
Can you be more specific? Are you talking about viewing logs within Sublime Text or within the log viewer in MavensMate-app?

**Comment by mikepaisner** [comment]
I am looking at the Debug Logs within MavensMate-App.

Love that I can instantly see the logs appear as I work in Salesforce, but want to be able to find my debug statements and other stuff.

P.S. Great work overall on MavensMate.  I’ll never go back to Eclipse.

Regards,
Mike

[cid:image001.jpg@01D0FB5E.637B58B0]


Michael Paisner | Salesforce Application Developer
Esri | 380 New York Street | Redlands, CA 92373 | USA
909-793-2853 x 4209 | mpaisner@esri.com<mailto:mpaisner@esri.com> | esri.com<http://esri.com/>

**Comment by joeferraro** [comment]
there's a filter search box, which is why I'm confused. Is the filter not working?

**Comment by mikepaisner** [comment]
The filter works, however, that only shows the lines that explicitly contain words in the filter.

I frequently will put a keyword in my code to get to the right place in the debug log, but then I want to see all the debug info in that area.

Using the filter takes out all the other debug information.

[cid:image001.jpg@01D0FB5F.ABFEECE0]

Can you point me to where the log files are stored locally on my machine?

Thanks,
Mike


Michael Paisner | Salesforce Application Developer
Esri | 380 New York Street | Redlands, CA 92373 | USA
909-793-2853 x 4209 | mpaisner@esri.com<mailto:mpaisner@esri.com> | esri.com<http://esri.com/>

**Comment by joeferraro** [comment]
@mikepaisner makes good sense. logs are stored in your project's debug/logs directory

<img width="276" alt="changepasswordcontroller_cls_ _another_cool_project" src="https://cloud.githubusercontent.com/assets/54157/10199004/a43af584-676c-11e5-86f9-e9b307e6a340.png">

**Comment by joeferraro** [comment]
tracking enhancement here: https://github.com/joeferraro/MavensMate-app/issues/35

**Comment by mikepaisner** [comment]
Tracking multiline comments would be helpful, but a good old fashioned "find" feature within the Debug Log view within MavensMate-App would be great.

There is frequently useful information in the debug logs about validation rules firing, query results, etc. I've found using "find" to get to the right place and then seeing all the details is an effective way to debug issues.  Would love to be able to do that from within MavensMate-App.

**Comment by ralphcallaway** [comment]
@joeferraro @mikepaisner just throwing this out there, but isn't this something Sublime Text 3 (as well as other editors) already does great? seems like we'd be better off open these in the editor and focusing on UI stuff that would be difficult to do in the text editor

**Comment by joeferraro** [comment]
@ralphcallaway agreed, that should be the "workaround" for now -- to use sublime text to parse through logs using the find feature

**Comment by mikepaisner** [comment]
Agreed that you can do it Sublime Text.  Just saves a few mouse clicks to not have to open the log file in Sublime Text.

Also, since this information is read only (no editing) and MavensMate App is already conveniently listing the log files as they come in, it would be nice to be able to search the contents of them in MavensMate App.
