### ISSUE TITLE
No idea what's changed, now seeing: please ensure the MavensMate-app is running

### ISSUE THREAD

**Issue by fusion27** [joeferraro/MavensMate-SublimeText#676]
## Summary 

All of a sudden, no matter what I do w/ Maven's Mate, I'm seeing the following error message.  I'm racking my brain trying to figure out what changed.  I'd rather drink broken glass than use Eclipse again.

```
Operation: Handling requested operation...
Timestamp: Wed, 30 Sep 2015 13:07:58
   Result: [ERROR]: Request to the local MavensMate server failed. please ensure the MavensMate-app is running.
```

## Fixes I've tried

1. Moved the value for `mm_app_server_port` around to a few different ports
2. Restarted editor (Sublime Text 3)
3. Restarted machine (OSX 10.10.5)
4. Uninstalled/Resintalled MM plugin in Sublime
5. Removed directory from Project (with the motive of adding it back in), can't add back in or I get the dreaded error message below
6. Commented `mm_mavensmate_app_location` configuration (see below).
7. Shut media server down (runs on 32400).

#### `mm_mavensmate_app_location`

* In my `mavensmate.sublime-settings` (**MM > Settings  > User**) file, I point at the home of MavensMate.app with the `mm_mavensmate_app_location` property :point_right: `/Applications/MavensMate.app`.  I looked on my machine w/ Finder and the terminal (`sudo find / -name 'MavensMate.app'`), MavensMate.app is no where to be found.
>```python
> "mm_mavensmate_app_location" : {
>   "osx": "/Applications/MavensMate.app",
>   "windows": "C:\\Program Files\\MavensMate.exe",
>   "linux": ""
> },
> ```

* My colleague sitting across the room currently cruising on our SalesForce sandbox right now  doesn't even have `mm_mavensmate_app_location` in his **MM > Settings  > User** config.

#### Possible Update Collision?

* The only thing I can think that changed which possibly could've affected this is that the App Store pulled down an update to Microsoft's RDP client.  Maybe?

**Comment by joeferraro** [comment]
What version of MavensMate-app are you running? https://github.com/joeferraro/MavensMate-app/releases

**Comment by fusion27** [comment]
@joeferraro v5.0.0

![MM Version](https://trello-attachments.s3.amazonaws.com/55e78fb2a0c984e520a612ec/532x342/c8159eaf18eb9ccd8535f135e197214f/upload_9_30_2015_at_1_41_20_PM.png)

**Comment by joeferraro** [comment]
You need to install MavensMate-app (https://github.com/joeferraro/MavensMate-app/releases) ... see version 5 help for more info. it's likely you don't have it installed and running (and please be sure to set `mm_app_server_port` back to `57248` :+1: )

![screen shot 2015-09-30 at 1 44 58 pm](https://cloud.githubusercontent.com/assets/54157/10201334/7809b6c8-6779-11e5-8a33-5f0efc66114c.png)

**Comment by fusion27** [comment]
@joeferraro 

* Sublime Text Plugin v5.0.0 [screenshot](https://trello-attachments.s3.amazonaws.com/55e78fb2a0c984e520a612ec/532x342/c8159eaf18eb9ccd8535f135e197214f/upload_9_30_2015_at_1_41_20_PM.png)
* How to find `MavensMate-app` verison?

**Comment by fusion27** [comment]
@joeferraro 

I'm good, man that's exactly what it was.  I massively appreciate your quick response and help.  Take the rest of the day off and go have a :beer: on me!

**Comment by joeferraro** [comment]
no rest til Eclipse is dead, my friend.
