### ISSUE TITLE
VF Pages and Layouts unable to save/compile on Sandbox

### ISSUE THREAD

**Issue by hunsakerjeff** [joeferraro/MavensMate-SublimeText#677]
I have just updated to V5 of Maven hooked to Sublime Text 3.  I updated my projects, changed the various settings and started working.  I am able, to pull items from the server.  However, I am unable to save/compile back to the server.  This is a sandbox.  This is a project that worked fine in prior version. I also have the 006 Version of the Maven App loaded on the PC.  It is windows.

The message comes up that the Compiling operation  has started, there is a moving icon in the Results showing, but HOURS later it is still not saved.

Here is the results in the log:

==================> executing command: compile-metadata

2015-09-30T17:35:35.641Z - info: executeCommandForProject payload is: {"paths":["C:\\Projects\\Github\\MasterCard\\src\\pages\\AccountFlow.page"]}
2015-09-30T17:52:35.026Z - info: 

I have tried a couple projects hooked to a couple different sandboxes.  It is clearly  not working.  I

**Comment by hunsakerjeff** [comment]
UPDATE:  classes and Triggers work fine.  Pages cycle forever trying to save/compile, and Objects return the following message: 
  Result: [OPERATION FAILED]: Survey_Candidate__c: An object 'Survey_Candidate__c' of type CustomObject was named in package.xml, but was not found in zipped directory

However the file clearly exists in the src directory.  Looks to be packaging up somehow on the compile and then not finding the File.

**Comment by hunsakerjeff** [comment]
Further Update:  WHen I attempt to save Layouts, Objects etc, other than classes and Triggers.  The file is first emptied out, then i get the message shown above.  So the file cannot be found because it is getting CLEARED prior to trying to save.  What the heck is going on?  WHere would clearing the file be a valid option in any case?

**Comment by hunsakerjeff** [comment]
The log for one of the deletes is:

HANDLING COMPILE!
{'operation': 'compile-metadata', 'complete': True, 'id': 'e11a2110-67ac-11e5-a1b3-3d850e61ddeb', 'result': {'runTestsEnabled': 'false', 'lastModifiedDate': '2015-09-30T19:53:12.000Z', 'status': 'Failed', 'numberTestErrors': 0, 'numberComponentErrors': 1, 'ignoreWarnings': False, 'createdByName': 'Jeff Hunsaker', 'startDate': '2015-09-30T19:53:11.000Z', 'rollbackOnError': True, 'checkOnly': False, 'success': False, 'completedDate': '2015-09-30T19:53:12.000Z', 'numberComponentsDeployed': 0, 'id': '0AfM000000AXlEfKAL', 'numberTestsCompleted': 0, 'numberComponentsTotal': 1, 'numberTestsTotal': 0, 'createdDate': '2015-09-30T19:53:11.000Z', 'createdBy': '005F0000005E55e', 'details': {'runTestResult': {'numFailures': '0', 'totalTime': '0.0', 'numTestsRun': '0'}, 'componentFailures': {'changed': 'false', 'fullName': 'Account-Advisors Licensed Customer', 'deleted': 'false', 'fileName': 'unpackaged/package.xml', 'problemType': 'Error', 'problem': "An object 'Account-Advisors Licensed Customer' of type Layout was named in package.xml, but was not found in zipped directory", 'created': 'false', 'componentType': '', 'createdDate': '2015-09-30T19:53:12.000Z', 'success': 'false'}, 'componentSuccesses': {'changed': 'true', 'fullName': 'package.xml', 'deleted': 'false', 'fileName': 'unpackaged/package.xml', 'created': 'false', 'componentType': '', 'createdDate': '2015-09-30T19:53:12.000Z', 'success': 'true'}}, 'done': True}}

**Comment by hunsakerjeff** [comment]
Further Update:  For certain pages, if I try to save/compile (where a server check occurs) then the process just cycles indefinitely.  If i tell it to force compile, without check, then the Page is cleared out, and the attempted save returns an error that the file was indicated in the package.xml, but was not found in the zip.  (Same behavior I am seeing with every layout save/compile).

**Comment by joeferraro** [comment]
Thanks for the detailed reports, will have a look

**Comment by joeferraro** [comment]
@hunsakerjeff we've been unable to reproduce this on our side. can you provide clear steps to reproduce what you're seeing and any relevant logs? thanks

**Comment by hunsakerjeff** [comment]
The logs are large, you want me to just attach here?  Or do you have a different way to receive them


Jeff Hunsaker
Consultant, Salesforce.com Applications

MasterCard | Operations & Technologies
2200 MasterCard Blvd. | O'Fallon, MO  63368-7263

tel 636-722-4802 | fax 636-722-3550
jeff_hunsaker@mastercard.com<mailto:angela_medina@mastercard.com>
[cid:image002.gif@01CF4DB7.27BE4A90]<www.mastercard.com>

Please think of the environment before printing this email.

**Comment by joeferraro** [comment]
https://gist.github.com/ is fine

**Comment by hunsakerjeff** [comment]
I have pasted several snippits to help.  We are releasing next Friday, after which I can try the upgrade again.  Maybe we wait until then to test better when we can exercise specific item.  If you don’t see anything in the logs I provided.

Jeff Hunsaker
Consultant, Salesforce.com Applications

MasterCard | Operations & Technologies
2200 MasterCard Blvd. | O'Fallon, MO  63368-7263

tel 636-722-4802 | fax 636-722-3550
jeff_hunsaker@mastercard.com<mailto:angela_medina@mastercard.com>
[cid:image002.gif@01CF4DB7.27BE4A90]<www.mastercard.com>

Please think of the environment before printing this email.
