### ISSUE TITLE
Unable to create new project or Update project after Updated the Sublime text Mavens Mate plugin

### ISSUE THREAD

**Issue by archita6** [joeferraro/MavensMate-SublimeText#678]
I am not able to create a project or refresh existing project after i have updated the Mavens Mate plugin in sublime text. I have installed the mavensmate-app and have updated the mm_workspace in the Global Settings . While creating the project get the following error
![image](https://cloud.githubusercontent.com/assets/6512067/10205538/94471784-6776-11e5-883d-3167e9010c4c.png)

**Comment by joeferraro** [comment]
what version of Windows do you have? Is `c:\windows\system32\cscript.exe` available on your system?

**Comment by archita6** [comment]
I am using windows 7 . Yes  c:\windows\system32\cscript.exe is available in my system

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-app/issues/43
