### ISSUE TITLE
Is it possible to go back to the 4. Release as 5.0 is not working for us

### ISSUE THREAD

**Issue by hunsakerjeff** [joeferraro/MavensMate-SublimeText#679]
How can i get the older version of MavensMate in Sublime Text.  I have a zip of the old directory, but  it keeps overwriting with the new version.  The new version is not working and I have a production deployment coming up that i NEED to be able to operate.

Thanks.

**Comment by joeferraro** [comment]
1. Package Control: remove package, select MavensMate
2. Install the zipped directory into the ST packages path and ensure the directory is called "MavensMate"
3. Have a drink of water

**Comment by hunsakerjeff** [comment]
Thank you, that worked.  Once our release is out, I can go back to the new version and give more details on the strange items we were seeing.

Jeff Hunsaker
Consultant, Salesforce.com Applications

MasterCard | Operations & Technologies
2200 MasterCard Blvd. | O'Fallon, MO  63368-7263

tel 636-722-4802 | fax 636-722-3550
jeff_hunsaker@mastercard.com<mailto:angela_medina@mastercard.com>
[cid:image002.gif@01CF4DB7.27BE4A90]<www.mastercard.com>

Please think of the environment before printing this email.

**Comment by joeferraro** [comment]
cheers @hunsakerjeff :+1:
