### ISSUE TITLE
tunneling socket could not be established, cause=write EPROTO

### ISSUE THREAD

**Issue by riadhmankai** [joeferraro/MavensMate-SublimeText#680]
Hi,

I managed to setup and run the new Mavensmate (version 5) on my home PC (Ubuntu) without any trouble, but on the corporate PC (Windows 7 64 bits) I get this error when trying to create a project, compile or refresh from salesforce: tunneling socket could not be established, cause=write EPROTO

I'm behind a proxy and I did the required setup in MavensMate-App global settings.

Thanks!

**Comment by joeferraro** [comment]
Apologies for the inconvenience, you can downgrade to v4 while I investigate: https://github.com/joeferraro/MavensMate-SublimeText#install

**Comment by joeferraro** [comment]
I believe this has been resolved in mm-app 0.0.8. closing for now, please re-open if you're still experiencing the issue
