### ISSUE TITLE
Unable to revert back to MM v4

### ISSUE THREAD

**Issue by dkurylo** [joeferraro/MavensMate-SublimeText#681]
Hello! Yesterday we were updated to MM v5. But not all features are working as they should, and we tried to revert back to v4, since coding is our loaf of bread and we don't have the possibility to spend time playing around with features that don't work or are unstable, -- but MM v4 was not available.
Is there a way to revert back to v4 at least until the more or less stable version of v5 is available?

**Comment by joeferraro** [comment]
here you go: https://github.com/joeferraro/MavensMate-SublimeText#install
