### ISSUE TITLE
Can't connect to localhost when HTTP_PROXY is set

### ISSUE THREAD

**Issue by leboff** [joeferraro/MavensMate-SublimeText#682]
Windows 7 64-bit

I have HTTP_PROXY and HTTPS_PROXY set as environment variables, so when SublimeText tries to open localhost:56248 it cannot connect to the MavensMate app. Removing this variables causes ST to work as expected.

**Comment by joeferraro** [comment]
@ralphcallaway any chance you guys could help me debug this issue? I thought Python's urllib handled all the proxy stuff ... looks like we may need to bake in some proxy goodness for calls like this to the local server? https://github.com/joeferraro/MavensMate-SublimeText/blob/master/lib/adapter.py#L24

**Comment by joeferraro** [comment]
tracking other proxy issues here: https://github.com/joeferraro/MavensMate-app/issues/24#issuecomment-144939874
