### ISSUE TITLE
mm_hide_panel_on_success not working upon successful resource bundle deployment

### ISSUE THREAD

**Issue by sturev** [joeferraro/MavensMate-SublimeText#685]
the default setting of true isn't working...  The panel is visible on load w/Happy Coding :) and never goes away, even after successful compiles.
MM ver 5, Win10

**Comment by joeferraro** [comment]
please provide specific steps to reproduce and sublime text console logs, if possible. thanks!

**Comment by sturev** [comment]
this doesn't appear to be an issue after updating to 5.0.4

**Comment by sturev** [comment]
so it turns out the panel hides when I compile a class but it doesn't hide after I deploy a static resource. do you still want logs or can you reproduce?

**Comment by sturev** [comment]
Joe, there are two other cases where the panel doesn't hide; on opening Sublime and also when refreshing one or more metadata types from the server.
