### ISSUE TITLE
Error: Deploying resource bundle...

### ISSUE THREAD

**Issue by MartinProkop** [joeferraro/MavensMate-SublimeText#687]
Hi, I like MavensMate, but have problems.

When I have resource bundle around 4MB large, deploying process is sometimes longer than 10 minutes. Sometimes ended with error message: "[ERROR]: Polling time out." 
I discovered that, when during deploing I save visualpage, deploing process finish faster.

Thanks,
Martin Prokop

**Comment by joeferraro** [comment]
Have you checked your deployment status in your org? Sometimes the metadata API is super slow.

**Comment by MartinProkop** [comment]
Yes, I know, but before update MavensMate to new version was deployment significantly faster.

**Comment by joeferraro** [comment]
OK, there have been several issues across the MavensMate projects complaining of performance from folks running v4 and v5 ... obviously given our tool integrates with a server outside of our control, it can be difficult to determine whether it's a salesforce.com server issue or a mavensmate issue. If you can provide evidence that this is something specific to the v5 source code, please post any relevant logs and we'll be sure to have a look. Until then, I'll close this issue, as there's nothing actionable here at the moment.

**Comment by vukers** [comment]
I have been receiving the same error. Is there an option anywhere to increase the duration before timing out? I'm not sure if this is on MavensMate end or SF.

I've tried changing the MavensMate setting: "Timeout, in seconds (mm_timeout)" to 6,000 but the same error occurs.
