### ISSUE TITLE
Linux: SublimeText3 cannot open MavensMate

### ISSUE THREAD

**Issue by hugogmg** [joeferraro/MavensMate-SublimeText#688]
Hello.
I have the new API.

*Workflow that works:*
Manually open MM App. Then open Sublime

*Workflow that dosen't work:*
* Configure SublimeText
   * MavensMate Menu --> Settings --> User Plugin Settings
   * Set "mm_start_mavensmate_app" to true
   * Set path of linux to MM app

```javascript
//set to true if you would like to automatically start MavensMate-app when Sublime Text opens
	"mm_start_mavensmate_app" : true,

// set to full path of MavensMate-app (MavensMate.app on OSX, MavensMate.exe on Windows, etc.)
	"mm_mavensmate_app_location" : {
		"osx": "/Applications/MavensMate.app",
		"windows": "C:\\Program Files\\MavensMate.exe",
		"linux": "/home/hugogmg/MMApp/MavensMate"
	},
```

I've configured all to make possible to open sublime directly and then automaticly open MM.

This didn't work.
Any idea?

Thanks

**Comment by MaggiePlusPlus** [comment]
I have the same issue on Windows 8.1; MavensMate for Sublime Text v5.0.4 

"C:\Program Files\MavensMate\MavensMate.exe" is the correct path.

My user settings are

`
	//set to true if you would like to automatically start MavensMate-app when Sublime Text opens
	"mm_start_mavensmate_app" : true,

	// set to full path of MavensMate-app (MavensMate.app on OSX, MavensMate.exe on Windows, etc.)
	"mm_mavensmate_app_location" : {
		"osx": "/Applications/MavensMate.app",
		"windows": "C:\\Program Files\\MavensMate\\MavensMate.exe",
		"linux": ""
	},`

**Comment by aleramesh** [comment]
```
	//set to true if you would like to automatically start MavensMate-app when Sublime Text opens
	"mm_start_mavensmate_app" : true,
```

The above setting is not working on linux because of the following method from the [file](https://github.com/joeferraro/MavensMate-SublimeText/blob/master/util.py):

```
[def start_mavensmate_app(printer):
    try:
        settings = sublime.load_settings('mavensmate.sublime-settings')
        friendly_platform_key = get_friendly_platform_key()
        mavensmate_app_location_setting = settings.get('mm_mavensmate_app_location')
        if friendly_platform_key in mavensmate_app_location_setting:
            mavensmate_app_location = mavensmate_app_location_setting[friendly_platform_key]
            debug(mavensmate_app_location)
            if os.path.exists(mavensmate_app_location):
                if friendly_platform_key == 'windows':
                    # subprocess.Popen('"{0}"'.format(mavensmate_app_location), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
                    # TODO: this causes multiple mavensmate-app instances to open
                    pass
                elif friendly_platform_key == 'linux':
                    pass #TODO
                elif friendly_platform_key == 'osx':
                    process = subprocess.Popen(["open", "-a", mavensmate_app_location, "--hide"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                    stdout, stderr = process.communicate()
                    if stderr != None:
                        printer.show()
                        message = '[ERROR]: Could not open MavensMate-app. '+stderr.decode('utf-8')
                        printer.write('\n'+message+'\n')
            else:
                printer.show()
                message = '[ERROR]: Could not open MavensMate-app. mm_mavensmate_app_location path does not exist, please check user plugin settings'
                printer.write('\n'+message+'\n')
    except Exception as e:
        debug('could not open mavensmate-app')
        debug(e)](url)

```

As we can see here, if it is linux, it is not doing anything. This definitely needs a fix for linux environment.

**Comment by aleramesh** [comment]
@joeferraro , I see that it is still not implemented for linux OS but you closed this issue that means no plans to implement for start mavensmate on start up for linux?

**Comment by joeferraro** [comment]
We've moved MavensMate issue tracking to our [central issues repository](https://github.com/joeferraro/MavensMate/issues) because there are more than 5 Github MavensMate repositories and it's hard for this small team of volunteers to keep track of the issues across all of those projects. There's also been a significant amount of development in the last 6 months and it's hard for us to know which bugs were addressed and which ones remain valid (some are more than 3 years old). If you believe your issue is still valid and unresolved, please feel free to create a new issue in the central repository and reference the original ticket in your report.  Thank you for your understanding!

-Joe

**Comment by aleramesh** [comment]
Thanks @joeferraro 

We already have a similar issue opened on the central repository and I added my comments there. Thanks!

**Comment by joeferraro** [comment]
cheers @aleramesh
