### ISSUE TITLE
Windows not auto-starting MavensMate App

### ISSUE THREAD

**Issue by ScriptMonkey00** [joeferraro/MavensMate-SublimeText#689]
I just tried to enable the auto starting function in the plugin settings to start mavensmate.  According to the log, I got a "No connection could be made because the target machine actively refused it" error, which sounds like a web callout error.

Here's the full error (and the path is correct):
[MAVENSMATE]: =============> Starting MavensMate for Sublime Text
[MAVENSMATE]: C:\Program Files\MavensMate\MavensMate.exe
[MAVENSMATE]: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

**Comment by ScriptMonkey00** [comment]
Sorry, seems I forgot it would parse the lessthan/greaterthan.  Here's the full error:
[MAVENSMATE]: =============> Starting MavensMate for Sublime Text
[MAVENSMATE]: C:\Program Files\MavensMate\MavensMate.exe
[MAVENSMATE]: &lt;urlopen error [WinError 10061] No connection could be made because the target machine actively refused it&gt;

**Comment by garyspencer** [comment]
Same issue here.  I also tried to add ../MavensMate/ to my path and just give the setting 'mavensmate' to no avail.  I am running ST3 as admin.

**Comment by force2b** [comment]
Same issue here; though I really thought this worked in an earlier beta version. Might be mixing that up with Atom though.

Windows 7 32-bit.

**Comment by joeferraro** [comment]
I had to pull it to look for a better fix because it wasn't properly detecting whether mm-app was already running, therefore launching an additional mm-app process, which was not desirable.
