### ISSUE TITLE
Validate/Deploy:  System keychain service not supported

### ISSUE THREAD

**Issue by techman97** [joeferraro/MavensMate-SublimeText#690]
I'm running the new x64 latest (v0.0.8) of MM and got my v4 projects running - I can pull down metadata, save files, and run tests successfully.

I cannot validate or deploy any project (not even a newly-created one).  I have the "Use keyring (mm_use_keyring)" setting OFF (multiple developers on the same project) and I get the following errors:

Validate Only - System keychain service not supported
Deploy - System keychain service not supported

![image](https://cloud.githubusercontent.com/assets/2081930/10251005/bb3da1fe-68f3-11e5-9838-8b83d7045deb.png)

I have to resort to <shudder> Change Sets for my projects right now - help?

**Comment by joeferraro** [comment]
OK, so to boil it down, authentication is working everywhere but deploys?

**Comment by joeferraro** [comment]
Also are you windows, linux, or osx?

**Comment by techman97** [comment]
Yes - deployment is the only problem.  Everything else is peachy.

Windows x64 - specifically Windows 10 Pro.

**Comment by joeferraro** [comment]
> Everything else is peachy.

:tada: 

You don't know how happy I am to hear this ... I've only heard nightmare stories re: performance on Windows 10 Pro ... https://github.com/joeferraro/MavensMate-SublimeText/issues/686

Will have a look at the deploy issue

**Comment by techman97** [comment]
Sounds good - if you want a GoToMeeting to look around or anything, just let me know.

**Comment by techman97** [comment]
Just tried the same deal out on my 2nd Windows10 Pro x64 workstation - same issues.

**Comment by joeferraro** [comment]
- OK, a few questions: is this a new project (created after v5 was released)?
- You said you're NOT using keyring, right (your global settings has this value unchecked)?
- If you're not using keyring, your org connection passwords will show up in in your .org_connections file. Can you confirm they're there?
- Is this happening with a certain type of org, sandbox, developer, etc?

**Comment by techman97** [comment]
NEWS!

- Both new and "migrated" projects yield the same results
- NOT using keyring, correct.  Password stored in the project .settings
- **the .org_connections password was NOT appearing before I just updated to v0.0.8 - but I just removed the org connection and re-added it, now it appears**
- happening with all org types

I just ran a validate and deployment - all is working now!

**Comment by joeferraro** [comment]
ok cool, thanks for the update. closing for now. feel free to re-open if you encounter it again
