### ISSUE TITLE
Unable to parse compilation response

### ISSUE THREAD

**Issue by lamorak24** [joeferraro/MavensMate-SublimeText#691]
When I try saving my project I receive the following error.  
```
Result: [OPERATION FAILED]: Whoops, unable to parse the response.
[RESPONSE FROM MAVENSMATE]: {
    "id": "ff410d10-6933-11e5-8191-f5c91d81c734", 
    "result": {
        "rollbackOnError": false, 
        "createdDate": "", 
        "numberComponentsTotal": 0, 
        "lastModifiedDate": "", 
        "done": false, 
        "numberTestsTotal": 0, 
        "details": {
            "runTestResult": {
                "numTestsRun": "0", 
                "totalTime": "0.0", 
                "numFailures": "0"
            }, 
            "componentFailures": [
                {
                    "attributes": {
                        "type": "ContainerAsyncRequest", 
                        "url": "/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drg00000027TEEAA2"
                    }, 
                    "Id": "1drg00000027TEEAA2", 
                    "IsCheckOnly": false, 
                    "MetadataContainerMemberId": null, 
                    "State": "Failed", 
                    "ErrorMsg": null, 
                    "MetadataContainerId": "1dcg0000000TxlnAAC", 
                    "DeployDetails": {
                        "componentFailures": [
                            {
                                "createdDate": "2015-10-02T18:33:03.090+0000", 
                                "warning": false, 
                                "fullName": "HouseholdOverview", 
                                "columnNumber": null, 
                                "deleted": false, 
                                "problemType": "Error", 
                                "forPackageManifestFile": false, 
                                "id": "066g00000004y21AAA", 
                                "fileName": "pages/HouseholdOverview.page", 
                                "problem": "Incorrect parameter type for operator '+'. Expected Number, Date, DateTime, received Object", 
                                "success": false, 
                                "componentType": "ApexPage", 
                                "changed": false, 
                                "requiresProductionTestRun": false, 
                                "created": false, 
                                "lineNumber": null, 
                                "knownPackagingProblem": false
                            }
                        ], 
                        "runTestResult": null, 
                        "allComponentMessages": [
                            {
                                "createdDate": "2015-10-02T18:33:03.090+0000", 
                                "warning": false, 
                                "fullName": "HouseholdOverview", 
                                "columnNumber": null, 
                                "deleted": false, 
                                "problemType": "Error", 
                                "forPackageManifestFile": false, 
                                "id": "066g00000004y21AAA", 
                                "fileName": "pages/HouseholdOverview.page", 
                                "problem": "Incorrect parameter type for operator '+'. Expected Number, Date, DateTime, received Object", 
                                "success": false, 
                                "componentType": "ApexPage", 
                                "changed": false, 
                                "requiresProductionTestRun": false, 
                                "created": false, 
                                "lineNumber": null, 
                                "knownPackagingProblem": false
                            }
                        ], 
                        "componentSuccesses": []
                    }
                }
            ], 
            "componentSuccesses": []
        }, 
        "success": false, 
        "numberComponentsDeployed": 0, 
        "checkOnly": false, 
        "numberTestErrors": 0, 
        "id": "", 
        "numberTestsCompleted": 0, 
        "ignoreWarnings": false, 
        "completedDate": "", 
        "startDate": "", 
        "numberComponentErrors": 1, 
        "createdByName": "", 
        "runTestsEnabled": "false", 
        "createdBy": "", 
        "status": ""
    }, 
    "operation": "compile-metadata", 
    "complete": true
}

<http.client.HTTPResponse object at 0x00000000043B6C18>
{'id': 'ff410d10-6933-11e5-8191-f5c91d81c734', 'result': {'rollbackOnError': False, 'createdDate': '', 'numberComponentsTotal': 0, 'lastModifiedDate': '', 'done': False, 'numberTestsTotal': 0, 'details': {'runTestResult': {'numTestsRun': '0', 'totalTime': '0.0', 'numFailures': '0'}, 'componentFailures': [{'attributes': {'type': 'ContainerAsyncRequest', 'url': '/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drg00000027TEEAA2'}, 'Id': '1drg00000027TEEAA2', 'IsCheckOnly': False, 'MetadataContainerMemberId': None, 'State': 'Failed', 'ErrorMsg': None, 'MetadataContainerId': '1dcg0000000TxlnAAC', 'DeployDetails': {'componentFailures': [{'createdDate': '2015-10-02T18:33:03.090+0000', 'warning': False, 'fullName': 'HouseholdOverview', 'columnNumber': None, 'deleted': False, 'problemType': 'Error', 'forPackageManifestFile': False, 'id': '066g00000004y21AAA', 'fileName': 'pages/HouseholdOverview.page', 'problem': "Incorrect parameter type for operator '+'. Expected Number, Date, DateTime, received Object", 'success': False, 'componentType': 'ApexPage', 'changed': False, 'requiresProductionTestRun': False, 'created': False, 'lineNumber': None, 'knownPackagingProblem': False}], 'runTestResult': None, 'allComponentMessages': [{'createdDate': '2015-10-02T18:33:03.090+0000', 'warning': False, 'fullName': 'HouseholdOverview', 'columnNumber': None, 'deleted': False, 'problemType': 'Error', 'forPackageManifestFile': False, 'id': '066g00000004y21AAA', 'fileName': 'pages/HouseholdOverview.page', 'problem': "Incorrect parameter type for operator '+'. Expected Number, Date, DateTime, received Object", 'success': False, 'componentType': 'ApexPage', 'changed': False, 'requiresProductionTestRun': False, 'created': False, 'lineNumber': None, 'knownPackagingProblem': False}], 'componentSuccesses': []}}], 'componentSuccesses': []}, 'success': False, 'numberComponentsDeployed': 0, 'checkOnly': False, 'numberTestErrors': 0, 'id': '', 'numberTestsCompleted': 0, 'ignoreWarnings': False, 'completedDate': '', 'startDate': '', 'numberComponentErrors': 1, 'createdByName': '', 'runTestsEnabled': 'false', 'createdBy': '', 'status': ''}, 'operation': 'compile-metadata', 'complete': True}
HANDLING COMPILE!
{'id': 'ff410d10-6933-11e5-8191-f5c91d81c734', 'result': {'rollbackOnError': False, 'createdDate': '', 'numberComponentsTotal': 0, 'lastModifiedDate': '', 'done': False, 'numberTestsTotal': 0, 'details': {'runTestResult': {'numTestsRun': '0', 'totalTime': '0.0', 'numFailures': '0'}, 'componentFailures': [{'attributes': {'type': 'ContainerAsyncRequest', 'url': '/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1drg00000027TEEAA2'}, 'Id': '1drg00000027TEEAA2', 'IsCheckOnly': False, 'MetadataContainerMemberId': None, 'State': 'Failed', 'ErrorMsg': None, 'MetadataContainerId': '1dcg0000000TxlnAAC', 'DeployDetails': {'componentFailures': [{'createdDate': '2015-10-02T18:33:03.090+0000', 'warning': False, 'fullName': 'HouseholdOverview', 'columnNumber': None, 'deleted': False, 'problemType': 'Error', 'forPackageManifestFile': False, 'id': '066g00000004y21AAA', 'fileName': 'pages/HouseholdOverview.page', 'problem': "Incorrect parameter type for operator '+'. Expected Number, Date, DateTime, received Object", 'success': False, 'componentType': 'ApexPage', 'changed': False, 'requiresProductionTestRun': False, 'created': False, 'lineNumber': None, 'knownPackagingProblem': False}], 'runTestResult': None, 'allComponentMessages': [{'createdDate': '2015-10-02T18:33:03.090+0000', 'warning': False, 'fullName': 'HouseholdOverview', 'columnNumber': None, 'deleted': False, 'problemType': 'Error', 'forPackageManifestFile': False, 'id': '066g00000004y21AAA', 'fileName': 'pages/HouseholdOverview.page', 'problem': "Incorrect parameter type for operator '+'. Expected Number, Date, DateTime, received Object", 'success': False, 'componentType': 'ApexPage', 'changed': False, 'requiresProductionTestRun': False, 'created': False, 'lineNumber': None, 'knownPackagingProblem': False}], 'componentSuccesses': []}}], 'componentSuccesses': []}, 'success': False, 'numberComponentsDeployed': 0, 'checkOnly': False, 'numberTestErrors': 0, 'id': '', 'numberTestsCompleted': 0, 'ignoreWarnings': False, 'completedDate': '', 'startDate': '', 'numberComponentErrors': 1, 'createdByName': '', 'runTestsEnabled': 'false', 'createdBy': '', 'status': ''}, 'operation': 'compile-metadata', 'complete': True}
{'createdDate': '2015-10-02T18:33:03.090+0000', 'warning': False, 'fullName': 'HouseholdOverview', 'columnNumber': None, 'deleted': False, 'problemType': 'Error', 'forPackageManifestFile': False, 'id': '066g00000004y21AAA', 'fileName': 'pages/HouseholdOverview.page', 'problem': "Incorrect parameter type for operator '+'. Expected Number, Date, DateTime, received Object", 'success': False, 'componentType': 'ApexPage', 'changed': False, 'requiresProductionTestRun': False, 'created': False, 'lineNumber': None, 'knownPackagingProblem': False}
int() argument must be a string or a number, not 'NoneType'
None
<class 'dict'>
int() argument must be a string or a number, not 'NoneType'
None
```

**Comment by aannenko** [comment]
Well. My problem is pretty much the same...

[RESPONSE FROM MAVENSMATE]: {
    "complete": true, 
    "id": "bc5de350-6b55-11e5-bf2d-2f74c3b8bbd9", 
    "operation": "compile-metadata", 
    "result": {
        "status": "", 
        "numberComponentsDeployed": 0, 
        "success": false, 
        "rollbackOnError": false, 
        "ignoreWarnings": false, 
        "numberComponentErrors": 1, 
        "numberTestsCompleted": 0, 
        "completedDate": "", 
        "createdDate": "", 
        "startDate": "", 
        "numberTestErrors": 0, 
        "numberComponentsTotal": 0, 
        "numberTestsTotal": 0, 
        "id": "", 
        "checkOnly": false, 
        "done": false, 
        "lastModifiedDate": "", 
        "createdByName": "", 
        "runTestsEnabled": "false", 
        "createdBy": "", 
        "details": {
            "componentSuccesses": [], 
            "runTestResult": {
                "numFailures": "0", 
                "totalTime": "0.0", 
                "numTestsRun": "0"
            }, 
            "componentFailures": [
                {
                    "MetadataContainerMemberId": null, 
                    "ErrorMsg": null, 
                    "MetadataContainerId": "1dcc0000000MFxgAAG", 
                    "attributes": {
                        "type": "ContainerAsyncRequest", 
                        "url": "/services/data/v33.0/tooling/sobjects/ContainerAsyncRequest/1drc0000001MlCvAAK"
                    }, 
                    "IsCheckOnly": false, 
                    "State": "Failed", 
                    "DeployDetails": {
                        "componentSuccesses": [], 
                        "componentFailures": [
                            {
                                "forPackageManifestFile": false, 
                                "requiresProductionTestRun": false, 
                                "success": false, 
                                "lineNumber": 1, 
                                "columnNumber": -1, 
                                "created": false, 
                                "componentType": "ApexPage", 
                                "fullName": "CustomerStatesAccountNew", 
                                "fileName": "CustomerStatesAccountNew", 
                                "knownPackagingProblem": false, 
                                "id": "066c00000002KMoAAM", 
                                "changed": false, 
                                "problemType": null, 
                                "createdDate": "2015-10-05T11:39:29.107+0000", 
                                "deleted": false, 
                                "problem": null, 
                                "warning": false
                            }
                        ], 
                        "allComponentMessages": [
                            {
                                "forPackageManifestFile": false, 
                                "requiresProductionTestRun": false, 
                                "success": false, 
                                "lineNumber": 1, 
                                "columnNumber": -1, 
                                "created": false, 
                                "componentType": "ApexPage", 
                                "fullName": "CustomerStatesAccountNew", 
                                "fileName": "CustomerStatesAccountNew", 
                                "knownPackagingProblem": false, 
                                "id": "066c00000002KMoAAM", 
                                "changed": false, 
                                "problemType": null, 
                                "createdDate": "2015-10-05T11:39:29.107+0000", 
                                "deleted": false, 
                                "problem": null, 
                                "warning": false
                            }
                        ], 
                        "runTestResult": null
                    }, 
                    "Id": "1drc0000001MlCvAAK"
                }
            ]
        }
    }
}

**Comment by skwilder** [comment]
+1 I am getting the same error and it doesn't seem to be generating a log for this error. Or my logging is broke as well.

**Comment by joeferraro** [comment]
Hey guys, will need some more information to reproduce this. Can you please include the information requested in the contributing guide? https://github.com/joeferraro/MavensMate-SublimeText/blob/master/CONTRIBUTING.md

It would be helpful if you could generate logs where appropriate and answer the following questions:

- what kind of org is this: developer, sandbox, production?
- does this happen in every project?
- does this happen for every compile operation?
- does this occur only with certain types of metadata?
- does this occur only in certain orgs?

**Comment by skwilder** [comment]
what kind of org is this: developer, sandbox, production?

sandbox / production

does this happen in every project?

I have tested two projects now and it seems to be happening in both

does this happen for every compile operation?

It's happening for VisualForce pages and Apex Classes. I am able to send up a resource bundle properly.

does this occur only with certain types of metadata?

It's happening for VisualForce pages and Apex Classes. I am able to send up a resource bundle properly.

does this occur only in certain orgs?

No, it's happening in multiple orgs.  


I have attempting to turn on logging but my logs aren't showing up.


![screen shot 2015-10-05 at 11 36 58 am](https://cloud.githubusercontent.com/assets/1234082/10287773/0eba9de8-6b63-11e5-8204-283cfbf4f6f6.png)
![screen shot 2015-10-05 at 11 37 40 am](https://cloud.githubusercontent.com/assets/1234082/10287772/0eb81bc2-6b63-11e5-8b87-e5853dba2c7d.png)
![screen shot 2015-10-05 at 11 38 08 am](https://cloud.githubusercontent.com/assets/1234082/10287771/0eb7f818-6b63-11e5-87a9-3eb50d450d69.png)

**Comment by skwilder** [comment]
I have restarted my machine and it seems to have been fixed. The restart was because I updated my OS to El Capitain.
