### ISSUE TITLE
Compiling in sublime does not highlight line that produces error and does not give line number either

### ISSUE THREAD

**Issue by veenaheragu** [joeferraro/MavensMate-SublimeText#692]
After updating to mavensmate app, when I compile in sublime, the error message looks like this:

Operation: Compiling: C:\Users\V. Heragu\Documents\MavensMate\mmdevx\src\classes\AutoDialHelperTest.cls
Timestamp: Fri, 02 Oct 2015 16:22:24
   Result: [OPERATION FAILED]: AutoDialHelperTest: Invalid field AccpountId for SObject Contact

There is no line number for the error and the line does not get highlighted in the file

Veena

**Comment by joeferraro** [comment]
The Salesforce API does not always return line numbers. Please generate logs by setting up logging in mm-app's global settings and pasting them here. Thanks

**Comment by veenaheragu** [comment]
Sorry, I found the issue I had compiling set to metadata api instead of tooling api.

Please close this one
Thanks
Veena

**Comment by ctinghino** [comment]
Hi, I found the same problem with Mavensmate and Sublime text.
Under **View > Show Console** I can view the following error as well as with line number:
`'componentFailures': {'created': 'false', 'columnNumber': '43', 'success': 'false', 'lineNumber': '66',`
but the line number is not present in Mavensmate panel, that shows only the _problem_ message
