### ISSUE TITLE
MM api not working in v5?

### ISSUE THREAD

**Issue by diligent176** [joeferraro/MavensMate-SublimeText#694]
We have developed a customized version of force.com migration tool that invokes the MavensMate API commands for certain things.  Since MM upgraded to 5.x, the API calls are no longer working.
 For example mm.exe -o new_project

I would've thought MM API should remain backwards compatible, but it appears to not be the case.
Has anyone been testing the API in 5.x release?  I rolled back to v4.0.5 (thank for the instructions!) and now all is well again.

I apologize for the lack of detail here, but the API commands seem to be not working.  Can anyone corroborate this?  At best, the API call will invoke mm.exe and it sits there doing nothing in Task Manager.

**Comment by joeferraro** [comment]
Hi @diligent176 thanks for the bug report. In keeping with semantic versioning, v5 is a major/breaking release. In v5, the `mm` API is no longer supported (https://github.com/joeferraro/mm). I've rewritten the MavensMate core in node and the CLI can now be used by installing the `mavensmate` npm package (`npm install mavensmate -g`). If you let me know the types of commands you're looking to run, I can help you with the equivalents in `mavensmate`.

For example, to create a new project:

```
mavensmate new-project <<< '{ "name" : "myproject", "workspace" : "/path/to/workspace", "username" : "foo@bar.com", "password" : "foo", package: { "ApexClass" : "*" } }'
```
