### ISSUE TITLE
html encoding on server responces

### ISSUE THREAD

**Issue by CSTufts** [joeferraro/MavensMate-SublimeText#697]
sorry if this is a dupe i didn't see it anywhere

I saw this response on a save attempt, the error response doesn't seem to be parsing the json/html properly...

getting &gt; and &lt; instead of < >

Result: [OPERATION FAILED]: ClassName: Method does not exist or incorrect signature: Class.Method(Set&lt;Id&gt;, String, String, List&lt;String&gt;, List&lt;String&gt;, List&lt;String&gt;, List&lt;String&gt;, Datetime) (Line: 48, Column: -1)

**Comment by harshal-gajare** [comment]
I am getting a similar issue on the errors being returned back int eh console. 

  Result: [OPERATION FAILED]: CLASS: Illegal assignment from List&lt;Case__c&gt; to List&lt;Case&gt; (Line: 27, Column: -1)
