### ISSUE TITLE
Not being able to save .labels, .object etc.

### ISSUE THREAD

**Issue by DzmitryKandora** [joeferraro/MavensMate-SublimeText#698]
Hey Joe! 

At first want to thank you for what you're doing, you are the man!
Now, I have a question. After updating and having the MavensMate app v0.0.9 installed, I cannot save many formats, custom labels as an example. So, when trying to save the CustomLabels.labels in sublime, I have the following error: 

Result: [OPERATION FAILED]: CustomLabels: An object 'CustomLabels' of type CustomLabels was named in package.xml, but was not found in zipped directory
At the same moment all code in the screen gets totally removed - I see a blank screen.  
Having the same error on windows 7 and osx 10.10.5 . 
Please give me a hint what could be causing this? I was looking for a solution during the whole day, including answered by you earlier, but with no result.

**Comment by joeferraro** [comment]
@DzmitryKandora thanks for the bug report. I'm unable to reproduce this, can you do me a favor and generate logs and paste them here? You can configure them in mm-app settings.

**Comment by DzmitryKandora** [comment]
Hey hey

No, I'm sure you aren't able to reproduce. Neither any of my team. 
I do want to help you to debug this, but I'm not sure I know how. Could you tell me how or reference any of your posts? And what is the "zipped directory" the error message complains about? 

One more thing, is there any way to reset to default settings? Also my colleague told me that he has set some settings in MavensMate and it was still not working (some other issue, not important), and when we returned from lunch, all started working as expected, so could it be that settings are not applied right away? 

Thanks!

**Comment by DzmitryKandora** [comment]
@joeferraro 
I have an update. I managed to solve this problem by removing Sublime Text 3 and Mavensmate, existing settings as well and installing all of them again using standard paths and folders without changing.
