### ISSUE TITLE
Create Apex class error: Dependent class is invalid and needs recompilation: sObject type 'RecordType' is not supported.

### ISSUE THREAD

**Issue by veenaheragu** [joeferraro/MavensMate-SublimeText#700]
we have Salesforce unlimited edition.  When I try to create an apex class using my own template, I get the error : 

Dependent class is invalid and needs recompilation: sObject type 'RecordType' is not supported.

Veena

**Comment by joeferraro** [comment]
Perhaps your template is invalid. Can you paste it here?

**Comment by veenaheragu** [comment]
I had been using the same template before upgrading to the mavensmate app.

This is the complete error message :

Dependent class is invalid and needs recompilation: BatchJobHelper: line 18, column 3: Dependent class is invalid and needs recompilation: utils: line 248, column 41: sObject type 'RecordType' is not supported.

This is line 248 of utils:

List<RecordType> oppRecsTypes = [Select Id, Name from RecordType where SobjectType = 'Solar_SA__c'];



And this is my template:


global class {{ api_name }} implements Database.Batchable<SObject>, Database.Stateful {

    global Integer numSuccess = 0;
    global String dmlFailures = null;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        try
        {
            // Start logging messages for this run of the batch in Batch_Job_Message__c object
            // Instead of system.debug, use BatchJobHelper.AddMessage(Caller, Message)
            // it will dd message to  Batch_Job_Message__c object AND do system.debug
            BatchJobHelper.StartMessages('{{ api_name }}');

            String query = '';

            if(Test.isRunningTest())
                query += ' limit 200';

            BatchJobHelper.AddMessage('{{ api_name }}', 'query = ' + query, true);

            return Database.getQueryLocator(query);
        }
        catch(Exception ex)
        {
            BatchJobHelper.exceptionHandler('{{ api_name }}', ex);
            return Database.getQueryLocator('Select Id from {{ sobj }} where Id = null');
        }

    }
    
    global void execute(Database.BatchableContext bc, List<{{ sobj }}> {{ obj_var }}){

        try
        {
            BatchJobHelper.AddMessage('{{ api_name }}', 'execute started, {{ obj_var }}.size = ' + {{ obj_var }}.size(), true);

            // ---------------------- ADD YOUR LOGIC HERE ----------------------------------------------
            
            //Integer i = 0;
            //Database.SaveResult[] srList = database.insert(objectList, false) ;
            //Database.SaveResult[] srList = database.update(objectList, false) ;
            //for (Database.SaveResult sr : srList) {
            //    if (sr.isSuccess()) 
            //        numSuccess++;
            //    else {
            //        // Operation failed, so get all errors                
            //        for(Database.Error err : sr.getErrors()) {
            //            // for inserts
            //            String errMsg = 'Error creating Object (' + objectList[i].Name + '): ' + err.getStatusCode() + ': ' + err.getMessage() + ', ' +
            //                                        'fields that affected this error: ' + err.getFields();
            //            // for updates
            //            String errMsg = 'Error updating Object (' + objectList[i].Id + '): ' + err.getStatusCode() + ': ' + err.getMessage() + ', ' +
            //                                        'fields that affected this error: ' + err.getFields();
            //            dmlFailures += '\n' + errMsg;
            //            BatchJobHelper.AddMessage('{{ api_name }}', errMsg, true);
            //        }
            //    }// some failures
            //    i++;
            //}


            BatchJobHelper.AddMessage('{{ api_name }}', 'Batch Done', true);

            // Now, insert all the messages logged for this batch job
            BatchJobHelper.writeLogs('{{ api_name }}');
        }
        catch(Exception ex)
        {
            BatchJobHelper.exceptionHandler('{{ api_name }}', ex);
        }


    }
        
    global void finish(Database.BatchableContext bc) {

        BatchJobHelper.AddMessage('{{ api_name }}', 'finish started, number of successful updates = ' + numSuccess, true);

        AsyncApexJob aaJob = [SELECT ApexClass.Name, Status, ExtendedStatus, MethodName FROM AsyncApexJob WHERE Id = :bc.getJobId()];

        if(aaJob.Status == 'Failed' || Test.isRunningTest() || (aaJob.ExtendedStatus != null && aaJob.ExtendedStatus != '')) {

            BatchJobHelper.AddMessage('{{ api_name }}', 'Failed, status = ' + aaJob.ExtendedStatus, true);

            Messaging.SingleEmailMessage semResult = new Messaging.SingleEmailMessage();
            semResult.setToAddresses(new String[] {'sf.onlinescherrors.group@nextsteplivinginc.com'});
            
            semResult.setSubject('Error in {{api_name}}');
            String fbody = 'The batch job, {{ api_name }}, failed to run.';
            fbody += '\n\nERROR: ' + aaJob.ExtendedStatus;
            fbody += '\n\n' + URL.getSalesforceBaseUrl().toExternalForm() + '/apexpages/setup/listAsyncApexJobs.apexp?retURL=%2Fui%2Fsetup%2FSetup%3Fsetupid%3DJobs&setupid=AsyncApexJobs';
            semResult.setPlainTextBody(fbody);
            try
            {
              Messaging.sendEmail(new Messaging.SingleEmailMessage[] { semResult });
            }
            catch(Exception e)
            {
              system.debug(e);
            }

        }
        if(dmlFailures != null || Test.isRunningTest())
        {
            Messaging.SingleEmailMessage semResult = new Messaging.SingleEmailMessage();
            semResult.setToAddresses(new String[] {'sf.onlinescherrors.group@nextsteplivinginc.com'});
            
            semResult.setSubject('DML failures in {{ api_name }}');
            String fbody = 'The batch job, {{ api_name }}, had the follwing DML failures :';
            fbody += '\n\n' + dmlFailures;
            semResult.setPlainTextBody(fbody);
            try
            {
              Messaging.sendEmail(new Messaging.SingleEmailMessage[] { semResult });
            }
            catch(Exception e)
            {
              system.debug(e);
            }
        }


        // Now, insert all the messages logged for this batch job
        BatchJobHelper.writeLogs('{{ api_name }}');
    }
    
}Thanks  for your help,

Veena

**Comment by mkpartnersDev1** [comment]
I'm having the same issue.  When creating a new class, it's saying a dependent class is invalid due to referencing the sObject type 'RecordType'.  When I comment that class out, it references another class, and so on and so on.

**Comment by rtconner** [comment]
I've been having this exact same issue deploying to SF on a completely different IDE (PHPStorm + IlluminatedCloud).
