### ISSUE TITLE
Cannot get standard objects to download

### ISSUE THREAD

**Issue by force2b** [joeferraro/MavensMate-SublimeText#702]
Up until v5, the following in the package.xml would pull down all custom, standard and managed objects:
```
    <types>
        <members>*</members>
        <name>CustomObject</name>
    </types>
```
Version 5 adds the new option for mm_ignore_managed_metadata to allow managed metadata to be ignored.

However, what I've found is that using just the wildcard for CustomObject returns only custom objects - no standard or managed objects at all. Checking or unchecking the mm_ignore_managed_metadata option in global settings did not change that behavior.  This happens for both Clean Project and right-clicking on the Objects folder and selecting "MavensMate->Refresh from Server"

Next I tried explicitly listing out the standard objects in package.xml:

```
    <types>
        <members>*</members>
        <members>Account</members>
        <members>Contact</members>
        <members>AccountContactRole</members>
        <members>Activity</members>
        <members>Campaign</members>
        <members>CampaignMember</members>
        <members>Case</members>
        <members>CaseContactRole</members>
        <members>Contract</members>
        <members>ContractContactRole</members>
        <members>Event</members>
        <members>Lead</members>
        <members>npe01__OppPayment</members>
        <members>npe4__Relationship</members>
        <members>npe5__Affiliate</members>
        <members>npsp__Address</members>
        <members>npsp__Allocation</members>
        <members>npsp__General_Allocation_Unit</members>
        <members>Opportunity</members>
        <members>OpportunityContactRole</members>
        <members>OpportunityLineItem</members>
        <members>Pricebook2</members>
        <members>Product2</members>
        <members>PricebookEntry</members>
        <members>Task</members>
        <members>User</members>
        <name>CustomObject</name>
    </types>
```

Interestingly that did not change the result at all. I still only get custom objects in the objects folder. Can't seem to find a way to get this to pull down Standard and Managed objects when using Clean Project or refreshing the folder from Salesforce.

MM-App: v.0.0.9
MM/Sublime: v5.0.5

**Comment by joeferraro** [comment]
@force2b fix is here: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta1

and just as an fyi, this is not a valid package.xml (according to salesforce):

```
<types>
        <members>*</members>
        <members>Account</members>
        <members>Contact</members>
        <members>AccountContactRole</members>
        <members>Activity</members>
        <members>Campaign</members>
        <members>CampaignMember</members>
        <members>Case</members>
        <members>CaseContactRole</members>
        <members>Contract</members>
        <members>ContractContactRole</members>
        <members>Event</members>
        <members>Lead</members>
        <members>npe01__OppPayment</members>
        <members>npe4__Relationship</members>
        <members>npe5__Affiliate</members>
        <members>npsp__Address</members>
        <members>npsp__Allocation</members>
        <members>npsp__General_Allocation_Unit</members>
        <members>Opportunity</members>
        <members>OpportunityContactRole</members>
        <members>OpportunityLineItem</members>
        <members>Pricebook2</members>
        <members>Product2</members>
        <members>PricebookEntry</members>
        <members>Task</members>
        <members>User</members>
        <name>CustomObject</name>
    </types>
```

**Comment by force2b** [comment]
Thank you. I searched for a similar issue (open or closed) and didn't see one. Installing beta version fixed the issue. 

I agree that the package.xml isn't technically valid, given that I'm mixing the wildcard and the object names. It was just an experiment to see if listing them out would help.

**Comment by joeferraro** [comment]
@force2b yeah no worries. just letting you know, only because in my testing this past weekend, I tried that very package combination and found that it wasn't valid. cheers!
