### ISSUE TITLE
Polling time out - project compile

### ISSUE THREAD

**Issue by LKozakewycz** [joeferraro/MavensMate-SublimeText#703]
I have a large project I am compiling and it times out from time to time. Here is the error that I get:

```
Operation: Compiling Project
Timestamp: Tue, 06 Oct 2015 13:33:54
   Result: [ERROR]: Polling time out. Process Id = 0Af20000005HjHGCA0
```

This is particularly frustrating because it takes a long time to compile the project as it is very large.

MM 5.0.5
Win 8.1 
ST 3083

**Comment by joeferraro** [comment]
Hi @LKozakewycz, certainly understand the frustration. You can adjust the timeout via the `mm_timeout` setting in mm-app. In an upcoming release, that default will be increased. 

![windows_8](https://cloud.githubusercontent.com/assets/54157/10308883/ff7ca502-6c06-11e5-927e-b783bc11ac70.png)

**Comment by LKozakewycz** [comment]
Thanks Joe! I've changed this - hopefully this won't happen now. :)

**Comment by joeferraro** [comment]
cheers @LKozakewycz :+1:

**Comment by LKozakewycz** [comment]
@joeferraro - I updated that value to 60000 and it still has the same issue.

I can't actually compile my project at all (in neither metadata API, nor the tooling API).

**Comment by joeferraro** [comment]
HI @LKozakewycz I'm sorry to hear that. what components make up your project? (can you paste your package.xml)?

**Comment by LKozakewycz** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>*</members>
		<name>ApexClass</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexComponent</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexPage</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexTrigger</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomObject</name>
	</types>
	<types>
		<members>*</members>
		<name>StaticResource</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomLabels</name>
	</types>
	<version>34.0</version>
</Package>
```

**Comment by seanhharrison** [comment]
May be unrelated but I found I would get in this state if, at any point, I've tried to save a class file with mismatched file & class names, recently had renamed some metadata, or failed in any effort to "delete file from server."  A "Clean Project" cleared up the compile problems I had in this regard.
