### ISSUE TITLE
Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

### ISSUE THREAD

**Issue by haripopuri** [joeferraro/MavensMate-SublimeText#705]
Hi,

I am using Windows MM and got this error. I created new project and still the same error. I got this error when trying to save/refresh file from server.

I have latest version of MM App (0.0.9) and MavensMate for Sublime Text v6.0.0

Please help.

Thanks

**Comment by LKozakewycz** [comment]
I'm getting this too.

**Comment by LKozakewycz** [comment]
Fix for this:

1. Open project directory
2. Delete `.sublime-project`, `.sublime-settings`, `.sublime-workspace` files
3. Delete config directory
4. In sublime text, open project and right click on the top level directory in the file explorer (the project directory).
5. Go to MavensMate > `Create MavensMate Project...`
6. Set credentials
7. Done!

**Comment by m0gul** [comment]
This doesn't work... There is no "Create MavensMate Project..." -- any other ideas?

**Comment by m0gul** [comment]
FYI -- I created an entire new project, still the same error.

**Comment by jeremywhittington** [comment]
This does not fix the error. I cant Create a MavensMate project if the folder already exists. So what does deleting those files do to help? Id have to literally blow away the entire project folder and start over. This is an existing project from github.

Need a way to reset credentials without having to completely kill my project.

**Comment by bobbyculbertson** [comment]
I am getting this as well.

Have recreated the projects (on Windows Machine)
Deleted MavensMate and sublime from Mac Machine
Have uninstalled and reinstalled MavensMate on Windows machine
Recreated new project, same error when trying to save a class.

**Comment by PaulChristian** [comment]
I'm seeing a similar error even after re-installing. Any update on this?

**Comment by lefthook123** [comment]
I'm seeing a similar error even after re-installing. Any update on this?

**Comment by Drobi83** [comment]
+1 here

**Comment by PaulChristian** [comment]
I've completed removed and reinstalled mavens mate and sublime. Seeing the same error.

**Comment by jeremywhittington** [comment]
Is there going to be a fix for this? I am unable to use sublime+mavensmate for development with Salesforce because of this. I will need to request a refund if this isnt resolved.

**Comment by WarbleSync** [comment]
I was having this same problem.  If you are tracking your projects with git then make sure your package.xml is clean when try to create the project.

**Comment by JodieM** [comment]
As this issue is still open, does this specific comment on one of the other issues about this topic help at all? https://github.com/joeferraro/MavensMate-SublimeText/issues/729#issuecomment-149344353

**Comment by devvratarya** [comment]
For sublime users on windows, close the Mavensmate app, and start a new project using Mavensmate sublime plugin. That will fix the issue.

Sublime works without starting MM app
