### ISSUE TITLE
[SOLVED]mm_workspace issue

### ISSUE THREAD

**Issue by Sylvainp-Ribbonfish** [joeferraro/MavensMate-SublimeText#709]
Hi,

I'm using this version:
MavensMate for Sublime Text v6.0.0

And since this morning in my office we are getting this error:

[OPERATION FAILED]: Please ensure mm_workspace is set to existing location(s) on your local drive

It was working fine a minute ago for me, but then nothing anymore..
The path is correctly set in the MavensApp setting. 
The line appears for me when I do MyObject. (Line appear in console)
Then I can't save anymore to the server. 
If I restart Sublime nothing help. 

For an other guy in the office this started to happen when he saved the file. And still can't work anymore as it do not save to the server anymore.

Thanks for your help

**Comment by LKozakewycz** [comment]
MavensMate > Settings > Default

Set your workspace directory under `mm_workspace`.

**Comment by Sylvainp-Ribbonfish** [comment]
Solved thanks, well it did erase the setting in this file with the new version.

Thanks a lot.
