### ISSUE TITLE
[OPERATION FAILED]: Please ensure mm_workspace is set to existing location(s) on your local drive

### ISSUE THREAD

**Issue by lnakamaru** [joeferraro/MavensMate-SublimeText#711]
Sublime 3 is throwing an error regarding MavensMate: 
[OPERATION FAILED]: Please ensure mm_workspace is set to existing location(s) on your local drive
I can open the project in Sublime through MavensMate app, I can open a file, but if I try to refresh or save the file it throws me this error.

I already unistalled MavensMatte, installed again. Created a new project, downloaded all the files. But it still throws me this error. The path is correct for the project.
<img width="674" alt="screen shot 2015-10-07 at 11 02 58" src="https://cloud.githubusercontent.com/assets/15015883/10339675/02ccad06-6ce3-11e5-8ed5-68b0d0a91340.png">

<img width="1112" alt="screen shot 2015-10-07 at 11 00 50" src="https://cloud.githubusercontent.com/assets/15015883/10339637/cd7002c0-6ce2-11e5-95d8-8528748dd058.png">
<img width="1552" alt="screen shot 2015-10-07 at 10 59 46" src="https://cloud.githubusercontent.com/assets/15015883/10339638/ceb8471e-6ce2-11e5-8a13-3452956ca30e.png">

**Comment by dsumnerMWA** [comment]
Im getting the same error. Here's the console output and screen shots.

[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
Package Control: Skipping automatic upgrade, last run at 2015-10-07 08:55:56, next run at 2015-10-07 09:55:56 or after
[MAVENSMATE] failed to send community activity
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project_from_existing_directory
[MAVENSMATE]: {'params': {'directory': 'C:\\Users\\dsumner\\workspace\\MWA'}}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Program Files\Sublime Text 3\Data\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --ui -o new_project_from_existing_directory
[MAVENSMATE]: {"directory": "C:\\Users\\dsumner\\workspace\\MWA"}
[MAVENSMATE]: response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false} 

[MAVENSMATE] failed to send community activity
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project_from_existing_directory
[MAVENSMATE]: {'params': {'directory': 'C:\\Users\\dsumner\\workspace\\MWA'}}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Program Files\Sublime Text 3\Data\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --ui -o new_project_from_existing_directory
[MAVENSMATE]: {"directory": "C:\\Users\\dsumner\\workspace\\MWA"}
[MAVENSMATE]: response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false} 

[MAVENSMATE] failed to send community activity

![image](https://cloud.githubusercontent.com/assets/13837723/10339784/ab8320da-6cd2-11e5-895f-27dfe2eb1f07.png)

**Comment by aoztovi** [comment]
I am having the same issue. It started giving this message today out of the blue. mm_workspace setting is done correctly. Makes no sense.

**Comment by Scott-Huller-Bluewolf** [comment]
Running into the same issue here. Please advise on a fix.

**Comment by miguelxt** [comment]
+1

**Comment by thegogz** [comment]
Mavensmate is not reverting the user settings file after it upgrades to V6.0.0 All you need to do is add 

mm_workspace to your User settings 

Click MavensMate > Settings > User

Add the following 
```
	"mm_workspace" : "C:\\Repos",
```

If you check the Default you'll see the full explanataion like this
```
	//set to absolute location where you wish your MavensMate project to reside
	//if the location does not exist, MavensMate will attempt to create it
	//for example: "/Users/username/Documents/workspaces/mavensmate" (notice the absolute path)
	//WINDOWS USERS: it's probably best to set this like so: C:\\path\\to\\your\\workspace
	//****NEW****: you can now set mm_workspace to an array of locations on your file system
	//EXAMPLE:
	// "mm_workspace" : [
	// 		"/my/workspace",
	// 		"/my/other/workspace",
	// 		"/my/super/secret/workspace"
	// ]
	"mm_workspace" : "",
```

**Comment by dsumnerMWA** [comment]
@thegogz - if you look at the screen shot I provided above, you'll see its set but still giving the error.

**Comment by aoztovi** [comment]
I did.. But still giving the error message.

**Comment by thegogz** [comment]
@dsumnerMWA that's odd, that's all I did and restarted Sublime and it worked. Have you tried copying and replacing the full contents of the User settings? 

@aoztovi  sorry to hear that, this is what fixed it for me.

**Comment by dsumnerMWA** [comment]
@thegogz - I received a handful of popup errors this morning and couldn't get around them, so I just reinstalled from scratch. The reinstall brought in ALL the settings to the user settings file again.

**Comment by MaggiePlusPlus** [comment]
I have this too starting today after updating to v6.0.0 and mavensmate app to v0.0.9
The workspace is still set in the global settings.

**Comment by thegogz** [comment]
You don't need the mavensmate app with v6.0.0. V6 is essentially v4 again, so the settings are in sublime text again not in the app

**Comment by MaggiePlusPlus** [comment]
I just read that I was getting used to 5, guess I'll try 7

**Comment by dfuller0814** [comment]
So I'm a little confused. Do we no longer need to run the MavensMate app in order for the Mavens Mate plugin to work?

**Comment by dsumnerMWA** [comment]
@dfuller0814 - If you use v7 then yes, but not for v6. v6 is basically v4 reborn from what Ive read.

**Comment by dfuller0814** [comment]
@dsumnerMWA, thanks for that info. I assumed the Sublime Text plugin automatically updates. Would v6 no longer be maintained?

**Comment by garyspencer** [comment]
Yes.. Same issue. 

The underlying issue is in that ST3 Package Manager Rollback/Remove Package/Install Package process does not overwrite your user settings...By design... So we are all using our old user settings files. Navigate to the directory where your mavensmate.sublime-settings and either:

A)  Find the deprecated-settings file in that directory and do a name swap
B) Delete the settings file and reinstall v6
C) Follow the instructions for letting ST3 package manager pull 'pre-releases'

**Comment by dsumnerMWA** [comment]
@dfuller0814 - Good question. v6 is supposed to be the work around for those with issues in v7. Hopefully we'll hear from someone soon. Regardless, Im headed back to use Eclipse while all this gets sorted out.

**Comment by dsumnerMWA** [comment]
@garyspencer thanks for the info. I did a complete reinstall and still have this issue with v6.

**Comment by dsumnerMWA** [comment]
Just tried to install the 32bit version to see if that makes a difference and it does not. Anyone else had any luck?

**Comment by garyspencer** [comment]
@dsumnerMWA Oh..  Well what I was getting at is that 'a complete reinstall' is a bit misleading, because it will not touch those settings files.

**Comment by garyspencer** [comment]
32 bit version will also re-use the culprit settings files...

**Comment by dsumnerMWA** [comment]
The mavensmate.sublime-settings was new for both installs. I had to re apply my workspace in both.

**Comment by garyspencer** [comment]
Oh... that must mean the settings files weren't swapped...  I didn't realize that might be an issue, I only tested one of the solutions.

Try this:  do the mavensmate-deprecated.settings rename I described above, (or copy the contents into the properly named file) to get a good base config file in order to start re-configuring properly.

**Comment by dsumnerMWA** [comment]
Also - the setting file was v4 based, not v5 based..so mm_workspace was already in the file and I just added my directory.

**Comment by garyspencer** [comment]
Damn, well inn any event, I tried for a solution... hehe.  If it doesn't work, I must have a bit of a misunderstanding of the problem.  Sorry bud!

**Comment by dsumnerMWA** [comment]
@garyspencer ok I'll give it a try, where does that file exist? I looked for it earlier but had to run out to a meeting.

**Comment by dsumnerMWA** [comment]
@garyspencer I appreciate your help, anything is worth a try at this point! :)

**Comment by garyspencer** [comment]
It can differ.  Open your user settings (MavensMate Menu -> Settings -> User),  Right click in the text region and choose "Copy File Path"  

I am on Windows 7, for me it is in %APPDATA%/Sublime Text/Packages/User/

**Comment by dsumnerMWA** [comment]
Im on Windows 7 as well, here's whats in that folder...

![image](https://cloud.githubusercontent.com/assets/13837723/10347228/8c07c460-6cf8-11e5-8bfa-9aad17cfc876.png)

**Comment by garyspencer** [comment]
Ok.

Same steps for opening user settings.

Open your user settings, and paste the contents of below in, set relevant settings, save, restart sublime, win.

https://github.com/joeferraro/MavensMate-SublimeText/blob/revert-427-private-repos/mavensmate.sublime-settings

**Comment by dsumnerMWA** [comment]
The file you have is the same as what I have, but I went ahead and renamed mine and created a new file with the content yours. Still no luck though. Thanks again for the suggestion, hopefully we'll hear something soon.

**Comment by dsumnerMWA** [comment]
You mentioned install_prereleases above, isn't that setting for v7 only? I did try it but didn't make any difference. 

https://github.com/joeferraro/MavensMate-SublimeText/blob/master/messages/rollback.md

**Comment by garyspencer** [comment]
Yea, I mentioned the pre-release as an option to continue using mavensmate-app (v5/7) with the 'current' settings file, which of course was assuming based on my experience that  the settings file was causing the issue.  ASS_U_ME!

**Comment by dsumnerMWA** [comment]
Ah gotcha, thanks.

Has anyone had any luck?

**Comment by joeferraro** [comment]
Hi folks, v6 (v4.0.5) has no concept of MavensMate-app. If you are using v6, all settings are managed within Sublime Text. You need to copy the default plugin settings to your user settings and modify them there, as you did in v4.0.5:

MavensMate > Settings

![screen shot 2015-10-08 at 11 05 27 am](https://cloud.githubusercontent.com/assets/54157/10370386/85a21fee-6dac-11e5-9f32-125b229bc6d8.png)

**Comment by dsumnerMWA** [comment]
@joeferraro - thanks for the response. I did do a COMPLETE reinstall of ST3 and MavensMate, so I know I have the v4 settings file (its much larger than v5) but it still did not work. So mm_workspace is set but its saying it is not. See my screen shot in the second post from the top.

**Comment by joeferraro** [comment]
@dsumnerMWA if i had to guess, mm is having trouble parsing your settings file. can you post your entire user settings file?

**Comment by dsumnerMWA** [comment]
@joeferraro - sure no problem, here you go. Thanks for your help on this!

https://github.com/dsumnerMWA/mystuff

**Comment by joeferraro** [comment]
@dsumnerMWA thanks a bunch. your settings look fine to me. out of curiosity, what happens if you set your workspace in the default settings instead?

**Comment by dsumnerMWA** [comment]
Same thing. I set it earlier when I was investigating.

**Comment by dsumnerMWA** [comment]
I'll post it up there as well.

**Comment by dsumnerMWA** [comment]
Just want to add WHEN I am receiving the error. Im trying to use the "Create MavensMate Project..." feature, so with Sublime Text open, I open my local Github folder, then right click on the top level folder, then go down to MavensMate --> Create MavensMate Project... That is when I receive the following error (same screen shot as above).

![image](https://cloud.githubusercontent.com/assets/13837723/10430562/8153c2f0-70c5-11e5-9b46-21e38875cc3a.png)

**Comment by dsumnerMWA** [comment]
One other thing I want to mention, is Im unable to create a new MavensMate project through the menu at the top (MavensMate --> Project --> New Project...). When I do, it doesn't open any browser windows like it would normally. But the console shows the same error mm_workspace error.

[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
Package Control: Skipping automatic upgrade, last run at 2015-10-12 09:30:35, next run at 2015-10-12 10:30:35 or after
[MAVENSMATE] failed to send community activity
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Program Files (x86)\Sublime Text 3\Data\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --ui -o new_project
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


[MAVENSMATE] failed to send community activity

**Comment by sirimudindi** [comment]
Hi

For me the mm_workspace is in default settings and it is set properly, i still get the error " Please ensure mm_workspace is set to existing location(s) on your local drive ". Please suggest how to fix this.

**Comment by sirimudindi** [comment]
![user settings](https://cloud.githubusercontent.com/assets/15001037/10432083/d270b2d6-70bd-11e5-8c07-97a044411ee0.PNG)
 Iam curious why i dont have the workspace settings in my user settings, this is how my user settings is looking like

**Comment by joeferraro** [comment]
@sirimudindi this is because you rolled back from the v5 release (now v7). v6 does not have any concept of mavensmate-app, so configuring your setting there will not help. you will need to copy your plugin default settings to your user settings and configure your mm_workspace there.

**Comment by sirimudindi** [comment]
How do i do that ?

**Comment by dsumnerMWA** [comment]
@sirimudindi - go here, copy,overwrite and save over what you have..

https://github.com/joeferraro/MavensMate-SublimeText/blob/revert-427-private-repos/mavensmate.sublime-settings

**Comment by sirimudindi** [comment]
I did and now i get this error, even though iam logged into my salesforce backend successfully " Server raised fault: 'INVALID_LOGIN: Invalid username, password, security token; or user locked out.". Please suggest.

**Comment by dsumnerMWA** [comment]
@sirimudindi - looks like you need to update your credentials. Goto MavensMate --> Project --> Edit Project and put in your credentials.

**Comment by dsumnerMWA** [comment]
@lnakamaru @Scott-Huller-Bluewolf @miguelxt @MaggiePlusPlus  - Did you all get yours to work?

**Comment by sirimudindi** [comment]
@joeferraro , Thanks my mavens,ate is working now !!!!

**Comment by miguelxt** [comment]
Yup, I just changed the mm_workspace in MavensMate -> Settings -> Default

"mm_workspace": 
	[
	  "/Users/username/Documents/mavensmate-workspace"
	],

**Comment by sirimudindi** [comment]
@miguelxt , Is it working for u ?

**Comment by miguelxt** [comment]
@sirimudindi Yep, it's working fine now.

**Comment by MaggiePlusPlus** [comment]
yes, thanks

**Comment by dsumnerMWA** [comment]
So mine is working again now. I did another complete reinstall. This time I searched through my registry and deleted every key value pair I found containing "Sublime Text" or "MavensMate". Then I searched my entire computer for any lingering files/folders with those names and deleted them as well. Then I just installed 64bit ST3 and followed the instructions at mavensmate.com. I can create projects now without this error showing up.

**Comment by garyspencer** [comment]
@dsumnerMWA  Out of curiosity, how many rego keys were there, and how many lingering files did you delete?  Did any of them strike you as the possible culprit?

**Comment by dsumnerMWA** [comment]
@garyspencer at this point I was just deleting and not looking back. If I had to guess, Id say there was about 20 registry entries between ST3 and MM. For files I uninstalled through Control panel, then just deleted the folder under Program Files and any related downloads I still had.
