### ISSUE TITLE
Error loading syntax file Packages/MavensMate/sublime/lang/Visualforce.tmLanguage

### ISSUE THREAD

**Issue by haripopuri** [joeferraro/MavensMate-SublimeText#712]
Hi,

I am receiving this error;

![mavensmate vf language error](https://cloud.githubusercontent.com/assets/1023143/10344004/bcb47a68-6cd5-11e5-853d-7c639ed7e804.png)

MavensMate for Sublime Text v5.0.5

**Comment by ct-ferozakbar** [comment]
whats the fix?

**Comment by ohaucke** [comment]
> Update: August 7, 2017
> MavensMate is no longer being actively developed or supported.
