### ISSUE TITLE
Your MavensMate project needs to be upgraded. Opening the upgrade UI.

### ISSUE THREAD

**Issue by karthikkornalies** [joeferraro/MavensMate-SublimeText#714]
Have update the Mavensmate app to  v0.0.9 and started the App then tried to save a page on Sublime. Getting the below message. However the password is valid while trying to edit the project on Mavensmate app. Please advise if i'm missing something here.

Error Message on Sublime Console : 

Timestamp: Wed, 07 Oct 2015 12:12:40
   Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

**Comment by garyspencer** [comment]
Hi, can you add more details to the issue according to the [guidelines](https://github.com/joeferraro/MavensMate-SublimeText/blob/master/CONTRIBUTING.md)?  What version of sublime text, mavens mate plugin, app, operating system, salesforce sandbox vs prod.. etc.

Did your ST3 Mavensmate rollback to v6?  There were issues in that process.  Without a little intervention on your part, MavensMate will not work correctly until you configure it correctly (again)

**Comment by jobou363** [comment]
Same problem for me when I save file .cls but I recreate a new project and it din't fix my problem : 

Operation: Your MavensMate project needs to be upgraded. Opening the upgrade UI.
Timestamp: Wed, 07 Oct 2015 16:04:45
   Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

Windows 8.1
Sales Force Developper
MavensMate for Sublime Text v6.0.0
MavensMateApp v0.0.10 Beta 2

**Comment by LKozakewycz** [comment]
Current fix:

https://github.com/joeferraro/MavensMate-SublimeText/issues/705#issuecomment-146154726
