### ISSUE TITLE
Getting error while saving file "workspace not set"

### ISSUE THREAD

**Issue by nevrekaramey** [joeferraro/MavensMate-SublimeText#716]
Please ensure mm_workspace is set to existing location(s) on your local drive

I have ensured that mm_workspace is set in Mavenmates app and it still throws me the above error.

**Comment by westhechiang** [comment]
how did you resolve this issue? I'm suddenly getting the same error out of the blue

**Comment by nevrekaramey** [comment]
Sublime text was automatically upgraded to v 6.0 which is primarily roll back to the v4.0.5 codebase. Hence now we need to go back to MavensMate -> Settings -> User and addd "mm_workspace" : path
This shall fix the issue.

**Comment by nevrekaramey** [comment]
Sublime text was automatically upgraded to v 6.0 which is primarily roll
back to the v4.0.5 codebase. Hence now we need to go back to MavensMate ->
Settings -> User and addd "mm_workspace" : path
This shall fix the issue.

On Wed, Oct 7, 2015 at 2:24 PM, Wesley Chiang <notifications@github.com>
wrote:

> how did you resolve this issue? I'm suddenly getting the same error out of
> the blue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate-SublimeText/issues/716#issuecomment-146334255>
> .
>



-- 
Thanks & Regards
Amey Nevrenkar
