### ISSUE TITLE
Your[mm_worksapce] property is not set

### ISSUE THREAD

**Issue by Inbarajd** [joeferraro/MavensMate-SublimeText#723]
When I am trying to open the project I am getting the following error message. I have set my mm_workspace in MavensMate. I have attached the screen shot for your reference. 
![screen](https://cloud.githubusercontent.com/assets/8289753/10397753/4e90cd18-6e77-11e5-8fa5-f2c3a1372f79.jpg)

Your[mm_worksapce] property is not set. Open 'MavensMate>Settings>User' or press'Cmd+Shift+,' and set this property to the full path of your workspace. Thx!

**Comment by DavidCDean** [comment]
I had this issue too and manually adding mm_workspace, like you said, worked. It was previously specified in the helper app, so I suspect this had to do with the plugin rollback?

**Comment by dkurylo** [comment]
@Inbarajd For me, changing the default settings helped. Seems like MM does not want to read this property from user settings for some reason.
