### ISSUE TITLE
Could not locate Sublime Text

### ISSUE THREAD

**Issue by m0gul** [joeferraro/MavensMate-SublimeText#725]
![wtf mavens mate](https://cloud.githubusercontent.com/assets/3057603/10403424/4cfce3c0-6e80-11e5-869e-7cc18cff7e59.JPG)

No idea why this isn't working... It was working on Monday (and I think Tuesday), then it just stopped...

**Comment by m0gul** [comment]
I fixed the problem above, now I'm getting: 

Operation: Your MavensMate project needs to be upgraded. Opening the upgrade UI.
Timestamp: Fri, 09 Oct 2015 12:52:32
   Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

**Comment by m0gul** [comment]
Time to use eclipse!

**Comment by m0gul** [comment]
re-installed Sublime and MM roughly 6 times per... still doesn't work.

**Comment by m0gul** [comment]
I should have taken better notes as I was doing this, but I've tried the "stable" version install and the newest install, each I've tried multiple times. But, nothing works... shit is broke, yo.

**Comment by m0gul** [comment]
How do I "upgrade" my MavensMate project?!

**Comment by garyspencer** [comment]
@mogul is that a mobile version of sublime text?  I remember reading an issue about that.  
Possibly relatedrelated issue? 

https://github.com/joeferraro/MavensMate/issues/269

this looked like it boliled down to the same thing -- even though it was an osx issue -- but for science https://github.com/joeferraro/MavensMate-SublimeText/issues/602

**Comment by m0gul** [comment]
Not mobile.

**Comment by m0gul** [comment]
Looks like Joe changes something in the last 20 hours, it works, yayyy!!!

**Comment by garyspencer** [comment]
@joeferraro @m0gul This issue can be closed then I suppopse :dart:
