### ISSUE TITLE
Unrecognized package.xml metadata type

### ISSUE THREAD

**Issue by karthikkornalies** [joeferraro/MavensMate-SublimeText#726]
Hello Team,

Getting the below mentioned mentioned message while saving or refreshing the project from workspace. Not sure what im missing here. Can anyone please advise to solve this issue or workaround.

 MavensMate for Sublime Text v7.0.0-beta.1  

Sublime version : 3 
                                                                          
Operation: Refreshing: E:\salesforceXXX\XXXX
Timestamp: Sat, 10 Oct 2015 07:29:38
   Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: Unrecognized package.xml metadata type: AccountTerritorySharingRules
 
Thanks,
Karthik Kornalies

**Comment by force2b** [comment]
Check out this issue - https://github.com/joeferraro/MavensMate-SublimeText/issues/693#issuecomment-145527660.

**Comment by karthikkornalies** [comment]
Changing the version to 32.0 worked. Thanks.
