### ISSUE TITLE
EBUSY: resource busy or locked, rmdir

### ISSUE THREAD

**Issue by karthikkornalies** [joeferraro/MavensMate-SublimeText#727]
Hello Team,

I'm trying to refresh the whole project (Update project). For some reasons the refresh fails with following messages on MavensMate App and also other components on the project are not showing up now. Also double checked the metadata subscription are still selected. Say for example only pages under src is available (Classes, triggers and other folder are missing).

EBUSY: resource busy or locked, rmdir 'E:\workspace\xxx'

Sublime version : 3
Mavensmate App : v0.0.9
Sublime Text v7.0.0-beta.1
OS : Windows 8.1

Also tried just refreshing (Refresh from server) src folder within sublime and getting following message.

Timestamp: Sat, 10 Oct 2015 14:56:26
   Result: [ERROR]: Could not initiate Package instance by path: ENOENT: no such file or directory, open 'E:\workspace\ProjNameXX\src\package.xml'

![image](https://cloud.githubusercontent.com/assets/43282/10413071/df853f20-6f62-11e5-93c7-d0d92705a0b5.png)

Tried restarting the sublime as well. Please advise any other workaround or any other thoughts

Thanks,
Karthik Kornalies

**Comment by joeferraro** [comment]
@karthikkornalies There are some super pesky PERM-related issues with node on windows. this update changes the way we do cleans/refreshes/edits of the src directory. let me know if it works for you: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta4
