### ISSUE TITLE
Create Resources Bundle in v6 project doesn't work in v7

### ISSUE THREAD

**Issue by rngadam** [joeferraro/MavensMate-SublimeText#728]
Created project in MavensMate v6. 

Then tried to create "MavensMate: Create Resource Bundle" in v7 results in this error:

```
[MAVENSMATE]: =============> Starting MavensMate for Sublime Text
SublimeSalesforceReference: Startup caching will begin shortly
Package Control: No updated packages
[MAVENSMATE] skipped community activity
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/MavensMate/mavensmate.py", line 920, in run
    for dirname in os.listdir(os.path.join(util.mm_project_directory(),"src","staticresources")):
FileNotFoundError: [Errno 2] No such file or directory: 'HelloWorld/src/staticresources'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/MavensMate/mavensmate.py", line 920, in run
    for dirname in os.listdir(os.path.join(util.mm_project_directory(),"src","staticresources")):
FileNotFoundError: [Errno 2] No such file or directory: HelloWorld/src/staticresources'
```

**Comment by joeferraro** [comment]
That path does not look right to me: `"HelloWorld/src/staticresources"`. what is the value of your `mm_workspace` setting in MavensMate-app? You always need to set workspaces as **absolute** paths. `HelloWorld/src/staticresources` is a relative (and probably non-existent) path, which leads me to believe you may have an invalid mm_workspace setting.

**Comment by rngadam** [comment]
I edited the stacktrace to remove private information, it is an absolute path.

**Comment by joeferraro** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: HelloWorld/src/staticresources'

this leads me to believe you may have an incorrect mm_workspace setting. please paste the value of your mm_workspace setting. thanks.
