### ISSUE TITLE
Cleaning Project Broken. Kills src folder.

### ISSUE THREAD

**Issue by ajfrederick** [joeferraro/MavensMate-SublimeText#730]
v7.0.0-beta.1 Every time I've cleaned my project today it nukes the src folder and subsequently the package.xml which prevents the ability to clean at all. I am continually having to make new projects for the same project.

**Comment by joeferraro** [comment]
Hi @ajfrederick, can you please update your issue according to the guidelines? https://github.com/joeferraro/MavensMate-SublimeText/blob/master/CONTRIBUTING.md

thanks so much
