### ISSUE TITLE
Changes made in Sublime Text do not get committed to the Salesforce server.

### ISSUE THREAD

**Issue by ErikatUCI** [joeferraro/MavensMate-SublimeText#732]
I am running MavensMate for Sublime Text v7.0.0-beta.1 and Sublime Text 3 along with Sublime Text Package Control.  I installed both today though first I tried to install MavensMate version 5 but got version 4.0.5 which did not support the Lightning Aura Definition Bundles. So I upgraded to version 7. 

I am running Windows 7 64-bit and am directly connected to the internet with no firewall.  I am connecting to a Salesforce sandbox on pod cs25.  Using the Eclipse force.com IDE I can change Apex files locally and commit them to the sandbox.  Aura files are not supported by Eclipse.

In MavensMate, I can create a project and download Aura and Apex files from a Salesforce sandbox to my local Windows PC.  Any changes I make directly in the sandbox (using the Salesforce Developer Console) are correctly downloaded to my PC when I tell MavensMate to update the project.

The problem I have is any changes I make to Aura or Apex files in my MavensMate project directory using Sublime Text never get committed to the Salesforce sandbox.  There is no error message.  The only message at the bottom of the screen is that the file has been saved.  The local copy is saved correctly, The sandbox copy never gets changed. The two log files I find are as follows:

LOG FILE MAVENSMATE.LOG contains:
2015-10-20T23:57:53.010Z - info: initiated client:  {"name":"mavensmate-app","isServer":true,"isNodeApp":false,"isCommandLine":false,"settings":{"type":"literal"}}
2015-10-20T23:57:53.560Z - debug: Processing request GET for URL: /app/home/index
2015-10-20T23:58:01.847Z - debug: Processing request GET for URL: /app/home/index

LOG FILE MMST.LOG FILE  contains (The first error occurs if I do not start MavensMate before starting Sublime Text.  The second message comes if MavensMate is running before starting Sublime Text.):
=============> Starting MavensMate for Sublime TextC:\Program Files\MavensMate\MavensMate.exe urlopen error [WinError 10061] No connection could be made because the target machine actively refused it
=============> Starting MavensMate for Sublime Text C:\Program Files\MavensMate\MavensMate.exe

My USER PLUGIN SETTINGS FILE in Sublime Text includes:
	"mm_compile_on_save" : true, 
	"mm_plugin_logs_location" : "C:\\Users\\Erik\\Documents\\Mavensmate-workspace\\Logs",
	"mm_diff_server_conflicts" : true,
	"mm_start_mavensmate_app" : true,
	"mm_mavensmate_app_location" : {
		"osx": "/Applications/MavensMate.app",
		"windows": "C:\\Program Files\\MavensMate\\MavensMate.exe",
		"linux": ""
	},
	"mm_sublime_text_executable_location" : {
		"osx": "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl",
		"windows": "C:\\Program Files (x86)\\Sublime Text 3\\sublime_text.exe",
		"linux": "/usr/bin/subl"
	},

My MAVENSMATE SETTINGS FILE in the MavensMate App includes:
mm_workspace =  "C:\\Users\\Erik\\Documents\\Mavensmate-workspace"
mm_api_version = 34
mm_subl_location =    "windows": "C:\\Program Files\\Sublime Text 3\\sublime_text.exe",
mm_mavensmate_app_path = "windows": "C:\\Program Files\\MavensMate\\mavensmate.exe",

All paths in the settings files are correct.  What can I do to further diagnose this or fix the problem?

Thanks,
Erik

**Comment by vicki429** [comment]
Did you got this solved? I have exactly same problem with you....

**Comment by ErikatUCI** [comment]
I never did get it solved. I eventually dropped it for lack of time.
