### ISSUE TITLE
Unable to retrieve password from the keychain store (on windows 10)

### ISSUE THREAD

**Issue by amolsable007** [joeferraro/MavensMate-SublimeText#737]
I have installed lates version 10 of mavensmate app and latest 64 bit sublime text 3 on my windows 10 machine. I am creating the project from mavensmate app and then opening it with sublime. After that if I try toi refresh any file for server or even saving any i am getting following error.

Operation: Your MavensMate project needs to be upgraded. Opening the upgrade UI.
Timestamp: Mon, 26 Oct 2015 16:47:33
Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

**Comment by joeferraro** [comment]
Hi! If you are using mavensmate-app, you need to install the sublime text plugin v7 betas https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas

**Comment by viraj89** [comment]
The same issue happened with my peers. I had experienced the same, so was able to get them out of this. Got the latest mm app, st3 and plugin especially. That worked out.
