### ISSUE TITLE
Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

### ISSUE THREAD

**Issue by nirvi22** [joeferraro/MavensMate-SublimeText#742]
I am getting this error when I am trying to refresh any object in Sublime.

Operation: Your MavensMate project needs to be upgraded. Opening the upgrade UI.
Timestamp: Mon, 02 Nov 2015 22:41:57
   Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

**Comment by nirvi22** [comment]
Please let me know what needs to be done as I have tried almost all the options that I found over the web.

**Comment by steals** [comment]
Hello @nirvi22,
can you please update your issue according to the guidelines? https://github.com/joeferraro/MavensMate-SublimeText/blob/master/CONTRIBUTING.md

Also have you tried to recreate your project in Mavensmate (or create project with different name but with the same credentials)?

**Comment by krauszraphael** [comment]
Hi @nirvi22 

Have you manually moved your project?

What happened / What steps did you take for this condition to occur?
