### ISSUE TITLE
Unable to Edit existing Project

### ISSUE THREAD

**Issue by Insouciance** [joeferraro/MavensMate-SublimeText#745]
I need to change my Password in MM. When I try to "Edit Project" the tab comes up in Chrome (Version 46.0.2490.80 m) but it's completely empty.  It doesn't show any Metadata in the metadata tab,  
![image](https://cloud.githubusercontent.com/assets/9252993/11094372/7fbaa972-885d-11e5-942b-fd3ad97c61cf.png)
nor does it show my Project Name and Username on the Project Details tab and it seems to have forgotten that the project is for a sandbox. 
![image](https://cloud.githubusercontent.com/assets/9252993/11094400/aa3468aa-885d-11e5-9b49-2a8d230795eb.png)

When I do put my credentials and click the "Update Credentials" button nothing happens.  The following is from the Sublime Text console.  

	[MAVENSMATE]: Calling mm_interface
	[MAVENSMATE]: OPERATION: edit_project
	[MAVENSMATE]: {}
	[MAVENSMATE]: mm command: 
	[MAVENSMATE]: "C:\Users\dbeltowski\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 -o edit_project --ui
	[MAVENSMATE]: {"workspace": "C:/Users/dbeltowski/MM Environments", "project_name": "Mirror"}
	[MAVENSMATE]: response from mm: {
	    "body": "UI Generated Successfully",
	    "body_type": "text", 
	    "success": true, 
	    "time": "1.3289999961853027"
	}
	[MAVENSMATE] failed to send community activity

This all started when I tried to save a file and MM gave me the error

	Server raised fault: 'INVALID_LOGIN: Invalid username, password, security token; or user locked out.'

I was working in this project/org yesterday and it was saving fine.  I was able to login to the org with no problems.  It seems almost as if MM has forgotten this project info.

**Comment by SuperPluck** [comment]
Same problem here. Anyone took a look at this?
