### ISSUE TITLE
Deploy Resource Bundle dialog showing ant scripts

### ISSUE THREAD

**Issue by seanidzenga** [joeferraro/MavensMate-SublimeText#747]
Unrelated to the other issue, this is more or less a nice-to-have...

When using sublime text to deploy a static resource bundle the dialog will show all files in the resource-bundles folder, this includes some ant script xml files that are used by coworkers who are not running mavensmate for their deploy process (shame on them!)

It'd be nice if this dialog filtered out anything that shouldn't be there just to cut down on the noise.

**Comment by steals** [comment]
It's not possible to exclude some files during deployment as there is no exact pattern of "unnecessary" files. If you don't need some files, for example *.xml, it doesn't mean no one don't need *.xml files.
Static resource (resource bundles) can contain any files. And it's your responsibility to include or exclude some files in resource bundles, but not the responsibility of the IDE.

**Comment by seanidzenga** [comment]
I'd just want to exclude them from the deployment dialogue, not from anything else. I'd not even pull them from git in the first place if that were an option.

Could some sort of ignore pattern attribute be added to mavensmate config? Similar to the ignore pattern you can add to sublime text.
