### ISSUE TITLE
MM downloads objects with custom fields from managed packages

### ISSUE THREAD

**Issue by Nailan** [joeferraro/MavensMate-SublimeText#748]
mm_ignore_managed_metadata is set to true. 
1) Create a new MM project with subscription to CustomObjects.
2) Update the project from server:
Result: MM downloaded all unmanaged objects, but they contain fields from managed packages.
Actually I'm trying to setup autodeploy from git repo and those custom fields from managed packages break deployments via Apache Ant: Cannot create a new component with the namespace: <managed package namespace>. Only components in the same namespace as the organization can be created through the API

**Comment by jhuizenga** [comment]
@joeferraro why was this issue closed? The behavior Nailan describes is in fact true. We have the same issue with our projects and would really appreciate if this could be solved.

**Comment by deanpearce** [comment]
We are still actively seeing this issue even with mm_ignore_managed_metadata set to true. Through other tools fields in the NVMConnect namespace were automatically removed, but when pulled with MavensMate those fields are present and causing deployment issues via the API.
