### ISSUE TITLE
What happens if you close the browser in the middle of a deployment?

### ISSUE THREAD

**Issue by 50471736** [joeferraro/MavensMate-SublimeText#751]
This question refers to the Windows MavensMate v6 Win7 64bit plugin for SublimeText.
If I accidentally close my browser in the middle of a deployment, does this abort the deployment?  See attached screen image.
![deploymentscreen](https://cloud.githubusercontent.com/assets/16543260/12094630/87b6c62a-b2d7-11e5-8df7-d053b7c62138.png)

**Comment by ralphcallaway** [comment]
afaik, no, this won't abort a deployment. however, salesforce allows you to cancel an in progress deployment. go to setup->deployment, and click cancel next to the deployment in progress

Under the covers the browser interface just looks pretty and talks to an underlying command line process, hence any processes initiated by the browser will continue after the browser is closed, although it's possible their may be post completion steps that would get skipped. 

This isn't something that's being designed for, so although things will probably work out fine in most cases, this isn't a viable technique for cancelling requests and could have unpredictable side-effects.

**Comment by ralphcallaway** [comment]
you might also look at https://github.com/joeferraro/MavensMate/issues/600 and add your thoughts there
