### ISSUE TITLE
Server operations stop after 1 or 2 successes

### ISSUE THREAD

**Issue by StevenWCox** [joeferraro/MavensMate-SublimeText#764]
I'm running the latest MM and Sublime Edit. After 1 or 2 successful server operations (save, refresh, run unit tests, etc), operations begin to timeout. This happens on several projects, and after restarting everything. Usually if I close and reopen the MM app, I can get another couple of successful operations.

**Comment by ralphcallaway** [comment]
hey @StevenWCox 

you might try switching to the pre-release version of the plugin (v7), it includes a rewrite of the core that offers a lot of performance improvements 

that said, frequently these timeouts are actually salesforce, a lot of the operations require doing a retrieve metadata call, which periodically starts taking several minutes even for very simple requests, if mm is slow, you might check if performing the same operation in the dev console or with ant is also slow

you also might consider increasing the `mm_timeout` setting

**Comment by StevenWCox** [comment]
That did the trick. Salesforce was definitely not the culprit - it was a very consistent problem with MM. Thanks @ralphcallaway!

**Comment by ralphcallaway** [comment]
@StevenWCox if it starts happening again, try and grab some logs and post the request again
