### ISSUE TITLE
<redacted>

### ISSUE THREAD

**Issue by JamesKosher** [joeferraro/MavensMate-SublimeText#773]
-redacted-

**Comment by willemmulder** [comment]
Haha, your comment is ridiculous. Unless you paid somebody for it, nobody should do anything for you, so I'm not sure what you're angry about. If it doesn't work for you, then bad luck, try something else.

**Comment by ralphcallaway** [comment]
wow, you know this is a volunteer project right? everyone has day jobs, and do this as a labor of love

if something doesn't work for you, man up and fix it, then submit a pull request, otherwise don't use it

i love this program and use it every day

**Comment by ralphcallaway** [comment]
@JamesKosher ps i'm closing this out since there really isn't constructive in here, but if you're having install issues please consider creating an issue with you're specifics that follows our contribution guidelines

**Comment by joeferraro** [comment]
lmao. it's always the people who have zero GitHub activity otherwise. this is the entirety of his feed:

<img width="558" alt="jameskosher__baum_realty_" src="https://cloud.githubusercontent.com/assets/54157/13761154/ec6c8b0e-ea04-11e5-95e1-0869988e036c.png">
