### ISSUE TITLE
Not able Create Project:[MAVENSMATE failed to send community activity]

### ISSUE THREAD

**Issue by vppravi93** [joeferraro/MavensMate-SublimeText#780]
Hi,
I tried to create setup mavenmate with sublime as mentioned [here](http://cloudyworlds.blogspot.in/2013/10/using-mavensmate-and-sublimetext-for.html).Everything went well except the project creation.When i tried to create a Project.i got below error in the console:
 **[MAVENSMATE] failed to send community activity**

OS : Window 8.1
Sublime V3(Build 3103)
Below is the Console.log for more info:

`
            [MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
Package Control: Skipping automatic upgrade, last run at 2016-04-24 00:24:50, next run at 2016-04-24 01:24:50 or after
[MAVENSMATE] failed to send community activity
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\Praveen P\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: {

    "body": "UI Generated Successfully", 

    "body_type": "text", 

    "success": true, 

    "time": "1.6429998874664307"

}

[MAVENSMATE] failed to send community activity
`

**Comment by lsamala** [comment]
This might be related to network firewall, try disconnecting from work network or network you are using and it might work or atleast you will be bypassing error: MAVENSMATE failed to send community activity

**Comment by vppravi93** [comment]
@isamala I tried to create the project by disabling the Firework in windows.But still am getting the same issue ** MAVENSMATE failed to send community activity**

**Comment by shanejayhayes** [comment]
I am getting a similar Failed to Send to Community Error.  I referred to an older thread and it did not resolve the issue.  This is a brand new Sublime and MM install so there are no issues with previous versions.  Workspace is set in both default and user settings.

[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\c16931\Downloads\Sublime Text Build 3103 x64\Data\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --ui -o new_project
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 151, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


[MAVENSMATE] failed to send community activity
