### ISSUE TITLE
Error: Could not create Trace Flags: LogType is required.: LogType

### ISSUE THREAD

**Issue by agentgill** [joeferraro/MavensMate-SublimeText#781]
Not sure where and how to fix this one. I'm guessing some setting has been knocked out.

Using Mac OS, Sublime Text and MavensMate v7

**Comment by sp0ken** [comment]
Same issue here and same softwares

**Comment by dfully0814** [comment]
Same issue here.

**Comment by jungblud** [comment]
Ditto.

**Comment by ckoppelman** [comment]
Duplicate of #126
