### ISSUE TITLE
Org updated to Summer '16 - Now I get compile errors

### ISSUE THREAD

**Issue by tglaess** [joeferraro/MavensMate-SublimeText#783]
My dev org upgraded to Summer '16 this weekend. When I save a VF page this morning, I get this error:

Result: [OPERATION FAILED]: Whoops, unable to parse the response. Please enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging) and post relevant log(s) to a new issue at https://github.com/joeferraro/MavensMate-SublimeText

[RESPONSE FROM MAVENSMATE]: {
    "operation": "compile-metadata", 
    "result": {
        "completedDate": "", 
        "status": "", 
        "id": "", 
        "numberTestsCompleted": 0, 
        "ignoreWarnings": false, 
        "createdByName": "", 
        "numberTestsTotal": 0, 
        "createdDate": "", 
        "success": false, 
        "done": false, 
        "runTestsEnabled": "false", 
        "lastModifiedDate": "", 
        "numberComponentsTotal": 0, 
        "numberComponentsDeployed": 0, 
        "numberComponentErrors": 1, 
        "startDate": "", 
        "rollbackOnError": false, 
        "checkOnly": false, 
        "createdBy": "", 
        "details": {
            "runTestResult": {
                "numFailures": "0", 
                "totalTime": "0.0", 
                "numTestsRun": "0"
            }, 
            "componentFailures": [
                {
                    "attributes": {
                        "url": "/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1dr180000010SKcAAM", 
                        "type": "ContainerAsyncRequest"
                    }, 
                    "IsCheckOnly": false, 
                    "Id": "1dr180000010SKcAAM", 
                    "DeployDetails": null, 
                    "State": "Error", 
                    "MetadataContainerId": "1dc18000000CDauAAG", 
                    "ErrorMsg": "An unexpected error has occurred. 80217062-25084 (1924580756)", 
                    "MetadataContainerMemberId": null
                }
            ], 
            "componentSuccesses": []
        }, 
        "numberTestErrors": 0
    }, 
    "complete": true, 
    "id": "99a643c0-15f5-11e6-b511-b763167381ec"
}

**Comment by tglaess** [comment]
Ok, this is strange. I was trying everything I could think of for an hour before I posted above. 5 minutes after I post, things start working. Sorry to bother you. Any ideas what would have caused the problem?

**Comment by tglaess** [comment]
I found some more information on this. If the VF has a compile error, you get the above message. If the page is fine, it compiles and saves just fine.

**Comment by amilabdallah** [comment]
I am having this issue as well.

**Comment by amilabdallah** [comment]
Are there any updates on this issue? I am getting this message a lot lately and it takes multiple attempts of compiling and saving until it finally decides to save.

**Comment by davehahn** [comment]
This is also affecting me quite frequently.  Sometimes it works fine, other times it fails for a bunch of times and then saves fine.  Some times I also receive a conflict with the server version, which doesn't usually happen.

**Comment by yiliangx** [comment]
Any update on this issue? It's impacting our dev as well.
