### ISSUE TITLE
Build 3113 of ST3 breaking Apex/VF syntax highlighting

### ISSUE THREAD

**Issue by jdcrensh** [joeferraro/MavensMate-SublimeText#784]
I just updated my SublimeText3 install to build 3113 from 3112. Apex and Visualforce syntax highlighting is now broken with the messages:

> Error loading syntax file "Packages/MavensMate/sublime/lang/Apex.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

> Error loading syntax file "Packages/MavensMate/sublime/lang/Visualforce.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

**Comment by OlegForce** [comment]
+1 
![capture](https://cloud.githubusercontent.com/assets/2013992/15236156/96f83568-1887-11e6-9035-4bc38558754f.PNG)

**Comment by tscottdev** [comment]
Same here: Error loading syntax file "Packages/MavensMate/sublime/lang/Apex.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit.

Looks like a general Sublime issue: https://forum.sublimetext.com/t/syntax-highlighting-problem-with-3113-apparent-recursion-within-a-with-prototype-action-25000-context-sanity-limit-hit/19914/12

**Comment by sp0ken** [comment]
Same here on MacOS build 3113
