### ISSUE TITLE
Upgraded to Sublime Text 3 v3114

### ISSUE THREAD

**Issue by rmillsdev** [joeferraro/MavensMate-SublimeText#786]
I upgraded Sublime Text 3 to v3114 and now I get this error message when I open Sublime.

Error loading syntax file "Packages\MavensMate\sublime\lang\Visualforce.sublime-syntax":
Unable to find Packages\MavensMate\sublime\lang\Visualforce.sublime-syntax

I look and the file is there. I downloaded the latest MavensMate and replaced the file with no success.

Any advise on how to fix?

**Comment by joeferraro** [comment]
Are you on Windows?

**Comment by rmillsdev** [comment]
Hi Joe,

Yes I am on win8. I did find a solution. It seems I had to re-select the type of syntax I wanted with the Visualforce page open. That seemed to reestablish the right connection.

I’ll update the issue soon.

Thanks
Richard
