### ISSUE TITLE
after going to new project in mavensmate the dialog is not showing 

### ISSUE THREAD

**Issue by Anil7569** [joeferraro/MavensMate-SublimeText#789]
i have installed sublime text 3 as portable version and installed mavens mate on it and changed the workspace directory. went to mavensmate>project>new project and nothing happening

**Comment by Anil7569** [comment]
Here is log

> Loading MavensMate for Sublime Text
mm_installer -->
user mm_path value is default, but mm not installed, forcing install
{'upload_url': 'https://uploads.github.com/repos/joeferraro/mm/releases/543050/assets{?name,label}', 'url': 'https://api.github.com/repos/joeferraro/mm/releases/543050', 'name': 'v0.2.4', 'body': '- Resolves package.xml parsing issue', 'assets_url': 'https://api.github.com/repos/joeferraro/mm/releases/543050/assets', 'id': 543050, 'draft': False, 'published_at': '2014-09-08T16:29:45Z', 'zipball_url': 'https://api.github.com/repos/joeferraro/mm/zipball/v0.2.4', 'author': {'url': 'https://api.github.com/users/joeferraro', 'login': 'joeferraro', 'id': 54157, 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}', 'type': 'User', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'gravatar_id': '', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'site_admin': False, 'html_url': 'https://github.com/joeferraro', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events'}, 'created_at': '2014-09-08T16:24:26Z', 'assets': [{'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232483', 'name': 'mm-linux.tar.gz', 'id': 232483, 'state': 'uploaded', 'size': 13496681, 'download_count': 2472, 'label': '', 'created_at': '2014-09-08T16:32:11Z', 'content_type': 'application/gzip', 'updated_at': '2014-09-08T16:32:16Z', 'uploader': {'url': 'https://api.github.com/users/joeferraro', 'login': 'joeferraro', 'id': 54157, 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}', 'type': 'User', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'gravatar_id': '', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'site_admin': False, 'html_url': 'https://github.com/joeferraro', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events'}, 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-linux.tar.gz'}, {'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232484', 'name': 'mm-osx-v0.2.4.zip', 'id': 232484, 'state': 'uploaded', 'size': 11164657, 'download_count': 19889, 'label': None, 'created_at': '2014-09-08T16:32:29Z', 'content_type': 'application/zip', 'updated_at': '2014-09-08T16:32:36Z', 'uploader': {'url': 'https://api.github.com/users/joeferraro', 'login': 'joeferraro', 'id': 54157, 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}', 'type': 'User', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'gravatar_id': '', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'site_admin': False, 'html_url': 'https://github.com/joeferraro', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events'}, 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-osx-v0.2.4.zip'}, {'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232481', 'name': 'mm-win-v0.2.4.zip', 'id': 232481, 'state': 'uploaded', 'size': 11502317, 'download_count': 43013, 'label': '', 'created_at': '2014-09-08T16:30:18Z', 'content_type': 'application/octet-stream', 'updated_at': '2014-09-08T16:30:22Z', 'uploader': {'url': 'https://api.github.com/users/joeferraro', 'login': 'joeferraro', 'id': 54157, 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}', 'type': 'User', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'gravatar_id': '', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'site_admin': False, 'html_url': 'https://github.com/joeferraro', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events'}, 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip'}], 'target_commitish': 'master', 'tarball_url': 'https://api.github.com/repos/joeferraro/mm/tarball/v0.2.4', 'html_url': 'https://github.com/joeferraro/mm/releases/tag/v0.2.4', 'tag_name': 'v0.2.4', 'prerelease': False}
latest asset ---->
{'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232481', 'name': 'mm-win-v0.2.4.zip', 'id': 232481, 'state': 'uploaded', 'size': 11502317, 'download_count': 43013, 'label': '', 'created_at': '2014-09-08T16:30:18Z', 'content_type': 'application/octet-stream', 'updated_at': '2014-09-08T16:30:22Z', 'uploader': {'url': 'https://api.github.com/users/joeferraro', 'login': 'joeferraro', 'id': 54157, 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}', 'type': 'User', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'gravatar_id': '', 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'site_admin': False, 'html_url': 'https://github.com/joeferraro', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events'}, 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip'}
handling result of mm update!!!
Loading MavensMate for Sublime Text
mm_installer -->
checking for updated mm version
mm is up to date (0.2.4), no further action needed
Calling mm_interface
OPERATION: new_project
{}
Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}


Calling mm_interface
OPERATION: new_project
{}
mm command: 
"D:\Sublime Text Build 3114 x64\Data\Packages\User\MavensMate\mm\mm.exe" -o new_project --ui -c SUBLIME_TEXT_3
{}
response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 60, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 47, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.connection\", line 145, in get_workspace\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}

**Comment by joeferraro** [comment]
v6 does not work with the portable version of sublime, unfortunately. you will need to update to the v7 betas https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas
