### ISSUE TITLE
Not able to create a new project in mavensmate

### ISSUE THREAD

**Issue by lalitsngh** [joeferraro/MavensMate-SublimeText#799]
Hi I am not able to create a new project in mavensmate please help
![capture](https://cloud.githubusercontent.com/assets/9973452/15855780/1ffbe67e-2ccf-11e6-9b63-dbd0b38f0f14.PNG)

**Comment by kshitizsrivastava** [comment]
![new project error](https://cloud.githubusercontent.com/assets/19847829/15950507/6c079482-2e64-11e6-9d2d-a0967b3f21e4.png)

Yup. I can't either. Your snapshot doesnt show the error, so I uploaded mine.

It says "Client[commandClassName] is not a function"

**Comment by digamberprasad** [comment]
I am not able to create new project either. Any update on this please?
