### ISSUE TITLE
Nobody panic. Salesforce is deprecating TLS 1.0

### ISSUE THREAD

**Issue by aklef** [joeferraro/MavensMate-SublimeText#800]
I brought my towel for this..

The issues #799, especially #798, #797 #769 are all related to this. This is a Xpost from https://github.com/joeferraro/MavensMate/issues/678

I've been getting the exact error as seen below, linked from #797 as of today.
> ERROR:suds.client: {SF_USERID} {SF_PASSWORD} {"body": "Server raised fault: 'LOGIN_DURING_RESTRICTED_DOMAIN: cannot log in from current domain'", "stack_trace": "Traceback (most recent call last):\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request\", line 93, in execute\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.commands.project\", line 39, in execute\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.project\", line 112, in retrieve_and_write_to_disk\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sfdc_client\", line 96, in init\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sfdc_client\", line 110, in login\nWebFault: Server raised fault: 'LOGIN_DURING_RESTRICTED_DOMAIN: cannot log in from current domain'\n", "success": false} 

Esentially, this: https://help.salesforce.com/apex/HTViewSolution?id=000221207 is happening.

See https://help.salesforce.com/apex/HTViewSolution?urlname=TLS-1-0-Disablement-Critical-Update-Console-CRUC-Setting&language=en_US

https://github.com/joeferraro/MavensMate/issues/645  was created as part of this change and the listed solution was as follows:

> goarnold commented on Mar 10
> I ran into the same issue and was able to resolve it by installing v7 beta.
> 
> Here is the original link to the issue: joeferraro/MavensMate-SublimeText#769
> 
> Here is the link to how to install the v7 beta for sublime: https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas

Meaning that MavensMate itself needs to be upgraded to v7 everywhere PRONTO.

**Comment by joeferraro** [comment]
Hi, thanks for the issue, but please do not create duplicate issues. Closing as a dup of https://github.com/joeferraro/MavensMate/issues/678
