### ISSUE TITLE
Unable to save 

### ISSUE THREAD

**Issue by wrone** [joeferraro/MavensMate-SublimeText#802]
Result: [OPERATION FAILED]: Whoops, unable to parse the response.

[RESPONSE FROM MAVENSMATE]: {
    "result": {
        "rollbackOnError": false, 
        "id": "", 
        "completedDate": "", 
        "numberComponentsDeployed": 0, 
        "success": false, 
        "createdDate": "", 
        "done": false, 
        "lastModifiedDate": "", 
        "numberComponentsTotal": 0, 
        "ignoreWarnings": false, 
        "numberTestsTotal": 0, 
        "numberTestErrors": 0, 
        "numberTestsCompleted": 0, 
        "numberComponentErrors": 1, 
        "runTestsEnabled": "false", 
        "createdByName": "", 
        "createdBy": "", 
        "checkOnly": false, 
        "details": {
            "componentSuccesses": [], 
            "componentFailures": [
                {
                    "DeployDetails": null, 
                    "Id": "1dr3E000000I4L9QAK", 
                    "attributes": {
                        "type": "ContainerAsyncRequest", 
                        "url": "/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest/1dr3E000000I4L9QAK"
                    }, 
                    "MetadataContainerId": "1dc3E0000001El8QAE", 
                    "ErrorMsg": "An unexpected error has occurred. 2061968264-751 (1924580756)", 
                    "State": "Error", 
                    "MetadataContainerMemberId": null, 
                    "IsCheckOnly": false
                }
            ], 
            "runTestResult": {
                "numTestsRun": "0", 
                "numFailures": "0", 
                "totalTime": "0.0"
            }
        }, 
        "status": "", 
        "startDate": ""
    }, 
    "id": "9351ff60-312e-11e6-a731-abb4f5abd093", 
    "operation": "compile-metadata", 
    "complete": true
}

**Comment by amilabdallah** [comment]
Issue has been logged as a bug already. https://github.com/joeferraro/MavensMate-SublimeText/issues/783   It's been almost 2 months with no response/comment though.  I've had to resort to disabling the tooling api and enabling the legacy compile from the mavenmsate settings in order to compile, however it takes so long I'm almost tempted to use the dev console to make code changes.
