### ISSUE TITLE
Problem upgrading to v7 beta 

### ISSUE THREAD

**Issue by Hcrouse** [joeferraro/MavensMate-SublimeText#810]
MavensMate V6
Sublime Text 3
MavensMate Ap v0.0.10
OSX 10.11.5 (15F34)

Sublime packageControl user settings.
`{
	"bootstrapped": true,
	"in_process_packages":
	[
             "MavensMate"
	],
	"installed_packages":
	[
	    "MavensMate"
	]
}`

When I attempt to upgrade packages I get a message that "There are no packages ready for upgrade".

**Comment by mbotos** [comment]
Try adding MavensMate to install_prereleases:
![8cf6d800-5152-11e5-925e-627995a4aef5](https://cloud.githubusercontent.com/assets/737005/16417763/229dd558-3d15-11e6-81d4-fce61da8ec8a.png)
