### ISSUE TITLE
HELP! Trouble With MavensMate & Sublime Text NOT WORKING AT ALL

### ISSUE THREAD

**Issue by TigMH** [joeferraro/MavensMate-SublimeText#811]
When trying to setup a project for a change set this morning I received an error about the TLS 1.0 issue.  

I am on Sublime Text build 3114.

I have tried following your instructions for the Version 6 Stable, and still received error message.  I then followed the instructions for the Version 7 prerelease channel.  I ensured that MavensMate was added to Package control "install-prereleases" user setting.  I installed the MavensMate-app: "MavensMate-app-v0.0.10-osx-x64.zip" as instructed.  

Now nothing is working, I keep getting an error that it could not contact local mavensmate server:

MavensMate for Sublime Text v7.0.0-beta.3

[ERROR]: Could not contact local MavensMate server, please ensure MavensMate-app is installed and running. 

In version 7+ of MavensMate for Sublime Text, there is a new companion app called MavensMate-app. You must download, install, and run this application in order for the MavensMate for Sublime Text plugin to operate. For more information, please visit https://github.com/joeferraro/MavensMate-app

 
                                                                          
Operation: Handling requested operation...
Timestamp: Mon, 27 Jun 2016 16:00:51
   Result: [ERROR]: Request to the local MavensMate server failed. please ensure the MavensMate-app is installer and running.

In version 7+ of MavensMate for Sublime Text, there is a new companion app called MavensMate-app. You must download, install, and run this application in order for the MavensMate for Sublime Text plugin to operate. For more information, please visit https://github.com/joeferraro/MavensMate-app

Please advise what to do, as I use MavensMate for pushing change sets, and this has brought me to a complete stop.

**Comment by surgaya1** [comment]
Hi,
Any updates on this post. Iam getting the same error today morning . I have installed the set up but still its giving error.

 Result: [ERROR]: Request to the local MavensMate server failed. please ensure the MavensMate-app is installer and running.

In version 7+ of MavensMate for Sublime Text, there is a new companion app called MavensMate-app. You must download, install, and run this application in order for the MavensMate for Sublime Text plugin to operate. For more information, please visit https://github.com/joeferraro/MavensMate-app

**Comment by moderatelyfunky** [comment]
Apparently, something changed over the weekend.  I now get the same error.  I tried to install the MavensMate-app but am on Windows and couldn't find an install.  Would appreciate any advice.

**Comment by mbasovich** [comment]
install a stable version from 
https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.10

**Comment by mbasovich** [comment]
Do not forget to Uninstall the previously installed MavenMates before installing a new one

**Comment by moderatelyfunky** [comment]
This worked a treat.  Thanks for the great software and support!
