### ISSUE TITLE
No Local Index Found - Clean Project

### ISSUE THREAD

**Issue by mahavrilla** [joeferraro/MavensMate-SublimeText#830]
As I work in multiple orgs across a variety of git repos, I am running into the issue where file that I have not actively worked on cannot be run in tests, or if I do work on them cannot be saved due to the error:

```
Result: [ERROR]: No local index found for ClassName. This can happen if you fetch your project from a remote git repository. Please ensure your project subscription includes the metadata type: "ApexClass", then run the "Clean Project" command to update your local index of metadata.o local index found for FamilyDocumentListControllerTest. This can happen if you fetch your project from a remote git repository. Please ensure your project subscription includes the metadata type: "ApexClass", then run the "Clean Project" command to update your local index of metadata.
```

I'm hoping theres a way to `Clean` your project without pulling down all the metadata and overwriting the codebase that I have locally. It causes issues with diffs. I'm unfamiliar if this is MavensMate error or an Salesforce specific error. 

The way I've currently worked around it is through compiling the `meta.xml` file to the server first.

**Comment by apoorvamathur12** [comment]
Hey Joeferraro,

I am also having the same issue. Can you please provide me the solution if you have any

**Comment by jebamania** [comment]
I am receiving this error on saving classes to I create with the MavensMate App. I don't connect git repos directly to my editor. I have v0.0.10

**Comment by fedegiust** [comment]
I've had the same issue today and found out that it was due to the filename being case sensitive.

In my case I had a file called SubscriberApi.cls but the class name was SubscriberAPI and on the index (config/.local_store) was as SubscriberAPI.cls.

I went in and edited .local_store and changed the cls file name to SubscriberApi (same as on the file system and SF) and worked.
