### ISSUE TITLE
[ERROR]: Request to the local MavensMate server failed. please ensure the MavensMate-app is installer and running.

### ISSUE THREAD

**Issue by lynnellemmanuel** [joeferraro/MavensMate-SublimeText#837]
The error is accompanied with the following statement:

> In version 7+ of MavensMate for Sublime Text, there is a new companion app called MavensMate-app. You must download, install, and run this application in order for the MavensMate for Sublime Text plugin to operate. For more information, please visit https://github.com/joeferraro/MavensMate-app

However, I tried to visit https://github.com/joeferraro/MavensMate-app but it only redirects me to https://github.com/joeferraro/MavensMate-Desktop and I don't know what to do now. Please help.

**Comment by CTconsultEA** [comment]
Same problem for me here.

**Comment by lynnellemmanuel** [comment]
Here's what I did earlier to solve this:
1. Downloaded MavensMate Desktop here: https://github.com/joeferraro/MavensMate-Desktop/releases . I guess that's what they mean about MavensMate App.
2. I removed and installed MavensMate in Sublime Text. This link can help you: https://github.com/joeferraro/MavensMate-SublimeText#install

And wallah! The bug is solved:

> MavensMate for Sublime Text v7.0.0
> You are now running a stable version of MavensMate for Sublime Text. Over the next few days, we will start to push prereleases in anticipation of the new version of MavensMate-Desktop. If you do not want to install these prereleases, you must remove "MavensMate" from your Package Control "install_prereleases" setting. For more information: https://github.com/joeferraro/MavensMate-SublimeText#install

I guess that instructions are not clear or at least not that comprehensive for simple users like us. But anyway, I'm happy that everything's working now.

**Comment by CTconsultEA** [comment]
What I've done:
1. You must install new desktop application https://github.com/joeferraro/MavensMate-Desktop/releases 
2. You must open this application(NOT SUBLIME) and set your workspace in it. I have my workspace in C:/mavensmate/ and my mm_workspace is "/mavensmate".
3. In sublime go to MavensMate => Settings => User Plugin Settings and set mm_mavensmate_app_location to path to the MavensMate application. In my case it was 
`"mm_mavensmate_app_location" : {
		"osx": "/Applications/MavensMate.app",
		"windows": "C:\\Program Files\\MavensMate\\MavensMate.exe",
		"linux": ""
	},`
4. Restart sublime and recreate project - the old projects are no longer supported (at least for me, when I'm trying to open my old projects, it shows "Unable to read project...").
5. Don't shut down MavensMate application - it must be opened for proper work of MavensMate in Sublime.
