### ISSUE TITLE
Automatic update to v7 (again)

### ISSUE THREAD

**Issue by devrieslex** [joeferraro/MavensMate-SublimeText#838]
Hey,

I've been automatically updated to the version in which I'm forced to use the MavensMate app (version 7). I did not have MavensMate set to automatically update. 
Please tell my how to revert to version 6.

Lex

**Comment by ohaucke** [comment]
* Open Package Control
* uninstall MM
* change Package Control settings (disable auto update `"auto_upgrade": false,`)
* download 6.0.3 from [here](https://github.com/joeferraro/MavensMate-SublimeText/releases/tag/v6.0.3)
* extract the content to `%appdata%\Sublime Text 3\Packages\MavensMate` (WIndows)
* rename `%appdata%\Sublime Text 3\Packages\User\mavensmate-deprecated.sublime-settings` to `mavensmate.sublime-settings`
* start sublime

**Comment by joeferraro** [comment]
@ohaucke cheers. 

v6 uses tls 1.0 which is [no longer supported by most salesforce environments due to vulnerabilities](https://help.salesforce.com/apex/HTViewSolution?id=000221207). my suggestion would be to upgrade to v7 for security purposes.

**Comment by devrieslex** [comment]
I thought that was only on Mac?

**Comment by ohaucke** [comment]
@joeferraro Is the MM-Desktop App useable?
The last time i "tried" it (was v5? v4.0.5? or v6) and nothing worked, but i need a working enviroment to do my stuff! If you say the App is useable i'll give it another shot.
