### ISSUE TITLE
Unable to Parse Response

### ISSUE THREAD

**Issue by yperez** [joeferraro/MavensMate-SublimeText#839]
Generated when trying to compile a class:
v7.0.0-beta.3
app version 0.0.10

 Result: [OPERATION FAILED]: Whoops, unable to parse the response. Please enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging) and post relevant log(s) to a new issue at https://github.com/joeferraro/MavensMate-SublimeText
[RESPONSE FROM MAVENSMATE]: {
    "complete": true, 
    "result": {
        "numberComponentsDeployed": 0, 
        "numberTestErrors": 0, 
        "details": {
            "componentSuccesses": [], 
            "runTestResult": {
                "numFailures": "0", 
                "numTestsRun": "0", 
                "totalTime": "0.0"
            }, 
            "componentFailures": [
                {
                    "ErrorMsg": null, 
                    "MetadataContainerId": "1dc3C000000000zQAA", 
                    "MetadataContainerMemberId": null, 
                    "IsCheckOnly": false, 
                    "attributes": {
                        "type": "ContainerAsyncRequest", 
                        "url": "/services/data/v37.0/tooling/sobjects/ContainerAsyncRequest/1dr3C0000008OIjQAM"
                    }, 
                    "State": "Failed", 
                    "Id": "1dr3C0000008OIjQAM", 
                    "DeployDetails": {
                        "runTestResult": null, 
                        "componentSuccesses": [], 
                        "componentFailures": [
                            {
                                "requiresProductionTestRun": false, 
                                "forPackageManifestFile": false, 
                                "lineNumber": 413, 
                                "success": false, 
                                "columnNumber": null, 
                                "changed": false, 
                                "problemType": "Error", 
                                "id": "01p61000008GDUWAA4", 
                                "fileName": "classes/AssetTriggerActions.cls", 
                                "knownPackagingProblem": false, 
                                "problem": "unexpected token: '<EOF>'", 
                                "componentType": "ApexClass", 
                                "created": false, 
                                "fullName": "AssetTriggerActions", 
                                "createdDate": "2016-09-12T14:31:52.413+0000", 
                                "warning": false, 
                                "deleted": false
                            }
                        ], 
                        "allComponentMessages": [
                            {
                                "requiresProductionTestRun": false, 
                                "forPackageManifestFile": false, 
                                "lineNumber": 413, 
                                "success": false, 
                                "columnNumber": null, 
                                "changed": false, 
                                "problemType": "Error", 
                                "id": "01p61000008GDUWAA4", 
                                "fileName": "classes/AssetTriggerActions.cls", 
                                "knownPackagingProblem": false, 
                                "problem": "unexpected token: '<EOF>'", 
                                "componentType": "ApexClass", 
                                "created": false, 
                                "fullName": "AssetTriggerActions", 
                                "createdDate": "2016-09-12T14:31:52.413+0000", 
                                "warning": false, 
                                "deleted": false
                            }
                        ]
                    }
                }
            ]
        }, 
        "rollbackOnError": false, 
        "status": "", 
        "numberComponentsTotal": 0, 
        "numberTestsTotal": 0, 
        "done": false, 
        "createdByName": "", 
        "runTestsEnabled": "false", 
        "id": "", 
        "ignoreWarnings": false, 
        "completedDate": "", 
        "startDate": "", 
        "checkOnly": false, 
        "createdBy": "", 
        "lastModifiedDate": "", 
        "numberTestsCompleted": 0, 
        "success": false, 
        "createdDate": "", 
        "numberComponentErrors": 1
    }, 
    "id": "a3b9c400-78f5-11e6-9e8e-277e3171d8b4", 
    "operation": "compile-metadata"
}

**Comment by yperez** [comment]
Cleaned the project. No longer reproducible.

**Comment by wnczwl369** [comment]
'Cleaned the project',  what does it mean? any steps? thanks @yperez
