### ISSUE TITLE
Sandbox project type not pointing to test.salesforce.com

### ISSUE THREAD

**Issue by ttagg2020** [joeferraro/MavensMate-SublimeText#841]
I'm trying to create a Sandbox project and am not able to login, it looks like because the url that is being pointed to is https://login.salesforce.com/ not https://test.salesforce.com/

I tried using the custom domain and putting test.salesforce.com there, but am getting this error: 

"Error initializing project: Unexpected token in JSON at position 835"

**Comment by joeferraro** [comment]
This issue was moved to joeferraro/MavensMate#738
