### ISSUE TITLE
JS error when project is being created

### ISSUE THREAD

**Issue by SerhiiKushnirenko** [joeferraro/MavensMate-SublimeText#842]
read ECONNRESET error,
in any time when I am trying to create project, or refresh metadata on existed project

**Comment by SerhiiKushnirenko** [comment]
Platform: Windows 10 - 64 Bit
Sublime Text: Version 3.0 - Build 3114
MavensMate: MavensMate-SublimeText 7.0.0 + MavensMate-app v0.0.10

**Comment by joeferraro** [comment]
This issue was moved to joeferraro/MavensMate#737
