### ISSUE TITLE
Unable to refresh Resource Bundle

### ISSUE THREAD

**Issue by ismohamed** [joeferraro/MavensMate-SublimeText#844]
Hi, I am unable to refresh the resource-bundle in Sublime Text 3. When I right-click on the resource bundle directory and select Mavensmate, Refresh Resource Bundle(s), nothing happens. I have looked in the text console and do not see any output either. If I refresh the project itself, it refreshes all the files (except the resource bundle of course). The only way for me currently to get the updated resource bundle is by physically deleting the resource bundle directory and then creating it again from the static resource file. The mavens-mate desktop app is running. The sublime plugin version for mavensmate is v7.0.0 and the desktio app is v.0.0.10. Is there a setting I am missing somewhere?

About a week ago, I did not need mavensmate desktop app running either and I did not have the refresh resource bundle issue either. Ever since I needed the mavensmate desktop app this issue has arised.

**Comment by joeferraro** [comment]
This issue was moved to joeferraro/MavensMate#735
