### ISSUE TITLE
Cannot read property 'result' of null

### ISSUE THREAD

**Issue by prateekgoel1503** [joeferraro/MavensMate-SublimeText#846]
While creating the project I am facing an issue. Cannot read property 'result' of null. Not able to identify the cause for this. 

Need help to identify and resolve this issue.
![sublime text issue](https://cloud.githubusercontent.com/assets/22494264/18910068/fe907630-8593-11e6-9184-c6322dca221c.PNG)

**Comment by prateekgoel1503** [comment]
Is there anyone who faced this issue?

**Comment by prateekgoel1503** [comment]
@joeferraro Can you please help me out with this issue

**Comment by sridhiraj** [comment]
Any solution on this.. I've tried with latest Maven's mate (MavensMate-app-v0.0.10-win-x64-setup) ??
