### ISSUE TITLE
Error initializing project

### ISSUE THREAD

**Issue by thierrytrouin** [joeferraro/MavensMate-SublimeText#853]
Hi,

I'm a Salesforce developper 
I have a bug with sublime Text 
I can neither edit, refresh, create apex class nor any other operations...
Some projects works and others not!
Thank's for your Help

Environment:
===========
Win 10
Sublime text 3
MavensMate for Sublime Text v7.0.2
MavensMate app V0.0.10
Project workspace is sync with bitbucket using sourcetree

ERROR START:
===========
MavensMate for Sublime Text v7.0.2
                                                                         
Operation: Handling requested operation...
Timestamp: Wed, 18 Jan 2017 15:47:34
   Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: Unexpected token <
                                                      
Operation: Opening Edit Project dialog
Timestamp: Wed, 18 Jan 2017 15:58:03
   Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: Unexpected token <
                                                       
Operation: Opening New Metadata UI
Timestamp: Wed, 18 Jan 2017 15:58:13
   Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: Unexpected token <

ERROR END:
===========

**Comment by thierrytrouin** [comment]
Hello Everyone,

No one has a solutions for this issue ?

Many thanks

**Comment by thierrytrouin** [comment]
Hello Everyone,

Is my problem not detailed enough or is it too complicated to fix it ?
Many thanks for your help
Thierry

**Comment by srujan21** [comment]
Did you started mavensmate before saving from sublime ?

**Comment by kidtsunami** [comment]
@thierrytrouin have you recently updated MavensMate and have old projects you created with the old version?

**Comment by thierrytrouin** [comment]
Thank you for your answers.
Whether I open Mavensmate or sublime first, it does not change anything.
Mavensmate has not been updated. The project is created with the current version of Mavensmate.
Note :
In Mavensmate, I do not have all my projects visible.

**Comment by thierrytrouin** [comment]
In the directory, the number of projects is different...

Widows folder Directory
=================
![image](https://cloud.githubusercontent.com/assets/25202699/22335080/85b1dff8-e3dd-11e6-961d-460472a7e22d.png)

Mavensmate Project Directory
=======================
![capture1](https://cloud.githubusercontent.com/assets/25202699/22335112/a5e4d7a8-e3dd-11e6-8669-69be43849ed4.PNG)

**Comment by kidtsunami** [comment]
Can you try re-creating the projects that are not visible in MavensMate?

**Comment by thierrytrouin** [comment]
Yes I can, but it also means that I should restart the sync to bitbucket with sourcetree (and all associated settings)
Having already spent some time to configured this, I would not want to have to do the same job again

**Comment by joeferraro** [comment]
@thierrytrouin have you tried the 0.0.11 betas? That may resolve your issue.

**Comment by thierrytrouin** [comment]
I have Created the project (without sync with bitbucket)

![image](https://cloud.githubusercontent.com/assets/25202699/22336418/7f8da904-e3e2-11e6-80e1-13fff652030d.png)


I have Created the project (without sync with bitbucket)
It's impossible to open it with the button "Open in sublime" (no error message)
I close, sublime and Mavensmate and open Mavensmate

The new project is avalaible in windows directory and not in sublime.
The project is avalaible in sublime but when i would refresh this, I have the same error

error
=====
                                                                         
Operation: Refreshing: C:\Users\Thierry\Projets local\mavensmate_workspace\clientProject.sbfull2\src
Timestamp: Thu, 26 Jan 2017 16:26:57
   Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: Unexpected token <

**Comment by thierrytrouin** [comment]
HI @joeferraro,

I do not use beta versions, but I'll test it.
Thanks

**Comment by thierrytrouin** [comment]
Hi,

I have updated Mavensmate to the version "v0.0.11-beta.7"
I have always error. but this message existed not before.
What is it ?

"in JSON at position 49" 

Info : Projects directory are always different betwen Sublime and Mavensmate

Many thanks

Error message
=======
MavensMate for Sublime Text v7.0.2
                                                                           
Operation: Refreshing: C:\Users\Thierry\Projets local\mavensmate_workspace\ClientName.sbfull
Timestamp: Thu, 26 Jan 2017 18:31:21
   Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: Unexpected token < in JSON at position 49

**Comment by thierrytrouin** [comment]
Hi Everyone,

I'm still blocked, somebody would have an answer ?
Many thanks for your help.

**Comment by thierrytrouin** [comment]
Hi @joeferraro , Hi All,

Would you have others solutions for my problem?
Many thanks,
Thierry

**Comment by thierrytrouin** [comment]
Hello everyone,

Is my problem so difficult, so no one has a solution?
It's been 15 days that I cannot develop with sublime/mavensmate.
I will not use "Eclipse" again !

Many thanks,
Thierry

**Comment by kidtsunami** [comment]
@thierrytrouin if you don't have this sorted by next week, I'll set aside some time where we can get on a call and sort this out for you.

Also have you tried using MavensMate for VS Code? I doubt it will rectify your issue, but it's certainly possible...

**Comment by thierrytrouin** [comment]
thanks for reply @kidtsunami ,

Mavensmat work with VS Code.
But I have only 4 projects in mavensmate "open project" menu.
My project folder contains 23 projects.

The 4 projects work with Sublime and VS code.
The 19 others projects does not work, no more...


![image](https://cloud.githubusercontent.com/assets/25202699/22597903/d2ad30a0-ea31-11e6-932f-5ec640f16f30.png)


Many thanks for your help

**Comment by thierrytrouin** [comment]
Hello all,

I followed this procedure. It worked for 2 projects but not for the others :
https://github.com/joeferraro/MavensMate-SublimeText/wiki/Connecting-MavensMate-to-an-existing-project

Would anyone have any other idea?

Many thanks,
Thierry

**Comment by kidtsunami** [comment]
@thierrytrouin do the projects that not show up have a file in them at the path
`{mavensmate}/{projectpath}/config/.settings`
?

**Comment by thierrytrouin** [comment]
Hi @kidtsunami , 
I have this file for all projects

Content
=========
{
    "projectName": "Client.sbfull",
    "username": "name@client.fr.sbfull",
    "id": "fa63f770-a687-11e6-9215-a356b1239293",
    "namespace": "",
    "environment": "sandbox",
    "loginUrl": "https://test.salesforce.com/",
    "workspace": "C:\\Users\\Thierry\\Projets local\\mavensmate_workspace",
    "subscription": [
        "ApexClass",
        "ApexComponent",
        "ApexPage",
        "ApexTrigger",
        "StaticResource"
    ]
}

**Comment by kidtsunami** [comment]
Can you share the project path and name of a project that does show up and one that doesn't?

**Comment by thierrytrouin** [comment]
Hi @kidtsunami ,
I have checked the directory.
On the bad project, only folder config not contains 2 missing files 
![image](https://cloud.githubusercontent.com/assets/25202699/23125795/d3c0aba8-f773-11e6-8e45-47d83d3f9ef8.png)

The file ".settings" not contains 2 attributes:
 - "orgType": "sandbox"
 - "instanceUrl": "https://cs31.salesforce.com"

Other attributes are the same.

When i have the following message, which file is concerned?

![image](https://cloud.githubusercontent.com/assets/25202699/23125869/31e2e692-f774-11e6-8b44-fb5a61dab9a9.png)

**Comment by cloudpremise** [comment]
I was having this same issue.  I was able to fix it by rebuilding my project folders within the workspace and simplifying the number of metadata components that I was adding to each project.  There must be some issue related to the amount of projects and/or metadata components that the app can support.

**Comment by thierrytrouin** [comment]
Everything worked fine, until a "mavensmate" update.
Existing projects are not taken over and the new projects, 1 time out of 2, does not work.
It's possible to create several times the same project, until it works, but it is not the best solution...

Many thanks,
Thierry

**Comment by thierrytrouin** [comment]
Hi all,

I have always the problem. Do you have any solution ?
Now I have a new problem, I can’t create new project.
I use the version : v0.0.11-beta.7
Many thanks for your help.

![image](https://cloud.githubusercontent.com/assets/25202699/24139331/fdad755e-0e1b-11e7-800b-9ee5020fb66d.png)

**Comment by AziEI** [comment]
Experience the same issue. I'm not even able to recreate a project, after clicking "Create Project" getting the same issue.
![image](https://cloud.githubusercontent.com/assets/8708643/24409315/90a8f0d8-13d8-11e7-9dd8-9867f273e758.png)

**Comment by AziEI** [comment]
Was able to quickly fix it moving some old projects to another folder, so seems the issue's somehow connected to number of projects in the workspace folder.

**Comment by thierrytrouin** [comment]
many thanks @AziEI,

You have the solution.
I can now edit existing projets and create new projects.

Best regards,
Thierry
