### ISSUE TITLE
can't find 'User' under 'Settings'. I can see 'User plugin settings'  , Default plugin settings' and 'Global settings'. Please help.

### ISSUE THREAD

**Issue by soffiya** [joeferraro/MavensMate-SublimeText#860]
*****
*****

Please do not create a new issue in this repository, we've left issues open on this project for SEO/historical purposes *only*. If you need to create an issue, please do so at the central MavensMate issues repository: https://github.com/joeferraro/MavensMate/issues

Thank you!

*****
*****

**Comment by soffiya** [comment]
Hi Joe,How can I fix it?

On Friday 11 August 2017, 7:58:04 PM IST, Joe Ferraro <notifications@github.com> wrote:


Closed #860.

**Comment by soffiya** [comment]
I am a new coder. Please help me to fix it.

Thanks,Angie

On Friday 11 August 2017, 7:58:04 PM IST, Joe Ferraro <notifications@github.com> wrote:


Closed #860.

**Comment by kidtsunami** [comment]
@soffiya Hi, you need to submit the issue against https://github.com/joeferraro/MavensMate/issues
