### ISSUE TITLE
Synchronize with Server

### ISSUE THREAD

**Issue by ceiroa** [joeferraro/MavensMate-SublimeText#87]
Right now in the Force.com IDE you can choose the src folder (or any folder or file below it) and do "right click > Force.com > Synchronize with Server". 

This functionality allows you to see files that the org has changed on its own (as it sometimes happens with permissions-related files) and pull those changes, as well as see the files that have changed locally and force those changes to be implemented in the server (even when the IDE complains that the copy in the server is more recent).

Does this functionality exist or could it be implemented in MavensMate? My team at work is seriously considering moving from the Force.com IDE to MavensMate, but this is the only piece we are missing.

**Comment by NewToCodeAndOldToIT** [comment]
Hello @doublesharp Our team installed MavensMate-Desktop-Setup-0.0.11-beta.7-ia32 and Sublime Text 3 for working with Force.com. But it just keeps overriding each others code every time we save it. It has become a big issue for us. We are new to this. Is there anything we are missing?

**Comment by stephenroden** [comment]
Hi @NewToCodeAndOldToIT, in MavensMate's global settings can you see if "Check conflicts before compile (mm_compile_check_conflicts) is checked.

**Comment by NewToCodeAndOldToIT** [comment]
Hello @stephenroden, Thanks for replying. Yes I checked it and the checkbox is checked. 
<img width="407" alt="mavensmate" src="https://user-images.githubusercontent.com/30958605/29251558-bac00218-8024-11e7-8a5e-bf2ff0a9068a.PNG">
